### ISSUE TITLE
SELECT DISTINCT foo ON (bar)

### ISSUE THREAD

**Issue by gfredericks** [jkk/honeysql#1]
I was trying to generate a `SELECT DISTINCT ON (bar) foo` recently and the only mechanism I could figure out was:

``` clojure
(-> (select :foo)
    (modifiers "DISTINCT ON (bar)")
    (sql/format))

;; => ["SELECT DISTINCT ON (BAR) foo "]
```

which feels like unintended usage, but at least works (at least because SQL isn't case-sensitive).

Is there a better way to do this, or a straightforward design as a new feature that I could add?

**Comment by emidln** [comment]
`SELECT DISTINCT ON (bar), foo` isn't legal in PostgreSQL at least.
