### ISSUE TITLE
Is there a way to generate intersect queries ? 

### ISSUE THREAD

**Issue by bcambel** [jkk/honeysql#102]
My assumption was that they would be very similar to union and union-all queries but I assume they're not implemented yet. Is that the case ? 

Thanks, Bahadir

**Comment by jakemcc** [comment]
@bcambel Just pulled out our extension to honeysql that adds intersect support and submitted a PR.

Pretty straight forward to extend in your own project though.

```clojure
;; honeysql.format required as `hformat` in files `ns` form.

(defmethod hformat/format-clause :intersect
  [[_ maps] _]
  (string/join " INTERSECT " (map hformat/to-sql maps)))
```

**Comment by bcambel** [comment]
ah great, thanks @jakemcc!
