### ISSUE TITLE
Array formatting error

### ISSUE THREAD

**Issue by icambron** [jkk/honeysql#104]
I'm having trouble creating an insert statement with an array and also other stuff.

```clj
dev=> (fmt/format {:insert-into :foo :columns [:bar :baz] :values [{:bar [#sql/array ["one" "two" "three"]] :baz "hi"}]})
["INSERT INTO foo (bar, baz) (baz, bar) VALUES (?, ARRAY[?, ?, ?] NULL)" "hi" "one" "two" "three"]
```

Notice the extra `NULL` tacked onto the value list, which breaks things. I'll try to look into this a bit deeper when I have some time and see if I can suss out the issue.

**Comment by MichaelBlume** [comment]
Strange, thanks for looking into it.

**Comment by icambron** [comment]
User error. I shouldn't have been wrapping the array in brackets, which royally confuses the formatter. This works fine:

```clj
user=> (fmt/format {:insert-into [:foo] :columns [:bar :baz] :values [{:bar (types/array ["one" "two" "three"]) :baz "hi"}]})
nil!
["INSERT INTO foo NULL (bar, baz) (bar, baz) VALUES (ARRAY[?, ?, ?], ?)" "one" "two" "three" "hi"]
```

Sorry for the noise.
