### ISSUE TITLE
Adding ILIKE support

### ISSUE THREAD

**Issue by cjauvin** [jkk/honeysql#11]
I don't know what's your stance on adding non-standard SQL support, but I would suggest adding PG's ILIKE operator. If not, I know I can always define it myself using `defmethod`.

**Comment by ddellacosta** [comment]
Since this is PG-specific and we're trying to stick to ANSI SQL stuff for now, and can be easily added using a custom formatter, I'm going to close this.

For the record, we've added this to our own system like so:

```clojure
(defmethod fmt/fn-handler "ilike" [_ col qstr]
  (str (fmt/to-sql col) " ilike " (fmt/to-sql qstr)))
 
(defmethod fmt/fn-handler "not-ilike" [_ col qstr]
  (str (fmt/to-sql col) " not ilike " (fmt/to-sql qstr)))
```
