### ISSUE TITLE
issue with custom fn-handler

### ISSUE THREAD

**Issue by scottbessler** [jkk/honeysql#119]
using 
```clojure
[honeysql "0.6.3"]
```

I have built a custom fn-handler (mine is slightly different, but can repro with this): 
```clojure
(defmethod fmt/fn-handler "true" [_]
  (str (fmt/to-sql true)))

(defmethod fmt/fn-handler "fun-call"
  [_ name filter] 
 (str name " FILTER " (fmt/to-sql {:where filter}))
  )
```

But I am seeing odd behavior where my fn-handler appears to not get used when the function is part of an arithmetic operation, but works fine when part of a boolean operation. Am I missing something?

```clojure
;good
=> (honeysql/format {:where [:and 1 [:fun-call "count(*)" [:true]]]})
["WHERE (1 AND count(*) FILTER (WHERE TRUE))"]
=> (honeysql/format {:where [:or 1 [:fun-call "count(*)" [:true]]]})
["WHERE (1 OR count(*) FILTER (WHERE TRUE))"]

;bad
=> (honeysql/format {:where [:+ 1 [:fun-call "count(*)" [:true]]]})
["WHERE (1 + (fun_call, ?, (true)))" "count(*)"]
=> (honeysql/format {:where [:- 1 [:fun-call "count(*)" [:true]]]})
["WHERE (1 - (fun_call, ?, (true)))" "count(*)"]
=> (honeysql/format {:where [:> 1 [:fun-call "count(*)" [:true]]]})
["WHERE 1 > (fun_call, ?, (true))" "count(*)"]
```

**Comment by krish8664** [comment]
You should be using the `honesql/call` method here, 

```clj
(honeysql/format {:where [:+ 1 (honeysql/call :fun-call "count(*)" [:true])]})
["WHERE (1 + count(*) FILTER (WHERE TRUE))"]

(honeysql/format {:where [:- 1 (honeysql/call :fun-call "count(*)" [:true])]})
["WHERE (1 - count(*) FILTER (WHERE TRUE))"]
```

This one works.

**Comment by scottbessler** [comment]
Cool, that fixed it. Why does it sometimes work without the `honeysql/call` ?

**Comment by krish8664** [comment]
@scottbessler That is how `where` is implemented. In case of `or`,`and` & `xor` - it considers each of the argument to the operator as a predicate and formats these predicate, where as in the case of `+`, `-`, etc - it evaluates based on how the `fn-handler` has been defined for that operator. 

Hope the explanation is clear, also check 
- [`format-clause*`](https://github.com/jkk/honeysql/blob/master/src/honeysql/format.clj#L356-L372)
- [`fn-handler`](https://github.com/jkk/honeysql/blob/master/src/honeysql/format.clj#L102-L106)
