### ISSUE TITLE
arglists metadata for helper functions is wrong

### ISSUE THREAD

**Issue by camsaul** [jkk/honeysql#123]
This is not super-important but the `:arglists` for functions like `merge-left-join` are wrong, which causes linters like [Eastwood](https://github.com/jonase/eastwood) to fail because it assumes you're calling these functions with the wrong number of arguments.

The arglists make it seem like the functions can only be called with 2 args:

``` clojure
(:arglists (meta #'honeysql.helpers/merge-left-join)) -> ([h clauses])
```

But in reality they can handle a variable number of args:

``` clojure
(h/merge-left-join :table [:= :a :b]) -> {:left-join (:table [:= :a :b])}
(h/merge-left-join {} :table [:= :a :b] [:= :c :d]) -> {:left-join (:table [:= :a :b] [:= :c :d])}
```

Not 100% sure what the right `:arglists` should be in this case but in the meantime I've had to manually alter the metadata to get my linter to stop complaining:

``` clojure
(alter-meta! #'honeysql.helpers/merge-left-join assoc :arglists '([m & clauses]))
```

**Comment by MichaelBlume** [comment]
Dang, that's no good, thanks for the report.

**Comment by MichaelBlume** [comment]
@camsaul I've got a pull up, can you tell me if this works better for you?

**Comment by psalaberria002** [comment]
I still get the same error in Eastwood.

{:linter :wrong-arity,
 :msg
 "Function on var #'honeysql.helpers/join called with 3 args, but it is only known to take one of the following args: [clauses]  [m clauses]"}

This is how I am calling h/join:
(h/join :b [:= :a.b_id :b.id])

(:arglists (meta #'honeysql.helpers/join)) -> ([clauses] [m clauses])

**Comment by MichaelBlume** [comment]
I'm a little confused, it looks like you're calling join with two arguments, but eastwood thinks you're calling it with three -- the metadata actually does match the way you're calling it

**Comment by psalaberria002** [comment]
Sorry for the poor example. I was missing the detail about having the join inside a thread first.

(-> (h/select :*)
      (h/from :x)
      (h/join :y [:= :y.b :x.a]))

**Comment by MichaelBlume** [comment]
aha

**Comment by MichaelBlume** [comment]
I think that should fix it? I have

```(:arglists (meta #'honeysql.helpers/join)) -> ([& clauses] [m & clauses])```

**Comment by MichaelBlume** [comment]
I suspect that running Eastwood over our test cases would have caught this, but the latest release of Eastwood still seems to ignore .cljc files, so it looks like we're not going to get any help there =(

**Comment by MichaelBlume** [comment]
It does look like Eastwood's making progress on this issue: https://github.com/jonase/eastwood/issues/179

**Comment by MichaelBlume** [comment]
I've now added an eastwood run to our travis build. Have checked, and it would have caught this.
