### ISSUE TITLE
implementing truncate http://dev.mysql.com/doc/refman/5.7/en/truncate-table.html

### ISSUE THREAD

**Issue by ebahsini** [jkk/honeysql#128]
Hey,

Just leaving myself @ebahsini a note to give this a shot when I have time:
http://dev.mysql.com/doc/refman/5.7/en/truncate-table.html

@jkk unless you see an obvious reason why that's a bad idea! 👍

**Comment by jrdoane** [comment]
I wouldn't mind seeing this either. PostgreSQL is exactly the same. More functionality but, the lowest common denominator is merely ```TRUNCATE [TABLE] table_name```. It also appears that Oracle and MSSQL also support this same common denominator. I think that the widespread support is all the reason that should be needed to add it. :+1:

https://www.postgresql.org/docs/9.3/static/sql-truncate.html
https://msdn.microsoft.com/en-us/library/ms177570.aspx
http://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_10007.htm

**Comment by ddellacosta** [comment]
The goal here is to standardize as much as possible on the ANSI standard, OR make sure you can add these kinds of things yourself without a ton of trouble.  In general HoneySQL makes it easy to add helpers so I don't think there's a super pressing need for this kind of stuff, but considering that this seems to be part of the (SQL:2008 standard)[https://en.wikipedia.org/wiki/Truncate_%28SQL%29] think it's reasonable to include it.

**Comment by seancorfield** [comment]
If there's truly common DDL, especially if it's within the ANSI SQL standard, then I think it's reasonable for HoneySQL to support it (but most DDL is vendor-specific and out of scope for HoneySQL).
