### ISSUE TITLE
Using fields with forward slashes chops off namespace.

### ISSUE THREAD

**Issue by jrdoane** [jkk/honeysql#131]
Since we're living in the Clojure world, it might not be unrealistic that we would want fields in the database to look and feel like idiomatic names we might see in Clojure.

Lets say I had a database where I had a table called `system.tables` that contains keys that look like `schema/oid`, `table/oid`,  `tablespace/oid`, `user/oid`, `user/name`, `schema/name`, `table/name` and, `tablespace/name`.

This all works fine for a query like this:

``` clojure
{:select [:*] :from [:system.tables]}
```

...but fails when doing something like this:

``` clojure
{:select [:table/oid :schema/oid :user/oid] :from [:system.tables] :where [:= :tablespace/name "foo"]}
```

In every case, the namespace on the keyword is discarded and strictly the name portion of the keyword remains. So in the example above with ansi quoting and allow-dashed-names? enabled, I would see something like this:

``` clojure
["SELECT \"oid\", \"oid\", \"oid\" FROM \"system\".\"tables\" WHERE \"name\" = ?" "foo"]
```

Is there any particular reason why this is the case and would an update to HoneySQL to fix this be welcomed? It's an edge case until you decide to do it, then it will probably show up everywhere.

**Comment by seancorfield** [comment]
PR #132 was merged so closing this.
