### ISSUE TITLE
[feature request] set clause doesn't handle expressions as values

### ISSUE THREAD

**Issue by emidln** [jkk/honeysql#134]
`{:set {:total [:+ :total 1]}}` turns into `["SET count = + count"]` instead of `["SET count = (count + ?)" 1]`. As quick test, replacing the `to-sql` call on the value inside the `for` for the `:set` `format-clause` with the same `format-predicate*` that `:update` uses produces correct code on the sample, but probably has other unintended side effects.

A couple test cases:

``` clj
(deftest sset-test
  (is (= (format {:set {:total 100}})
         ["SET total = ?" 100]))
  (is (= (format {:set {:total [:+ :total 1]}})
         ["SET total = (total + ?)" 1])))
```

It seems that currently we need to do this to handle an expression:

``` clj
(deftest sset-expression
  (is (= (format {:set {:total #sql/call [:+ :total 1]}})
            ["SET total = (total + ?)" 1])))
```

**Comment by emidln** [comment]
In light of #135 being fixed, I retested this and found it is still an issue.

**Comment by seancorfield** [comment]
The readme contains an example of `sset` that uses `sql/call` to indicate the appropriate evaluation of the RHS. My feeling is that's the correct way to handle this so I'd like to close this out -- unless you want to provide a PR to make the expression handling implicit here?

**Comment by antonmos** [comment]
not likely that ill have the time to make PR any time soon. Thanks for addressing this!

**Comment by seancorfield** [comment]
Closing due to lack of feedback. The readme contains an appropriate example.
