### ISSUE TITLE
Unable to use SQL Arithmetic Operators in select component

### ISSUE THREAD

**Issue by TangJiong** [jkk/honeysql#136]
`(h/select :DataTime [(sql/call :round (/ (sql/call :sum :Hotavg) 1000)  0) :Hotavg])`
I have such a code segment to divide the result by 1000 and get the int part, but it doesn't work. I get error `honeysql.types.SqlCall cannot be cast to java.lang.Number`. Is there any way to  use SQL Arithmetic Operators in select component

**Comment by 7even** [comment]
@TangJiong seems like this is what you need:

``` clojure
(select :DataTime
        [(sql/call :round
                   (sql/call :/ (sql/call :sum :Hotavg) 1000)
                   0)
         :Hotavg])
```

**Comment by seancorfield** [comment]
@TangJiong Seems like this can be closed out since you have working code, yes?
