### ISSUE TITLE
Unable to order by in UNION query

### ISSUE THREAD

**Issue by madvas** [jkk/honeysql#138]
Let's say we have honeysql query like this

``` clojure
(honeysql.format/format
    {:union-all [{:select [:amount :id :created_on]
                  :from [:transactions]}
                 {:select [:amount :id :created_on]
                  :from [:other_transactions]
                  :order-by [[:created_on :desc]]}]})
```

It compiles into 

``` clojure
["(SELECT amount, id, created_on FROM transactions) 
UNION ALL 
(SELECT amount, id, created_on FROM other_transactions ORDER BY created_on DESC)"]
```

But actually in order to ORDER BY working correctly by combining both queries it has to be out of parenthesis. Like: 

``` clojure
["(SELECT amount, id, created_on FROM transactions) 
UNION ALL 
(SELECT amount, id, created_on FROM other_transactions) 
ORDER BY created_on DESC"]
```

How to achieve this in honeysql?

**Comment by seancorfield** [comment]
You'd need:
```clj
{:union-all [{:select ...}
             {:select ...}]
 :order-by [...]}
```
(because you want the `ORDER BY` on the whole query, not just the second subquery).

However, there seems to be a bug with `UNION` and `ORDER BY` that I just ran into where this generates the `ORDER BY` (and any `LIMIT` etc) at the start of the formatted query, rather than at the end.

**Comment by seancorfield** [comment]
PR #140 submitted to address the bug I highlighted above.

**Comment by rnewman** [comment]
See also #142, which removes the non-standard parentheses from `UNION` and `INTERSECT`, which I suspect will also fix this problem!

For the benefit of folks ending up here through searches — the correct standard way of doing `ORDER BY` in the various parts of a `UNION` is through subqueries:

```
SELECT amount, id, created_on FROM transactions
UNION ALL
SELECT amount, id, created_on FROM
  (SELECT amount, id, created_on FROM other_transactions ORDER BY amount DESC LIMIT 5)
ORDER BY amount ASC
```

which in honeysql is:

```
             {:union
              [{:select [:amount :id :created_on]
                :from [:transactions]}
               {:select [:amount :id :created_on]
                :from [{:select [:amount :id :created_on]
                        :from [:other_transactions]
                        :order-by [[:amount :desc]]
                        :limit 5}]}]
              :order-by [[:amount :asc]]}
```

There's a test for that in #142.

**Comment by seancorfield** [comment]
Given that #140 and #142 are both merged, it would seem this issue has been addressed and this issue should be closed? @madvas ?

**Comment by seancorfield** [comment]
Closing for lack of response.
