### ISSUE TITLE
Nicer function calling syntax

### ISSUE THREAD

**Issue by dubiousdavid** [jkk/honeysql#14]
It would be really cool to use the following convention for function calls:

``` Clojure
(-> (select '(now)
            '(count *)
            '(date_format dob "%m/%d/%Y"))
    (from :users))
```

**Comment by ddellacosta** [comment]
Think this with #17 needs some more serious discussion...

**Comment by piranha** [comment]
That would be certainly nicer than current `:%now`. But, to be honest, I use `(sql/call :now)` everywhere right now and it's mostly ok... It would be easier to read `'(now)`, but I'm not sure how recognizable will it be from the parser's standpoint.

**Comment by seancorfield** [comment]
Given that #17 is closed out and there's been no additional discussion here for over three years, I'm going to close this out, asserting that `sql/call` is sufficiently convenient.
