### ISSUE TITLE
Support for Query Optimizer Hints

### ISSUE THREAD

**Issue by johnmcconnell** [jkk/honeysql#145]
This might be solvable with an extension.

A SQL query hint (for oracle looks something like).

```sql
SELECT
  /*+ USE_INDEX(TABLE_A MY_CUSTOM_INDEX) */
  *
FROM
  TABLE_A
```

**Comment by MichaelBlume** [comment]
I don't have the bandwidth to work on this, but will be happy to review a pull request (with tests)

**Comment by johnmcconnell** [comment]
I understand. I'll see if I have bandwidth also!

**Comment by seancorfield** [comment]
@johnmcconnell Any further thoughts on this?

**Comment by seancorfield** [comment]
Closing for lack of response.
