### ISSUE TITLE
Could not locate honeysql/core__init.class or honeysql/core.clj on classpath

### ISSUE THREAD

**Issue by acthp** [jkk/honeysql#147]
Getting this error when trying to build, with 0.8, lein and clojure 1.6. Using 0.7 works.

**Comment by MichaelBlume** [comment]
Yep, honeysql was made usable from both Clojure and Clojurescript, with the
loss of Clojure 1.6 support. you should either downgrade to honeysql 0.7 or
upgrade to Clojure 1.7/1.8

**Comment by seancorfield** [comment]
Given the workaround options given -- and the general "state of the union" as far as Clojure version usage and support goes -- I'm going to close this out.
