### ISSUE TITLE
Readme missing actual connection to RDBMS

### ISSUE THREAD

**Issue by WorldsEndless** [jkk/honeysql#148]
Obviously a newbie problem here, but while the Readme discusses production of SQL statements, it doesn't have anything about actually using Honey with a running MySQL, PostGres, or other DB.

**Comment by matanster** [comment]
@WorldsEndless I think you are generally right. 

The simple solution is to understand, or for the readme to say in case it does not, that the result of `sql/format` is just the query to supply on your jdbc api. Honey is really only the parallel of a query builder, but I agree the readme could avoid this being somewhat ambiguous.

**Comment by matanster** [comment]
As an example, if you use clojure's hikari-cp wrapper, which entails these dependencies
```
 ;; sql wrangling stack
                 [honeysql "0.8.2"]         ; sort of a query builder
                 [mysql/mysql-connector-java "5.1.41"]  ; mysql jdbc driver
                 [org.clojure/java.jdbc "0.7.0-alpha3"] ; clojure jdbc, needed for the rest of them libraries
                 [hikari-cp "1.7.5"]]       ; jdbc connection pooling, if we really need it (https://github.com/tomekw/hikari-cp)
```
then to execute against a database, you e.g. supply a single-element vector `sql-statement` built by honeysql, like so
```clojure
(jdbc/with-db-connection [conn {:datasource datasource}]
          (jdbc/execute! conn sql-statement))))
```
after having initialized a hickari `datasource`.
