### ISSUE TITLE
No clause exists for MS SQL Server SELECT TOP <n> FROM... for limiting

### ISSUE THREAD

**Issue by fdhenard** [jkk/honeysql#15]
I would like to add this clause, and thought that I should start with an issue.    Some background to this can be found here: https://github.com/jkk/honeysql/issues/6#issuecomment-23174297

This will be my first pull request on github.  If I take too long on this, feel free to step on my toes.

**Comment by ddellacosta** [comment]
Looks like this one has been resolved with (Menthalion's workaround)[https://github.com/jkk/honeysql/issues/15#issuecomment-52159339]--closing.
