### ISSUE TITLE
update already refers to: #'clojure.core/update

### ISSUE THREAD

**Issue by matanster** [jkk/honeysql#157]
Is it possible that following the readme's suggestion 
```clojure
(:require [honeysql.helpers :refer :all])
```
might actually override clojure.core's `update`?

> WARNING: update already refers to: #'clojure.core/update in namespace: <my namespace> being replaced by: #'honeysql.helpers/update

I use:
```clojure
  (:require [honeysql.core :as sql])
  (:require [honeysql.helpers :refer :all]))
```

Inside my namespace definition.
I see this has already been addressed by #41, so I wonder what I might be missing.

**Comment by MichaelBlume** [comment]
Yeah, you'll want to add ```(:refer-clojure :exclude [update])``` to your own ns declaration in order to prevent this. By default any Clojure namespace has a bunch of Clojure core functions imported into it, and update is one of them.
