### ISSUE TITLE
Extending honeysql with json operators

### ISSUE THREAD

**Issue by DanBurton** [jkk/honeysql#159]
My team is developing an app that constructs queries somewhat dynamically. Honeysql seems like a great fit, but doesn't have out-of-the-box support for json operators.

https://www.postgresql.org/docs/9.6/static/functions-json.html

If we work on this, would you be interested in having us submit a PR to honeysql? Or do you think this might be better suited for honeysql-postgres? (cc @nilenso)

**Comment by AlJohri** [comment]
This would be really helpful. I'm relying on the `->` operator quite a bit.

**Comment by AlJohri** [comment]
I'm currently using `sql/raw` to achieve this.

```clojure
(require '[honeysql.core :as sql])
(require '[honeysql.helpers :refer [select where join from limit offset]])

(defn select-json-key [parent k]
  (-> k
      (clojure.core/name)
      (#(vector (sql/raw (str (clojure.core/name parent) "->'" % "'")) %))))

(defn select-json-keys [parent keyz]
  (->> keyz
       (map (partial select-json-key parent))))

(defn get-articles-querymap [lim off fields]
  (-> (apply select (select-json-keys :a.original fields))
      (from [:articles :a])
      (limit lim)
      (offset off)))

(def fields [:_id :date])
(println (get-articles-query 1 0 fields))
```

This resulting sql would be:
```sql
SELECT original->'_id', original->'date' FROM articles a LIMIT 1 OFFSET 0
```

Would love to see native support.

**Comment by emidln** [comment]
This seems like something better suited to honeysql-postgres. In my codebase, we have several `(defmethod honeysql.format/fn-handler ....)` implementations for things like json-eq and json-exists. We tend to use them like so:

`(sql/where [:json-eq :some-json-field :my-key some-value])`

**Comment by seancorfield** [comment]
Agreed. This is vendor-specific and shouldn't be in the core HoneySQL library. I'm tagging it `vendor-specific` and would encourage folks to open feature request issues on `honeysql-postgres` instead (as I'm planning to close out all the vendor-specific stuff here soon).

**Comment by seancorfield** [comment]
Given HoneySQL's position of trying to be vendor-neutral and the presence of reasonable approaches to make this work (without changing HoneySQL), I'm closing this out.
