### ISSUE TITLE
Unable to do multiple inner joins

### ISSUE THREAD

**Issue by fdhenard** [jkk/honeysql#160]
or I'm just not figuring it out.  Here's what I tried

```
{:select [[:qo.text "qo_text"]
              [:q.text "q_text"]
              [:qs.text "qs_text"]]
 :from [[:question-option :qo]]
 :join [[[:question :q] [:= :qo.question-id :q.id]]
          [[:question-section :qs] [:= :q.section-id :qs.id]]]}
```
Here's the output:
`["SELECT qo.text AS qo_text, q.text AS q_text, qs.text AS qs_text FROM question_option qo INNER JOIN question q ON qo.question_id = q.id"]`

Notice it's only catching the first join.

**Comment by AdamNiederer** [comment]
I think you have too many braces. Try this:

```clojure
=> (honeysql.format/format {:select [[:qo.text "qo_text"]
                                    [:q.text "q_text"]
                                    [:qs.text "qs_text"]]
                           :from [[:question-option :qo]]
                           :join [[:question :q] [:= :qo.question-id :q.id]
                                  [:question-section :qs] [:= :q.section-id :qs.id]]})

["SELECT qo.text AS qo_text, q.text AS q_text, qs.text AS qs_text FROM question_option qo INNER JOIN question q ON qo.question_id = q.id INNER JOIN question_section qs ON q.section_id = qs.id"]
```

**Comment by fdhenard** [comment]
Thanks @AdamNiederer, I will try that when I get a chance.

**Comment by seancorfield** [comment]
@fdhenard I'm closing this out on the assumption that the suggested code works. Let us know if you believe you still have an issue with HoneySQL and multiple inner joins.

**Comment by fdhenard** [comment]
Sorry about that.  I wanted to check it out, but never got to it.  I'm very happy with honeysql.  Thanks for your contribution!
