### ISSUE TITLE
0.9.0 fails to format some queries which worked on 0.8.2

### ISSUE THREAD

**Issue by jetmind** [jkk/honeysql#168]
Changes in `0.9.0` regarding sequences acting as function invocation in value position are breaking some queries which worked in `0.8.2`.

For example, you can write a query with tuples like this:

```
(sql/format {:select [:id]
                     :from   [:table]
                     :where  [:= [:a :b] [1 2]]})

;;  => [SELECT id FROM table WHERE (a, b) = (?, ?) 1 2]
```

This works on `0.8.2` but fails on `0.9.0` with `java.lang.ClassCastException` (trying to evaluate `(name 1)`.

It would be great if backward compatibility was preserved.

**Comment by MichaelBlume** [comment]
Looks like this was introduced in #149 -- @joodie could you help take a look at this?

**Comment by MichaelBlume** [comment]
Ok, it looks a little like we're really overloading what vectors are doing within a query. I'm not really sure there's a way to fully accomodate both desired uses, and I'm worried that if we try we'll wind up with people spending too much time trying to guess what the system's going to do. Can we rethink this?

**Comment by jetmind** [comment]
I'd say it should be at least reported as a breaking change in the changelog for now.

**Comment by MichaelBlume** [comment]
I'm inclined to just revert #149 but I'll update the changelog first.

**Comment by joodie** [comment]
Sorry for taking so long to respond - I was on holiday. @MichaelBlume I definitely agree that we're doing too much with plain vectors. I had a hard time coming up with a change in #149 that did not *appear* to break anything.

There should be a better (and probably more explicit) way of handling what vectors currently do, which would probably be a big breaking change. I'm not sure what it should look like though... There's a reason clojure's vectors and lists are different (and I'm pretty sure using `[:foo :foo-alias]` as a shorthand was a bad idea - seems to be `[:as :foo :foo-alias]` is more readable and only slightly longer).

I'm not too attached to #149 so if you want to revert it that's ok by me.

**Comment by MichaelBlume** [comment]
This should've been fixed by #169 -- in fact I stole your test case

**Comment by jetmind** [comment]
Any estimate on when it will be released?

**Comment by MichaelBlume** [comment]
Probably today, will be 0.10.0

**Comment by jetmind** [comment]
Is there anything I can do to speed this up? :)

**Comment by MichaelBlume** [comment]
Hey, I'm really sorry for my silence on this issue. There was a discussion [on Slack](https://clojurians.slack.com/messages/C66EM8D5H)/[on the mailing list](https://groups.google.com/forum/#!forum/honeysql) and the upshot was that given the way the features are used/level of vendor support/etc. it may make sense to declare #149 to be a breaking change that we're keeping. If you think that's the wrong call I'd definitely like to hear you weigh in. In any case, if we might keep #149 going forward, I definitely don't want to push a release which reverts it, only to reinstate it. That'd just be really confusing.

**Comment by jetmind** [comment]
After reading all the arguments I think keeping #149 is the way to go even though it means some additional work for me rewriting some queries. In my experience tuples use are much rarer than function application, so having consistent function application behavior makes more sense for the library.

**Comment by MichaelBlume** [comment]
Cool, sorry for the flip-flopping
