### ISSUE TITLE
README examples should run as tests

### ISSUE THREAD

**Issue by MichaelBlume** [jkk/honeysql#173]
there's lots of code in the README and we don't actually know if it all produces the same results quoted there. It'd be nice to get it hooked into our testing process so if any of our README examples change, we know that.

**Comment by MichaelBlume** [comment]
Like, I think we could literally, at runtime, extract the backtick-quoted segments from the README and eval them.

**Comment by seancorfield** [comment]
midje-readme -- that's what we use on clj-time.

**Comment by MichaelBlume** [comment]
@seancorfield Yep! I took your suggestion from Slack and ran with it =) https://github.com/jkk/honeysql/pull/175/files

**Comment by seancorfield** [comment]
Very nice!
