### ISSUE TITLE
When using against PostgreSQL what is the best way to insert/update JSON columns?

### ISSUE THREAD

**Issue by erez-rabih** [jkk/honeysql#176]

**Comment by emidln** [comment]
I do this:

```clojure

    (require '[clojure.java.jdbc :as jdbc]
                '[cheshire.core :as json])
       (import 'org.postgresql.util.PGobject)

       ;; setup JSON fields to automatically serialize-deserialize
       (defn value-to-json-pgobject [value]
         (doto (PGobject.)
           ;; hack for now -- eventually we should properly determine the actual type
           (.setType "jsonb")
           (.setValue (json/generate-string value))))

       (extend-protocol jdbc/ISQLValue
         clojure.lang.IPersistentMap
         (sql-value [value] (value-to-json-pgobject value)))
       (extend-protocol jdbc/IResultSetReadColumn
         org.postgresql.util.PGobject
         (result-set-read-column [pgobj metadata idx]
           (let [type (.getType pgobj)
                 value (.getValue pgobj)]
             (if (#{"jsonb" "json"} type)
               (json/parse-string value true)
               value))))
```

This makes is so that when you send a map to the clojure.java.jdbc layer it is presented as a jsonb value to Postgres. Also, when you read a json/jsonb you get back the equivalent clojure map/array. 

Armed with this you can insert some JSON into the database:

`(clojure.java.jdbc/execute! my-db ["insert into foo (json-col) values (?)" {:this :is :a "json" "object" 0}])`

Now from HoneySQL, you can use `honeysql.format/value` around your json value during insert/updates to make sure HoneySQL passes your json directly through to the JDBC layer. 

```
(require '[honeysql.core])
(require '[honeysql.helpers :refer :all])
(require '[honeysql.format :refer [value])

(def q (-> (insert-into :foo) (values [{:json-col (value {:this :is :a "json" "object" 0})}])))

(->>  (honeysql.core/format q)
     (clojure.java.jdbc/execute! my-db)))

**Comment by erez-rabih** [comment]
Thanks for the tips @emidln I appreciate it
I really think that this know-how should be a part of the library documentation taking into account that working with JSON object and PSQL is a pretty common use case.

**Comment by danielbraun** [comment]
Also take a look at https://github.com/nilenso/honeysql-postgres
It extends jdbc protocols for a variety of Clojure types.
Still have to use honeysql.format/value though.

**Comment by MageMasher** [comment]
@danielbraun Where in that project does it extend protocols for clojure types? There are three source files and none of them include jdbc protocols.

**Comment by danielbraun** [comment]
Sorry, I probably meant https://github.com/remodoy/clj-postgresql

**Comment by seancorfield** [comment]
HoneySQL tries hard to avoid vendor-specific features so this feels like it belongs in a PostgreSQL-specific library instead.

I'm going to tag this `vendor-specific` for now but I'll probably close out all the vendor-specific issues in a while.

**Comment by zelark** [comment]
For those who want only `json` and `jsonb` types to support, I wrote this tiny [snippet](https://gist.github.com/zelark/3b484e9b16ad55c97b4ed6f6ea13986b).

**Comment by seancorfield** [comment]
Given HoneySQL's position of trying to be vendor-neutral and the presence of reasonable approaches to make this work (without changing HoneySQL), I'm closing this out.
