### ISSUE TITLE
Documentation issue with execute!

### ISSUE THREAD

**Issue by AndreaCrotti** [jkk/honeysql#178]
I believe this example in the README:

`(jdbc/execute! conn (sql/format sqlmap))`

is not actually correct, because execute! does not support selects apparently.
From the docs
`Given a database connection and a vector containing SQL (or PreparedStatement)
  followed by optional parameters, perform a general (non-select) SQL operation.`
And it gives an error anyway.

I believe `jdbc/query` would be the right call to do?
Thanks!

**Comment by MichaelBlume** [comment]
Ha, the one statement in the README that isn't under test
