### ISSUE TITLE
Subquery Aliasing

### ISSUE THREAD

**Issue by zerg000000** [jkk/honeysql#184]
The subquery table alias is wrongly identified as function. Could it be fixed?

```clojure
(sql/format {:select [:a.*] 
             :from [[:ddd :a]]
             :where [:= :dd {:select [:b.id]
                             :from [[:eee :b]]
                             :where [:= :b.id :a.id]}]})
=> ["SELECT a.* FROM ddd a WHERE dd = (SELECT b.id FROM eee(b) WHERE b.id = a.id)"]
```

**Comment by iku000888** [comment]
The problem seems with `honeysql.format/seq->sql`

Changing it to the following fixes the problem, but it obviously deletes the mentioned workaround for oracle.

```
(defn seq->sql [x]
  (cond
    *value-context?*
    ;; sequences are operators/functions
    (format-predicate* x)
    *fn-context?*
    ;; list argument in fn call
    (paren-wrap (comma-join (map to-sql x)))
    :else
    ;; alias
    (str (to-sql (first x))
         " AS "
         (if (string? (second x))
           (quote-identifier (second x))
           (to-sql (second x))))))
```

**Comment by seancorfield** [comment]
@iku000888 Aside from removing the Oracle-specific condition, I don't see what's different between the current code and what you posted -- so I can't see what *change* you're proposing or how it would fix this problem?

**Comment by seancorfield** [comment]
I don't see how that change would affect `eee(b)` in the original problem statement.

That condition just causes the output to either be `eee AS b` or `eee b` so it's pretty clear that's **not** the path being executed to produce `eee(b)`.

Did you actually *try* the original code on a modified version of HoneySQL with just your proposed change?

**Comment by iku000888** [comment]
Yes I did test it out.
Let me prepare something minimal...

**Comment by seancorfield** [comment]
Your insistence caused me to test @zerg000000 's original code in a REPL using the *current* version of HoneySQL _with no code changes_:
```
(! 926)-> clj
Clojure 1.9.0
user=> (require '[honeysql.core :as sql])
nil
user=> (sql/format {:select [:a.*] 
             :from [[:ddd :a]]
             :where [:= :dd {:select [:b.id]
                             :from [[:eee :b]]
                             :where [:= :b.id :a.id]}]})
["SELECT a.* FROM ddd a WHERE dd = (SELECT b.id FROM eee b WHERE b.id = a.id)"]
```
In other words, it **already does the right thing** so the original bug -- producing `eee(b)` -- has been fixed at some point along the way.

So I'm closing this out.

**Comment by iku000888** [comment]
Thanks for checking and I appreciate your time.

So my specific issue:

```clj
(-> (select :a)
    (from [(-> (select :*)
               (from :b)) :subq])
    (sql/format))
```

Renders 

`["SELECT a FROM (SELECT * FROM b) subq"]`

And this is problematic in mysql as it gives me a table alias required error.
With the mentioned fix it renders

`["SELECT a FROM (SELECT * FROM b) AS subq"]`

And runs as expected.

Would you call this a separate issue?

**Comment by seancorfield** [comment]
Feel free to create a separate issue for that. Not sure how to solve it without breaking other databases but I'll give it some thought.
