### ISSUE TITLE
Interest in deploying on npm?

### ISSUE THREAD

**Issue by arichiardi** [jkk/honeysql#191]
With the latest `lumo` a package could be now deployed and consumed from npm if self-host compatible.

There is only one change involved: add a package json with the right stuff in it.
Recently I have pushed the same thought to Macrovich and @cgrand kindly [agreed](https://www.npmjs.com/package/macrovich). So basically `honeysql`'s only dependency is already good to go.

I can put a PR together quickly if you are interested in this. It duplicates work a bit, but it is nothing that a simple script cannot handle for you.

Thanks a lot for merging the PRs @MichaelBlume!

**Comment by MichaelBlume** [comment]
Yeah, I think it'd be good to get one of these in, thanks =)

**Comment by seancorfield** [comment]
I have no experience with Node (and only very little with CLJS) so a PR for this would be great @arichiardi !

**Comment by arichiardi** [comment]
Forgot to close this - done already :smile: https://github.com/jkk/honeysql/pull/208
