### ISSUE TITLE
SQL validation?

### ISSUE THREAD

**Issue by AndreaCrotti** [jkk/honeysql#192]
It's possible even using the helper functions to actually generate invalid SQL with Honeysql.
I know it's not really possible to prevent that, but it would be great to be able to validate the generated SQL before actually having it fail in Postgres (or other dbs).

I think that's in theory possible if a definition of the Postgres grammar (for example) is available, anyone ever thought/tried that?
Thanks

**Comment by MichaelBlume** [comment]
I think that'd be pretty cool. My inclination is to say that it's outside of honeysql's scope -- if someone wrote a library to do this, lots of people would find it useful, not just honeysql users.

**Comment by seancorfield** [comment]
Agreed that a SQL validator is out of scope -- especially since each DB has its own syntax above and beyond ANSI SQL. Closing this out due to scope. If you want a PostgreSQL-specific checker, maybe propose that to the `honeysql-postgres` project?
