### ISSUE TITLE
Retrieve create id after insert with mysql

### ISSUE THREAD

**Issue by pablobcb** [jkk/honeysql#194]
is it possible? in the same way `jdbc/insert!` does?

**Comment by MichaelBlume** [comment]
Sorry, I'm not sure what this is asking.

Honeysql really isn't responsible for *doing* things to databases; it generates SQL. Once you have a SQL string in hand, honeysql's job is pretty much done.

**Comment by seancorfield** [comment]
Closing for lack of response.
