### ISSUE TITLE
SET ends up before JOIN in formatted SQL

### ISSUE THREAD

**Issue by ljosa** [jkk/honeysql#200]
The `SET` clause [has priority 100](https://github.com/jkk/honeysql/blob/master/src/honeysql/format.cljc#L197), which is lower than the priority of the `JOIN` clauses. Hence, `SET` ends up up before `JOIN` in the formatted SQL statement, and MySQL does not accept that:

```clojure
> (-> (sqlhelper/update :foo)
      (sqlhelper/join :bar [:= :bar.id :foo.bar_id])
      (sqlhelper/sset {:a 1})
      (sqlhelper/where [:= :bar.b 42]))
{:update :foo, :join (:bar [:= :bar.id :foo.bar_id]), :set {:a 1}, :where [:= :bar.b 42]}
> (sql/format *1 :quoting :mysql)
["UPDATE `foo` SET `a` = 1 INNER JOIN `bar` ON `bar`.`id` = `foo`.`bar_id` WHERE `bar`.`b` = 42"]
> (jdbc/execute! mysql-db *1)
MySQLSyntaxErrorException You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INNER JOIN `bar` ON `bar`.`id` = `foo`.`bar_id` WHERE `bar`.`b` = 42' at line 1  sun.reflect.NativeConstructorAccessorImpl.newInstance0 (NativeConstructorAccessorImpl.java:-2)
```

I found that I can change the priority with `honeysql.format/register-clause!`:

```clojure
> (honeysql.format/register-clause! :set 155)
{:full-join 150, :having 180, :where 160, :limit 200, :group-by 170, :offset 210, :query-values 230, :columns 90, :update 70, :right-join 140, :left-join 130, :with 30, :from 110, :values 220, :insert-into 60, :order-by 190, :with-recursive 40, :set 155, :lock 215, :delete-from 80, :join 120, :select 50}
(sql/format *3 :quoting :mysql)
["UPDATE `foo` INNER JOIN `bar` ON `bar`.`id` = `foo`.`bar_id` SET `a` = 1 WHERE `bar`.`b` = 42"]
mailquail.db> (jdbc/execute! mysql-db *1)
[0]
```

Is there any reason not to make 155 the default priority for `set`?

**Comment by MichaelBlume** [comment]
Yep, this looks reasonable.

**Comment by seancorfield** [comment]
This breaks `update ... set ... from ...` -- see #200 -- but given that `from` must come before `join` and in one case we want `set` before `from` and in the other case we want `set` after `join`, I'm not quite sure how to resolve this. It seems like we need `set` to have different priorities based on usage which isn't something HoneySQL currently supports (right @MichaelBlume ?) or else we need multiple versions of `set` with different priorities which seems... nasty. Thoughts? /cc @armed
