### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by arichiardi** [jkk/honeysql#202]
Hi folks it's me again :smile: 

I have a branch in my fork that sets up things for publishing on `npm`. I have used it with an internal repository to build things with `lumo` and it works pretty well so I was wondering if this project would be interested.
As you can see, the project this project depends on - [macrovich](https://github.com/arichiardi/honeysql/blob/npm/package.json#L16) - it has [already been deployed](https://www.npmjs.com/package/macrovich).

Fun times in the self-host ClojureScript world :smile: :tada: :balloon:

**Comment by arichiardi** [comment]
@MichaelBlume maybe we can release a `0.9.2` so that I can merge my self-host patch commit in `honeysql-postgres`? :wink:

**Comment by MichaelBlume** [comment]
Yep, hoping to get 0.9.2 out soon, just need to write up the changelog.

...If someone wants to write the changelog up for me, that'd honestly speed me up a lot.

**Comment by arichiardi** [comment]
@MichaelBlume I can honestly do that if you promise to push the release button right after :smile:

**Comment by MichaelBlume** [comment]
Done =)

**Comment by arichiardi** [comment]
Lol who did it first :smile: 

Btw for publishing on `npm` you need an account, should be simple. After that:

```
npm login
...
npm publish
```

should bring you there :+1:

**Comment by MichaelBlume** [comment]
I'll release as soon as I get home and have access to my PGP key =)

**Comment by MichaelBlume** [comment]
Oh, by "done" I meant "yes I'll agree to that"

I'll release as soon as I get home and have access to my PGP key =)

**Comment by arichiardi** [comment]
Thank you for releasing! The npm release is not that important but would be cool.

**Comment by MichaelBlume** [comment]
Can you publish to NPM?

**Comment by arichiardi** [comment]
I think I can :)

**Comment by MichaelBlume** [comment]
Cool! I don't think you should need any, like, actual technical permissions, because we've never interacted with the NPM infrastructure before. If you feel you ethically need permission from a honeysql dev: go for it =)

Thanks!

**Comment by arichiardi** [comment]
@MichaelBlume So I saw the repo's commits and I think that:

```
0eff12e Cut 0.9.2 release
```

Is a good candidate for the release tag? What do you think? Shall I release against that?

**Comment by MichaelBlume** [comment]
Yep, there should already be git tags in the repo =)

**Comment by arichiardi** [comment]
I will do this asap :)

**Comment by arichiardi** [comment]
The package has been published on `npm` and and `honeysql` org has been created:

https://www.npmjs.com/package/@honeysql/honeysql

**Comment by MichaelBlume** [comment]
Awesome, thanks =)
