### ISSUE TITLE
How to use params in honeysql.core/raw

### ISSUE THREAD

**Issue by vincent-dm** [jkk/honeysql#213]
Hi,

In some cases HoneySQL syntax is too cumbersome (or unable) to express a complex part of my query, so I have to use `honeysql.core/raw` to express it. However, I run into a problem when I need to use a parameter in these raw parts, because the string passed to `raw` does not seem to be parsed to extract params (or at least I can't find how to do it).

Can someone confirm whether or not it is possible to refer to a parameter within a raw expression? The docs are not clear about this at all and trying out various combinations (see below) didn't yield anything.

(I'm aware there is also `honeysql.core/inline`, but the docs and source code imply that this is intended to prevent constant values being bound as params. AFAIK it also behaves identical to `honeysql.core/raw`)

To illustrate what I already tried:
_(code is supposed to return the sqlvec`["SELECT 1 + ?" 2]`), but none of these attempts work_
  - `(sql/format {:select [(sql/raw "1 + ?")]} [2])`
  - `(sql/format {:select [(sql/raw "1 + :?")]} [2])`
  - `(sql/format {:select [(sql/raw "1 + ?")]} {:params [2]})`
  - `(sql/format {:select [(sql/raw "1 + :?")]} {:params [2]})`
  - `(sql/format {:select [(sql/raw "1 + :foo")]} {:params {:foo 2}})`
  - `(sql/format {:select [(sql/raw "1 + :?foo")]} {:params {:foo 2}})`

(I'm aware that this trivial example could be better expressed without calling `raw`, but I kept it simple for argument's sake. So please pretend that `1 + x` is some complex SQL syntax that needs to be parameterized.)

Does anyone know more about this?

Thanks!

**Comment by kronos** [comment]
Same problem here. Any suggestions?

**Comment by seancorfield** [comment]
`raw` is for an opaque SQL string -- no parsing, no logic at all, just a string that is rendered as-is into the final SQL.

`inline` is for a value that you want to keep as a literal in the final SQL string, overriding HoneySQL's default behavior (of lifting values out as parameters).

So the answer to your question is, no, you can't parameterize a `raw` string.

I'll tag this with `documentation` as a reminder to improve the README information about both `raw` and `inline`.

**Comment by seancorfield** [comment]
I updated the README to (hopefully) clarify this, as well as adding an example of `inline`.

**Comment by vincent-dm** [comment]
Hi @seancorfield 

Thanks for clarifying this. As far as you know: is it on purpose that there is no mechanism for using parameters in a raw part?

Currently, when I need to parametrize SQL syntax that is unsupported by HoneySQL, I have to choose between (a) dropping HoneySQL and using a plain sqlvec with params or (b) using a raw part and using string interpolation to concat the params in it (only safe if I'm certain about the content of the params).

I don't like both options, and I believe parametrizing raw strings would be a welcome third option. Would you be open to a PR which adds such a feature?

**Comment by seancorfield** [comment]
Well, it's "on purpose" in that it is a mechanism for inserting raw strings into the generated SQL with no processing performed on them. That's by design.

Do you have a specific example where you currently _need_ to use `raw` but still want parameters? (the above examples aren't helpful because they can be done without `raw`)

**Comment by seancorfield** [comment]
I'm looking at #62 which is a bit more compelling in terms of a use case but has the complication of seeming to need parameters inside a SQL string is a sticking point for me right now.

**Comment by kronos** [comment]
@seancorfield 
Simple example:
```SQL
SELECT (orders.car_id = :id:) as selected from ...
```
Now I have to use sql/raw which can lead to security issues:
```clojure
(let [id ...]
  ...
  (apply helpers/select <...> [(sql/raw (str "orders.car_id = " id)) "selected"] <...>)
  ...
```

**Comment by vincent-dm** [comment]
Indeed, expressions in the SELECT part were also a major use case for me.

Another one is having the ability to use vendor-specific syntax, without needing to extend HoneySQL. For example, we often use PostgreSQL range types and need to check whether a value is contained by a range. The PostgreSQL operator for that is `@>`, but unfortunately `:@>` is not a valid keyword in Clojure, so when defining a custom HoneySQL handler, we had to resort to a made-up `CONTAINS` "operator". This is confusing to people reading the query who are familiar with PostgreSQL, but now aware of our custom fn-handlers.

Being able to resort to a parametrized string part would provide an elegant escape hatch for such cases. It could also reduce the pressure to add all kinds of rarely used or vendor-specific syntax to HoneySQL.

**Comment by seancorfield** [comment]
Here's a suggestion -- see whether you think it would solve your issues (if implemented):

Extend `#sql/raw` to accept a vector argument (as well as a plain string) and the vector contains strings and parameters and the rendering will join all the strings together and lift the parameters out. If you need a string parameter, you could use `#sql/param` and provide a name (and the parameter in the `:params` argument to `format`).
```clojure
(sql/format (select #sql/raw ["1 + " 2]))
=> ["SELECT 1 + ?" 2]
(sql/format (select #sql/raw[#sql/param :foo " AS x"]) {:params {:foo "bar"}})
=> ["SELECT ? AS x" "bar"]
```
If that seems at least promising to y'all, I'll open up a new ticket for that work and see what I can do.

**Comment by vincent-dm** [comment]
Hi @seancorfield 

Yes, that would be very useful. Thanks for going the extra mile on this!

**Comment by seancorfield** [comment]
Follow-up to #219
