### ISSUE TITLE
"AS NULL" being added to query when using helpers

### ISSUE THREAD

**Issue by jarcane** [jkk/honeysql#215]
Working on a simple query I ran into an odd issue with the helper functions. 

Given the following query: 
```clj
(-> (select [:*])
    (from :app.messages)
    (where [:= :name "hello"]))
```
I get a surprising resulting string vector after passing that to `sql/format`:
`["SELECT * AS NULL FROM app.messages WHERE name = ?" "hello"]`

This of course fails because (in my case) PostgreSQL doesn't support the "AS NULL" clause it's inserting isn't supported on `SELECT *`. It *does* work if I drop `:*` for specific fields (say `:message`), but I still get the `AS NULL` being inserted so the results are less than useful. 

Given:
```clj
(-> (select [:message])
    (from :app.messages)
    (where [:= :name "hello"]))
```

Instead of getting, say `{:message "Hello, world"}` as I'd expect, I get back `{nil "Hello, world"}` because of the `AS NULL`. 

Using plain maps seems to work as expected with no surprises, save that I did notice an error in the README: the `:from` clause's argument needs to be wrapped in a vector or else I get an IllegalArgumentException because it tries to make an ISeq from a keyword.

**Comment by emidln** [comment]
This is because the select helper expects varargs containing the fields. You're passing a single field with an alias. The alias, being unspecified, is nil which translates to as null. Compare:

```clj
(select :messages) ;; SELECT messages
(select [:messages :foo]) ;; SELECT messages as foo
(select :foo [:bar :baz]) ;; SELECT foo, bar as baz
```

This would make a helpful linter rule, but it's hard to blacklist since `SELECT foo as NULL` might be legal for some databases. Maybe the docs here could be more clear?

**Comment by jarcane** [comment]
Ahh, then it seems I did misunderstand the docs, thanks for the clarification.

**Comment by seancorfield** [comment]
We'll try to improve the docs around this!

**Comment by seancorfield** [comment]
I have added an explicit example of aliasing column and tables names, with an explanation that `select` is variadic and so `(select [:a :b])` means `SELECT a AS b` rather than being a collection of column names.
