### ISSUE TITLE
Enhance sql/raw to accept a vector to allow parameters

### ISSUE THREAD

**Issue by seancorfield** [jkk/honeysql#219]
This supercedes #213 and will allow sql/raw to accept a vector of values: strings will be passed directly into the SQL, non-strings will become parameters. For a string parameter, you'll need to use sql/param and a name, then provide the value via the `:params` map argument to `format`.

**Comment by vincent-dm** [comment]
Maybe it's worth to consider a more convenient way to provide string params before the API of the new feature is settled?

Calling a function or adding a reader macro before inline param would be more convenient than having to name the param and then keeping a map of `:params` in sync.

So something like `(select #sql/raw[#sql/raw-param "foo" " AS x"])`, but I have no idea whether this is possible. Just brainstorming :-)

**Comment by seancorfield** [comment]
Yeah, I must admit I've always found the `#sql/param` construct a bit weird... Open to suggestions. I think `#sql/raw-param` is a bit of a mouthful but I guess it would only be needed for strings inside a raw vector (although you'd have to be careful if you didn't know what types of expression you were dealing with).

I would if `#sql/?` would be more intuitive as a way to mark expressions as parameters inside a raw vector?

**Comment by seancorfield** [comment]
I've implemented the basic concept behind this: `#sql/raw` can accept a vector strings and parameters. Non-string parameters are automatically lifted out as parameters. String parameters need to be explicitly lifted out with `#sql/param` and you can either provide a keyword name -- and then a matching keyword name in the params map to for `format` or position parameters.

At this point, I'm yet to be convinced that we need a new, specific syntax for inline string parameters so I'm going to close this out. I'm willing to be persuaded -- in a new ticket -- that string parameters need a more convenient inline syntax :)

**Comment by vincent-dm** [comment]
Alright. Thanks @seancorfield for the quick development.

Looking forward to when the next release is cut. (That should also finally release my [PR 201](https://github.com/jkk/honeysql/pull/201) which has been merged since April...)

**Comment by seancorfield** [comment]
`[honeysql "0.9.3"]` is available for you to play with @vincent-dm !

**Comment by vincent-dm** [comment]
Awesome. Thanks!!
