### ISSUE TITLE
Question: Do we support sql transactions?

### ISSUE THREAD

**Issue by patrickds** [jkk/honeysql#220]
I could not find anything related in the code. It would be very very useful :)

**Comment by seancorfield** [comment]
Since HoneySQL is just about generating SQL (strings), I'm not sure what "transaction support" would look like -- that's something that JDBC libraries like `org.clojure/java.jdbc` provide.

Can you elaborate?

**Comment by patrickds** [comment]
hummm I was thinking that we could send something like

```
begin
insert into a (id) values ('my-id')
insert into b (id) values ('my-id')
commit
```
and it would execute as a transaction. But thinking now I'm not sure if there is such a thing

**Comment by seancorfield** [comment]
Are you comfortable with me closing this issue then?

**Comment by patrickds** [comment]
Yep sure, thanks for the help :)
