### ISSUE TITLE
When using against PostgreSQL what is the best way to insert/update array columns?

### ISSUE THREAD

**Issue by athiramukundan** [jkk/honeysql#223]
My table has the following schema:
```sql
create table table_name (
    id SERIAL NOT NULL PRIMARY KEY,
    column_with_int_array INTEGER [] NOT NULL,
);
```

**Comment by jakemcc** [comment]
Hi @athiramukundan. The below works for me. This is using `[honeysql "0.9.2"]`. `db` is just a delay that is holding my database connection pool.


```clojure
(ns outpace.targeting-engine.db
  (:require [clojure.java.jdbc :as jdbc]
            [honeysql.core :as hsql]
            [honeysql.types :as hsql-types]))

(defn insert-with-array [conn xs]
  (->> {:insert-into :table-name
        :columns [:column-with-int-array]
        :values [[(hsql-types/array xs)]]}
       hsql/format
       (jdbc/execute! conn)))

(comment
  (insert-with-array @db [1 2 3 4]))
```

**Comment by seancorfield** [comment]
Thanks @jakemcc Closing this out as "answered" (and Issues are not really mention for support questions -- asking questions in the #honeysql channel on the Clojurians Slack would be preferred).

**Comment by arichiardi** [comment]
Thank you for the answer! I would add ClojureVerse to the list of support question places - answers are persisted and reusable :smile:

**Comment by seancorfield** [comment]
I don't pay much attention to ClojureVerse (I don't like web forums) so #honeysql on Slack is the fastest place to get my attention. Just FYI.
