### ISSUE TITLE
An inline keyword should not retain its colon

### ISSUE THREAD

**Issue by vincent-dm** [jkk/honeysql#224]
Keywords are often used to represent constants in Clojure code, and they often correspond to ENUM values in the DB.

E.g. we use the ENUM value `unit` in Postgres and represent it as `:unit` in our Clojure code. However, this where-clause would not work because HoneySQL tries to interpret the keyword as a column:
```
[:= :some-column :unit]
```

Our current solution is to first convert the keyword to a string and then inline it, because it is not some unsafe thing that needs parametrization:
```
[:= :some-column (sql/inline (name :unit))]
```

However, I think the following syntax would be much easier to read and more sensible for any imaginable use case:
```
[:= :some-column (sql/inline :unit)]
```

Because of that, I propose that the way inline values are stringified should be improved, since there is no reason why Clojure's colon-representation of a keyword would make sense in SQL code.

**Comment by seancorfield** [comment]
This relates to #221 which I'm still thinking about. This has bigger implications than just how to stringify `inline` values.
