### ISSUE TITLE
sset helper does not lift params from sql/raw

### ISSUE THREAD

**Issue by antonmos** [jkk/honeysql#227]
```
(-> (helpers/update :foo)
    (helpers/sset {:bar (sql/raw ["bar + " 123])})
    (helpers/where [:= :a :?baz])
    (sql/format :params {:baz "BAZ"}))
=> ["UPDATE foo SET bar = [\"bar + \" 123] WHERE a = ?" "BAZ"]
```

If i am reading the docs correctly, it should produce 
```
["UPDATE foo SET bar = bar + ? WHERE a = ?" "BAZ" 123]
```

**Comment by seancorfield** [comment]
There are a number of problems with the way both `raw` and `inline` are implemented that need to be revisited. For the example given above, I would consider this approach instead:
```
user=> (require '[honeysql.core :as h] '[honeysql.helpers :refer :all] '[honeysql.types :as sql])
nil
user=> (-> (update :foo) (sset {:bar (sql/call :+ :bar 123)}) (where [:= :a :?baz]))
{:update :foo, :set {:bar #sql/call [:+ :bar 123]}, :where [:= :a :?baz]}
user=> (h/format *1 :params {:baz "BAZ"})
["UPDATE foo SET bar = (bar + ?) WHERE a = ?" 123 "BAZ"]
user=> 
```

**Comment by antonmos** [comment]
i see! May be a good thing to add to the docs, until the proper change is done.

**Comment by seancorfield** [comment]
I was a bit surprised your original code didn't work, so in some ways that's just a bug, but overall I'm not sure yet what to do with `raw` and `inline` and the parameter-lifting that was added to `raw` recently was a workaround for a different problem. Hence, I'm not sure what the docs should be changed to say at this point. If I fix the bug with `sset`/`raw`, no doc change would be needed _yet_.

**Comment by seancorfield** [comment]
I added a `sql/call` example into the README section for `sset`.

**Comment by seancorfield** [comment]
Given that I updated the README ages ago to show how to set expressions and I still don't have a good path forward with `raw`/`inline`, I'm just going to close this out and take no action for now.
