### ISSUE TITLE
Merge-where produces an extra :and

### ISSUE THREAD

**Issue by arichiardi** [jkk/honeysql#228]
Hello folks!

I found that when I do `(sqlh/merge-where {} [])` I receive back a ` {:where [:and]}`.
It is probably a bug in the way `honeysql` handles the clauses.

Has anyone else experienced that?

Thank you :wave:

**Comment by seancorfield** [comment]
I don't see that. Can you provide repro steps?
```
(! 619)-> clj -Sdeps '{:deps {honeysql {:mvn/version "RELEASE"}}}'
Clojure 1.9.0
user=> (require '[honeysql.core :as h] '[honeysql.helpers :refer :all])
WARNING: update already refers to: #'clojure.core/update in namespace: user, being replaced by: #'honeysql.helpers/update
nil
user=> (merge-where {} [])
{:where []}
user=> (-> (select :*) (from :table) (merge-where [:= :foo 42]))
{:select (:*), :from (:table), :where [:= :foo 42]}
user=> (h/format *1)
["SELECT * FROM table WHERE foo = ?" 42]
user=> 
```

**Comment by arichiardi** [comment]
Yep sure, this is what I see:

```clojure
Clojure 1.10.0-alpha6
user=> (require '[honeysql.core :as h] '[honeysql.helpers :refer :all])
WARNING: update already refers to: #'clojure.core/update in namespace: user, being replaced by: #'honeysql.helpers/update
nil
user=>  (merge-where {:where [:and [:= 1 1]]} [])
{:where [:and [:and [:= 1 1]] []]}
```

**Comment by seancorfield** [comment]
How did you create that inner hashmap? It looks wrong to me.

**Comment by arichiardi** [comment]
Ah, that can be...let me see, thanks good point!

**Comment by seancorfield** [comment]
```
user=> (where [:= 1 1])
{:where [:= 1 1]}
user=> (-> *1 (merge-where [:= :id 4]))
{:where [:and [:= 1 1] [:= :id 4]]}
```
This is why the helpers are provided -- a lot of people find the raw maps hard to get right. Best not to mix'n'match.

Can this be closed?

**Comment by arichiardi** [comment]
I think so, thanks!

**Comment by arichiardi** [comment]
Well ok, but this is data transformation and I though the semantics of `merge-where`, given that `merge` is in the name, would allow `nil` or empty in input...that's mainly where my confusion comes from. That's good to know anyways :wink:

**Comment by seancorfield** [comment]
Both `where` and `merge-where` assume at least one predicate. The `merge-*` functions in HoneySQL are designed to take one or more "things" and add them correctly into an existing structure, i.e., taking into account whether that clause already exists in the structure. Using `apply` with them looks like an anti-pattern to me, based on how they're meant to be used (typed in by people).

I'm not averse to making `prep-where` return a `nil` value for `pred` in the case where there are no arguments or only the hashmap as the first and only app, which would then allow that usage tho'.

**Comment by arichiardi** [comment]
That's a tough one because while adding that would solve my problem if you really want to emphasize typing usage probably that should go there.

I (maybe wrongly) assumed that those helpers where data transformation helpers that "build up" the SQL map...

Not sure at this point how many folks think it that way though

**Comment by arichiardi** [comment]
Awesome will try it out tomorrow!
