### ISSUE TITLE
how to translate lower((ts_lexize('unaccent'," p "))[1])

### ISSUE THREAD

**Issue by geraldodev** [jkk/honeysql#23]
Hi,

Very good library, I'm going to use it a lot.

I have played with sql/call and sql/raw trying to translate the expression above.
The problems are
1) the extra parethesis are necessary and sql/call needs a name/keyword
2) the [1] is necessary because is a vector, if I inject  it using sql/raw inside sql/call there ll be a ',' separating.

What I'm looking for is a way to use honey in cases like this because I want the parameter goodies that honey bring to the table.

That's what I end up using 

```
(defn func-minusc-sem-acento [p]
  (str "lower((ts_lexize('unaccent'," p "))[1])"))

(defn municipio-pelo-nome [connection nome]
  (let [qry (str "select * from ibge_municipio where "
                 (func-minusc-sem-acento "nome") "=" (func-minusc-sem-acento " ? "))
        _ (prn qry)]
    (first
      (jdbc/query connection [qry nome]))))
```

**Comment by ddellacosta** [comment]
@geraldodev I realize this is rather old and you've probably figured out how to do this already--but here's one way to solve it with HoneySQL as is:

```clojure
(defmethod fn-handler "ts_lexize" [_ dict token]
  (str "(ts_lexize('" dict "', '" token "'))[1]"))
```
...and then, for example:

```clojure
=> (hsql/format (hsql/build {:select (hsql/call :lower (hsql/call :ts_lexize "dict" "token"))}))
["SELECT lower((ts_lexize('dict', 'token'))[1])"]
=>
```
