### ISSUE TITLE
Infer sequences from keywords?

### ISSUE THREAD

**Issue by vemv** [jkk/honeysql#232]
Hi there!

Currently, `{:select :id :from :users :limit 1}` is not acceptable syntax, and one should use `{:select [:id] :from [:users] :limit 1}`. Else `IllegalArgumentException Don't know how to create ISeq from: clojure.lang.Keyword` happens.

However, it seems to me that the intent of the former attempt is clear, and possibly unmistakable (what else could a user have meant?).

Have you considered this improvement already?

A possible argument against could be https://stuartsierra.com/2015/06/10/clojure-donts-heisenparameter . To which I would say that I keep making the same silly mistake from time to time, so some DWIM-ness could be welcome.

In any case, the current thrown error is not very expressive, so it could be improved without altering the current syntax.

WDYT?

Thanks - Victor

**Comment by seancorfield** [comment]
If you want the ability to use singular keywords (as well as pairs that define an alias), use the DSL. The underlying data structures will not be changed.
