### ISSUE TITLE
sset is misplaced in 0.9.4 in `update from select` queries

### ISSUE THREAD

**Issue by armed** [jkk/honeysql#235]
Hi, thanks for awesome library.

Here is minimal example which works in 0.9.2, but produces wrong SQL in 0.9.4

```clojure
(sql/format
 (-> (h/update [:films :f])
     (h/sset {:kind :c.test})
     (h/from [(-> (h/select :b.test)
                  (h/from [:bar :b])
                  (h/where [:= :b.id 1])) :c])
     (h/where [:= :f.kind "drama"])))
```
In 0.9.2 all seems ok:
```
["UPDATE films f SET kind = c.test FROM (SELECT b.test FROM bar b WHERE b.id = ?) c WHERE f.kind = ?" 1 "drama"]
```

But in 0.9.4 `SET` is placed after `FROM`
```
["UPDATE films f FROM (SELECT b.test FROM bar b WHERE b.id = ?) c SET kind = c.test WHERE f.kind = ?" 1 "drama"]
```

Is this bug, or I'm doing something wrong?

**Comment by seancorfield** [comment]
Looks like this got broken when we fixed https://github.com/jkk/honeysql/issues/200 and you can see the change here https://github.com/jkk/honeysql/commit/fcdf3269680a2b4f66c6864e60006a04edecf41d

At first glance I'm not sure how to solve both of these concerns at the same time -- will give it some thought.

**Comment by armed** [comment]
@seancorfield thanks for clarification, rolled back to 0.9.2 for now.

**Comment by armed** [comment]
https://stackoverflow.com/questions/1293330/how-can-i-do-an-update-statement-with-join-in-sql according to this answer different DBMS has their own `update` query format.
At first thought there have to be DB specific priority configurations (maybe by setting dialect globally or per `sql/format` call).

**Comment by seancorfield** [comment]
Having a dialect set in the `format` call would probably not play well with `register-clause!` which can add new clauses with different priorities or override default priorities (as shown in #200 -- the OP's workaround was to use `register-clause!` to modify the priority of `:set`).

Much as I dislike it, I think the most pragmatic approach would be to have multiple `SET` helpers at different priorities (and deprecate `:set` and `sset` perhaps). Of course, coming up with good names for those is going to be hard so I might just punt on attempting that and call them `set0` / `:set0 100` and `set1` / `:set1 155` and then folks only need to care if they have a compound `update` query where it matters...
