### ISSUE TITLE
Add support for multi-arity SQL functions

### ISSUE THREAD

**Issue by swam92** [jkk/honeysql#240]
Honeysql does not support the use of multi-arity functions via the ":%" operator.  This prohibits the use of functions, specifically 'coalesce' and 'nullif'. 

Line 391 of format.cljc reads :
```
\% (let [call-args (string/split (subs s 1) #"\." 2)]
```

Because the call to clojure.string/split has a limit of 2, it is impossible to create a function of multiple arguments.  

Adding support for this feature would be beneficial for the following reasons:
* Lessen the dependencies on ``` sql/raw ```
* Improve readability of honeysql statements
* Remove a barrier to add support for more SQL functions in the future
* Allow the use of multi-arity functions in embedded statements

**Comment by swam92** [comment]
Thanks for fixing this

**Comment by sumbach** [comment]
@seancorfield This change might be breaking for (many?) existing use cases -- I suspect this syntax is commonly used to call aggregate functions with qualified column names: `:%max.foo.qty`. Where multiple arguments are required, I think `sql/call` would suffice.

/cc @swam92

**Comment by seancorfield** [comment]
@sumbach Ouch! I hadn't thought of qualified column names. I don't know how widespread that usage is, but you're right that it would be breaking. I will revert this change!

**Comment by seancorfield** [comment]
Per @sumbach if you want to call functions with more than one argument, use `sql/call`.
