### ISSUE TITLE
Don't uppercase modifiers?

### ISSUE THREAD

**Issue by b-ryan** [jkk/honeysql#241]
I wanted to use `modifiers` to implement `DISTINCT ON` functionality using the suggestion here: https://github.com/jkk/honeysql/issues/1#issue-12977128 but this doesn't work properly when you want to properly quote Postgres identifiers. For example:

```clojure
(format {:select [:x] :modifiers ["DISTINCT ON (\"capitalizationMatters\")"}])
```

Produces

```clojure
["SELECT DISTINCT ON (\"CAPITALIZATIONMATTERS\") x "]
```

Which doesn't work. The simple solution appears to be to not upper-case the modifiers, but I don't know what implications this has.

**Comment by seancorfield** [comment]
`DISTINCT ON` is PostgreSQL-specific and will not be added to HoneySQL. It is however already raised as an issue on `honeysql-postgres` (which is where it belongs): https://github.com/nilenso/honeysql-postgres/issues/31

**Comment by b-ryan** [comment]
Yes I'm aware of that issue but I wasn't asking for distinct on support. I'm pointing out that the modifiers functionality is broken, at least from my point of view, and am wondering if there's some reason to uppercase the modifiers other than having the generated sql read more consistently.

**Comment by seancorfield** [comment]
You're trying to use `modifiers` for something other than its designed purpose -- it is not "broken".

**Comment by b-ryan** [comment]
Could you help me understand what the designed purpose is? I understand not wanting to change the behavior since it could be seen as a breaking change. At this point I'm just trying to understand the context / what the designed purpose is. I had looked through to the original commit from 7 years ago where the code had been touched but it didn't look like I was going to get to the root of it. 

At this point I'm mostly curious to increase my understanding. Thanks

**Comment by seancorfield** [comment]
It is intended to provide a SQL keyword as a modifier for SELECT. Very limited scope. I think it's actually a bad idea, even in its current form, so I'd really rather not extend its use to anything else -- and especially not as a workaround for lack of PostgreSQL-specific syntax in the core library.

**Comment by b-ryan** [comment]
Alright thanks for the help
