### ISSUE TITLE
Any way or suggestions for using infix conditionals?

### ISSUE THREAD

**Issue by b-ryan** [jkk/honeysql#243]
I have a scenario where we effectively allow users to generate their own WHERE clauses and our representation of that clause is an array like:

```
["A" "AND" "B" "AND" ["C" "OR" "D"]]
```

Thus far I have been handling this by converting to a raw SQL string because I couldn't find a way to use this within what honeysql provides unless I converted the expression to prefix and that seemed daunting / not worth it. But now I am having difficulty extending the functionality because I have to manually manipulate the bindings by doing stuff like:

```
(let [[where-sql & where-bindings] (generate-where-clause ...)
      [select-sql & select-bindings] (format {:select [:x] :from [:y]})]
  (concat
    [(str select-sql where-sql)
     select-bindings
     where-bindings])
```

and it's getting unwieldy. I am curious if there's a better way to deal with this. If there's nothing immediately available, I have been thinking I'd write a `:inline-where` extension locally - but I'm trying to avoid it.

**Comment by seancorfield** [comment]
I would look at mapping your DSL to HoneySQL's underlying data DSL, instead of converting to strings directly. Mapping to `[:and "A" "B" [:or "C" "D"]]` should be pretty easy. And this will scale in complexity easily too.

You might also consider changing the representation for your WHERE clauses to be more amenable to that. We use Instaparse at work to turn English-like search criteria into data that can be used to build actual search criteria.

For the top-level `AND`, you could use `merge-where`, but for `OR` you'll need `[:or "C" "D"]` (and similarly for nested `AND`).

Out of scope for HoneySQL itself tho' -- and you might get more (useful) suggestions from a broader range of HoneySQL users if you ask questions in the `#honeysql` channel on the Clojurians Slack.

**Comment by b-ryan** [comment]
I revisited mapping to the honeysql DSL and you're right, it's not that complicated. I was experimenting with it a few nights ago, but I think it was too late at night.

The main edge case that needs to be dealt with is the precedence of AND and OR. I just wrote out an algorithm that I think works though. If you or anyone who stumbles on this is interested, here's what I'm going with:

algorithm

1. create an AND vector vector and an OR vector and add an "and" to the end of
   the expression
    and = [:and]
    or = [:or]

2. iterate through items.
    (A.) if item is a collection, call the algorithm recursively and add the
         result to the OR vector
    (B.) if it's AND
        (C.) if OR vector has 1 item, do nothing (I don't think this scenario
             is actually possible given a well-formed expression)
        (D.) elif OR vector has 2 items, add the second item to AND, reset the
             OR vector
        (E.) else, add the OR vector to AND, reset the OR vector
    (F.) if it's OR, do nothing
    (G.) else, add it to the current OR vector

3. output the result
    (H.) if AND vector has 1 item, something screwy happened - your expression
      must have been empty
    (I.) if AND vector has 1 item, return the second item
    (J.) else return the whole AND vector


example walkthrough
    input -> `[a or b or c and [d or e and f and g]]`
    expected -> `[:and [:or a b c] [:and [:or d e] f g]]`

```
1. AND = [:and]  OR = [:or]   EXPR = [a or b or c and [d or e and f and g] and]
2.
    - a       (G.)     AND = [:and]  OR = [:or a]
    - or      (F.)     AND = [:and]  OR = [:or a]
    - b       (G.)     AND = [:and]  OR = [:or a b]
    - or      (F.)     AND = [:and]  OR = [:or a b]
    - c       (G.)     AND = [:and]  OR = [:or a b c]
    - and     (E.)     AND = [:and [:or a b c]]  OR = [:or]
    - [...]   (A.)     AND = [:and [:or a b c]]  OR = [:or [:and [:or g e] f g]]
        (see INNER WALKTHROUGH BELOW)
    - and     (D.)     AND = [:and [:or a b c] [:and [:or d e] f g]]  OR = [:or]
3. (J.) - result is [:and [:or a b c] [:and [:or d e] f g]]
```

INNER WALKTHROUGH

```
1. AND = [:and]  OR = [:or]   EXPR = [d or e and f and g and]
2.
    - d       (G.)     AND = [:and]  OR = [:or d]
    - or      (F.)     AND = [:and]  OR = [:or d]
    - e       (G.)     AND = [:and]  OR = [:or d e]
    - and     (E.)     AND = [:and [:or d e]]  OR = [:or]
    - f       (G.)     AND = [:and [:or d e]]  OR = [:or f]
    - and     (D.)     AND = [:and [:or d e] f]  OR = [:or]
    - g       (G.)     AND = [:and [:or d e] f]  OR = [:or g]
    - and     (D.)     AND = [:and [:or d e] f g]  OR = [:or]
3. (J.) - result is [:and [:or d e] f g]
```

I'll post a code snippet once I have that ready in case it's ever useful for someone.

**Comment by b-ryan** [comment]
Have initial code and it works given the test scenario in my algorithm above:

```clojure
(defn- second-or-all
  [items]
  (if (= (count items) 2)
    (second items)
    items))

(defn- inline->honeysql
  [expr]
  (loop [[and-vec or-vec] [[:and] [:or]]
         [item & remaining] (concat expr ["AND"])]
    (if item
      (recur
        (cond
          (coll? item)
            [and-vec (conj or-vec (parts->where item))]
          (= item "AND")
            [(conj and-vec (second-or-all or-vec)) [:or]]
          (= item "OR")
            [and-vec or-vec]
          :else [and-vec (conj or-vec item)])
        remaining)
      (second-or-all and-vec))))
```
