### ISSUE TITLE
NOT EXISTS

### ISSUE THREAD

**Issue by sorsasampo** [jkk/honeysql#245]
`:exists` is supported, but there does not seem to be `:not-exists`.

What is the best way to construct `WHERE NOT EXISTS` queries? Should support for `:not-exists` be added?

**Comment by sorsasampo** [comment]
Looks like creating the issue acted as rubber duck debugging, because I found the syntax:

```
(-> {:where [:not {:exists {:select [true]}}]} sql/build sql/format)
["WHERE NOT (EXISTS (SELECT TRUE))"]
```

I think this could be documented better somewhere. Either the README or `exists-test`. The only not mentioned in the README is `:not=`.

**Comment by seancorfield** [comment]
I've never seen such syntax before! TIL. PR for the README and/or tests welcome!

**Comment by seancorfield** [comment]
Since `:exists` isn't documented in the README, there's no obvious place to document "not exists" so I'm just going to close this out. A PR to add docs for exists/not exists would be well-received :)
