### ISSUE TITLE
`where` with multiple `nil` arguments result in `WHERE ()` SQL

### ISSUE THREAD

**Issue by p-himik** [jkk/honeysql#246]
honeysql 0.9.5
Initially started in #32 

Using just one `nil` works as expected:
```clojure
(-> (select :*)
    (from :t)
    (where nil)
    (format))
=> ["SELECT * FROM t"]
```
Using more than one results in `WHERE ()`:
```clojure
(-> (select :*)
    (from :t)
    (where nil nil)
    (format))
=> ["SELECT * FROM t WHERE ()"]
```

I think this is an important use-case to support because of the ability to do stuff like this:
```clojure
(defn get-user-query [args]
  (-> (select :*)
      (from :user)
      (where (when-some [n (:name args)]
               [:= :name n])
             (when-some [a? (:active? args)]
               [:= :active a?])
             (when-some [d (:joined-at args)]
               [:= :joined-at d]))))
```
Of course there are alternatives where you either filter `nil` args yourself or never add them in the first place. But to me the use-case seems to be rather sensible to have its support in the library itself, especially given that a single `nil` works just fine.

**Comment by p-himik** [comment]
@seancorfield Just in case the notification doesn't get through - I've left a comment in the commit because it doesn't really fix the issue.

**Comment by p-himik** [comment]
It also doesn't help filtering `nil`s from the map at all because it's already done during `format`: https://github.com/jkk/honeysql/blob/master/src/honeysql/format.cljc#L465
I *think* a proper fix would to both filter it and remove any clauses in `format-predicate*`'s `("and" "or" "xor")` branch that don't contain any arguments.

**Comment by seancorfield** [comment]
It worked when there were still some non-`nil` conditions. I've updated it to work when all are `nil` as well. See the tests here https://github.com/jkk/honeysql/blob/master/test/honeysql/core_test.cljc#L239-L255

I have no plans to handle `nil` values in `:and`/`:or` clauses -- only at the top-level and only in the helper.

**Comment by p-himik** [comment]
Great, thank you!
