### ISSUE TITLE
Redundant parens in columns clause

### ISSUE THREAD

**Issue by igrishaev** [jkk/honeysql#248]
The following map

```clojure
(sql/format {:select [:vals.a]
             :from [[{:values [[1 2 3]]} [:vals {:columns [:a :b :c]}]]]})
```

gives

```clojure
["SELECT vals.a FROM (VALUES (?, ?, ?)) vals ((a, b, c))" 1 2 3]
```

which breaks PostgreSQL syntax rules because of double parens around `a, b, c`. How can I skip them having only single parens?

**Comment by seancorfield** [comment]
Fixed on master. If you're using CLI/`deps.edn` you can test this via Git deps. Otherwise, feel free to clone and install locally to verify it does what you expect without breaking anything else.
