### ISSUE TITLE
`format-join` no longer supports a boolean predicate

### ISSUE THREAD

**Issue by ted-coakley-otm** [jkk/honeysql#253]
Before version 0.9.4, and this commit that adds support for join `USING` https://github.com/jkk/honeysql/pull/201/commits/8a6ecd94aad4de06993883b9265a15cf73881f54 
It was possible to join a table `ON TRUE`
e.g
```
{:join [[:table :t] true]}
-> 
INNER JOIN table t ON TRUE
```

This is useful in particular when using lateral joins in postgresql, but I think this is valid for other use cases also. 

Offending code is in `honeysql.format/format-join`
```
(when pred
  (if (= :using (first pred))
    (str " USING (" (->> pred rest (map quote-identifier) comma-join) ")")
    (str " ON " (format-predicate* pred))))
```
Which throws an IllegalArgumentException `Don't know how to create ISeq from: java.lang.Boolean` when pred = true

Could we add a check that pred is sequential before `(= :using (first pred))`

**Comment by seancorfield** [comment]
Looks like this last worked in HoneySQL 0.9.2. It was broken in 0.9.3. Confirmed still broken in 0.9.8.

**Comment by ted-coakley-otm** [comment]
@seancorfield Thanks for the quick fix and release

**Comment by ted-coakley-otm** [comment]
@seancorfield 

Sorry to come back to this, but I think that one more change is necessary that I didn't spot at the time. This doesn't support the case when predicate is `false` i.e `JOIN table ON FALSE` , which is also valid SQL. Use `(when (some? pred) ...)` instead.

**Comment by seancorfield** [comment]
Ouch! Yes, good catch. Will try to get to that today (and release 0.9.9.1 I think).

**Comment by seancorfield** [comment]
It'll be in 0.9.10 (given the addition of `except` as well).

**Comment by seancorfield** [comment]
0.9.10 is on clojars.
