### ISSUE TITLE
Add support for `except` set operation

### ISSUE THREAD

**Issue by ted-coakley-otm** [jkk/honeysql#254]
The library currently supports `UNION`, `UNION ALL` & `INTERSECT`, would be good to also support `EXCEPT`

**Comment by seancorfield** [comment]
Seems to be part of ANSI SQL so, yup, I'll add that.

**Comment by tcoakley1** [comment]
Added a PR https://github.com/jkk/honeysql/pull/255

**Comment by seancorfield** [comment]
Fixed by #255

**Comment by seancorfield** [comment]
0.9.10 is on clojars. Thank you!
