### ISSUE TITLE
2.0: rethink "raw"

### ISSUE THREAD

**Issue by seancorfield** [jkk/honeysql#261]
Originally, `raw` just accepted a string and that was the SQL result. Then it was extended to support a vector of mixed SQL and values and the behavior is that strings are left alone but other types are "converted to SQL". This is both limited and surprising since the code cannot tell the difference between a literal string and an expression that yields a string. It also doesn't perform any useful conversion of values to SQL "strings" (e.g., when `x` yields a string `"foo"`, it should become `"'foo'"`) because HoneySQL doesn't know anything about parameterization when building raw SQL strings.

It would be helpful to figure out how people are using `raw` and how it could be handled better.

**Comment by seancorfield** [comment]
As I'm working on 2.x, I ran across a related bit of functionality: in 1.x, `inline` effectively has the same "problem" as `raw`. In 1.x, if you `inline` a string, it becomes literal SQL syntax because there's no coercion to SQL types. I'm planning to side-step the whole `honeysql.types` stuff in 2.x and use "special syntax" (in an extensible way) so that what is currently `(sql/inline x)` will become `[:inline x]` and then apply coercion to SQL types for a given set of input types, which would include turning `[:inline "foo"]` into `'foo'`.

I think I would approach `raw` in the same way but, again, the issue of "parameterized raw SQL" still comes up and I haven't yet spent enough time thinking about that.

**Comment by pounard** [comment]
> Then it was extended to support a vector of mixed SQL and values and the behavior is that strings are left alone but other types are "converted to SQL". This is both limited and surprising since the code cannot tell the difference between a literal string and an expression that yields a string.

I wrote a similar query builder using another techno (PHP) and I solved this problem using two different solutions:

 - first trick is by creating types for values, allowing the user to disambiguate what is given to the raw query: so I ended up with types such as `expression(string, expression[])`, `value(<any value dynamically typed>, string type)` (which extends expression), and a few others. First one carries SQL and a list of arbitrary parameters which are the same type, allowing to build very complex expressions easily, the second one carries a value along with its type, which can then be used by the formatter to do whatever it has to do,

 - whenever a raw SQL statement is given to the formatter, strings of the form: `?|?::TYPE` are caught inside, values are being passed as a list to the formatter, and replaced along, `?` means any value, determined dynamically, `?::TYPE` where `TYPE` can be anything, means that the formatter must convert the associated value using the given type.

**Comment by seancorfield** [comment]
The v2 behavior:
* `[:raw "string"]` produces the literal `string` as SQL
* `[:raw ["vector" "of" "strings"]]` produces the literal `vectorofstrings` as SQL

Vector subexpressions are formatted as SQL & params so you can have `[:inline "string"]` which will produce `'string'` as SQL and `[:param :foo]` which will produce `?` as SQL and will use the value of the `:foo` parameter value in the formatted result. Also `[:lift 5]` will produce `?` as SQL with `5` as a parameter value in the formatted result.
