### ISSUE TITLE
2.0: simplify extension machinery

### ISSUE THREAD

**Issue by seancorfield** [jkk/honeysql#262]
Currently, in order to add a new clause, you must:
* Decide a priority for it and register that
* Extend `format-clause` and/or `format-modifiers`
* Potentially add helpers and perhaps extend `build-clause`

The priority list is crowded in places so finding a new, unique priority may be hard. This could be automated and registration could just specify two existing clauses to slot in between?

The `format-clause` extensions involve a lot of repetition and boilerplate. They could be categorized and built on top of a handful of reusable formatters. This would potentially allow for much more declarative extension.

In addition, the helpers could mostly be generated from the extension declarations, if that could be made sufficiently regular.

**Comment by jrdoane** [comment]
Is the first point an active issue? Crowding can be solved by adding enough space between clause priorities, but the problem might be that priority is a little more complicated than just being a discrete position and that the clauses that another is paired with could influence its position. Just food for thought. I don't have a good solution to that, but it seems to me that if someone wants to extend HoneySQL, that flexibility is far more important than ease of use.

**Comment by seancorfield** [comment]
Currently, changing any of the built-in priorities (to accommodate a new clause) _could_ break anyone's code that assumes a particular priority. There's also the issue that different SQL dialects actually do have different priorities (`SET` is different between MySQL and PostgreSQL, for example, leading to the nasty `:set0` and `:set1` stuff in the current list.

By changing to an ordered list (with synthetic priorities generated at startup) and having registration of new clauses select an existing clause to "insert after", no one has to worry about numeric priorities and it also becomes much less likely that adding a new built-in clause would break user-space extensions.

I'm also thinking of dialect support directly in HoneySQL, if the extension machinery can be made more declarative, since it would alleviate issues such as `:limit` (supported) vs `:top` (not supported), and the `:set` issue and so on.

**Comment by jrdoane** [comment]
SELECT TOP and LIMIT were the first that came to my mind, to be honest.

**Comment by seancorfield** [comment]
@jrdoane TOP/LIMIT etc will be handled in #292 and I'm declaring the rest of this issue "done" based on the current state of the v2 branch.
