### ISSUE TITLE
How to increment a field in one transaction? 

### ISSUE THREAD

**Issue by WorldsEndless** [jkk/honeysql#264]
Many (most?) SQL have functions to increment a field, such as a views counter for a video table. 

Here it is in Postgres https://stackoverflow.com/questions/10233298/increment-a-value-in-postgres

And  identical in MySQL: https://www.tech-recipes.com/rx/2139/mysql_increment_an_exisitng_value/

Is there a way to do this in Honey without writing a custom function? 

``` sql
UPDATE totals 
   SET total = total + 1
WHERE name = 'bill';
```

**Comment by WorldsEndless** [comment]
Apologies. As Honey is for queries, not updates, this issue clearly doesn't belong here.

**Comment by WorldsEndless** [comment]
For any future investigators, one approach is here: http://clojure-doc.org/articles/ecosystem/java_jdbc/using_sql.html#updating-rows

**Comment by jrdoane** [comment]
FWIW, I highly suggest looking into using `next.jdbc` instead, but you can use `execute!` with any query you want, including updates.
https://github.com/seancorfield/next-jdbc

```clojure
(jdbc/execute! db-connection ["UPDATE totals SET total = total + 1 WHERE name = ?", "bill"])
```

**Comment by seancorfield** [comment]
The readme has an example of this: https://github.com/seancorfield/honeysql#updates
