### ISSUE TITLE
Missing variadic arguments causes hard to track down error

### ISSUE THREAD

**Issue by mmower** [jkk/honeysql#265]
In a query I am building I missed that `merge-where` is variadic and passed a collection instead of arguments. This lead to:

    Execution error (ClassCastException) at honeysql.format/format-predicate* (format.cljc:481).
    clojure.lang.PersistentVector cannot be cast to clojure.lang.Named

which was a little hard to track down as the query itself (using the helpers) was being generated fine.

It was only when I had installed Ultra and got a color-coded, syntax highlighted version of the unformatted query to look at that I noticed some missing `[:and …`'s in the query and realised what I had done.

It may be that there's nothing you can do here, but I thought I would flag it.

**Comment by seancorfield** [comment]
@mmower Can you provide a concrete repro case so I can take a look?

**Comment by seancorfield** [comment]
_bump_ @mmower Any chance of a concrete example of this?

**Comment by seancorfield** [comment]
Closing this out for lack of response.
