### ISSUE TITLE
2.0 A `pretty-format` functionality

### ISSUE THREAD

**Issue by green-coder** [jkk/honeysql#266]
While using HoneySQL, I found myself often having to insert new lines in the SQL statements generated by the `format` function in order to read them and see if the SQL is what I wanted to obtain.

It would be nice for the user to have a programmatic way to make the generated SQL string readable on multiple lines.

I imagine multiple approaches:
1. Having the `format` function take a `:pretty true` option.
2. Having a separate `pretty-format` function just for development purpose.
3. Having a `pretty-sql` function that changes a string of SQL into a prettier string of SQL.

The option 2 avoids any performance impact on the `format` function.
The option 3 additionally avoids any coupling between SQL generation and "pretty formatting".

**Comment by seancorfield** [comment]
In 2.0, `format` will accept a `:pretty? true` option that will add newlines into the generated SQL.
