### ISSUE TITLE
Assert failed: Alias should have two parts

### ISSUE THREAD

**Issue by frankiechz** [jkk/honeysql#267]
Hi, @seancorfield, thanks for honeysql. I'm really enjoying it.

I have an issue with version 1.0.444.

I have a table with multiple text array columns. When I try to insert to any of these columns **with one string in a vector**, I get the following assertion failture:

```
Execution error (AssertionError) at honeysql.format/seq->sql (format.cljc:385).
Assert failed: Alias should have two parts["Genre"]
```

An example map being inserted:

```clojure
{:identifier 123 :genres ["Genre"]}
```

The insert function:

```clojure
(defn insert! [m]
  (run (-> (insert-into :items)
           (values [m]))))
```

The run function:

```clojure
(defn run [raw-query]
  (let [query (if (map? raw-query)
                (sql/format raw-query)
                raw-query)]
    (jdbc/execute! *db* query)))
```

Has anyone seen this? Any advice on the direction to take would be very helpful. Thank you!

**Comment by seancorfield** [comment]
Can you try using `{:identifier 123 :genres #sql/array ["Genre"]}`, which should generate:
```clojure
["INSERT INTO items (identifier genres) VALUES (?, ARRAY[?])" 123 "Genre"]
```
I don't know if PG will accept that in the SQL (I don't use PostgreSQL) and I realize it isn't a true solution to this.

**Comment by frankiechz** [comment]
Thanks for the response, Sean.

Pardon me, I'm beginning Clojure development, how do you suggest I use `#sql/array` in the map like this?

**Comment by frankiechz** [comment]
Thanks for the response, Sean.

```clojure
(-> (insert-into :item) (values [{:identifier 123 :genres #sql/array ["Genre"]}]))
```

Yes, this works without the assertion failure! :D Thank you.

Pardon me, I'm beginning Clojure development, how do you suggest I use #sql/array in the map via the example `insert!` function above? For example, if I already have the map all together being sent to the function -- how do I automatically insert #sql/array at every vector in the map?

**Comment by seancorfield** [comment]
GitHub issues aren't a good place for that sort of interactive discussion. If you're just getting started with Clojure I'd strongly recommend joining the Clojurians Slack and ask that sort of question in the #beginners channel -- folks there have opted in to help new developers get up to speed on the basics. You can sign up for that Slack at http://clojurians.net -- the Slack itself is at https://clojurians.slack.com

In the meantime, I'll dig into why HoneySQL is treating this as something that could be aliased -- it's definitely a bug.

**Comment by frankiechz** [comment]
Great. Thanks, Sean, and thanks again for an awesome library.

**Comment by seancorfield** [comment]
In HoneySQL 2.0, the `#sql/array` syntax will go away and `[:array ["Genre"]]` will be standard function syntax. This will also work in a `select` statement (although it will need an extra `[`...`]` wrapped around it to avoid confusion with an alias pair) so this should be simpler to use -- and it will also all be properly documented.
