### ISSUE TITLE
Check that the value passed to `sql/param` is actually present in the parameters map

### ISSUE THREAD

**Issue by p-himik** [jkk/honeysql#268]
Every unspecified parameter becomes `nil`.
I would expect `sql/format` to fail here because I explicitly specify the need for the parameter, but don't pass any parameters at all.

```clojure
(sql/format (sql/call :array_length (sql/param :array)))
=> ["array_length(?)" nil]
```

**Comment by seancorfield** [comment]
This seems to be the culprit:
```clojure
  SqlParam
  (to-sql [x]
    (let [pname (param-name x)]
      (if (map? @*input-params*)
        (add-param pname (get @*input-params* pname))
        (let [x (first @*input-params*)]
          (swap! *input-params* rest)
          (add-param pname x)))))
```
Both arms should check `*input-params*` further:
* The `map?` clause should check `contains?`
* The else clause should check `seq`

**Comment by seancorfield** [comment]
This check is performed in v2. Both `:?foo` and `[:param :foo]` are supported in v2 and they both check that the named parameter is passed to `format` (as part of a consolidated options hash map, under the `:params` key).

I'll leave this open for now: I'm not sure whether I'll fix this in v1 at this point.

**Comment by seancorfield** [comment]
This is not going to get fixed in v1 unless someone sends a PR so I'm going to close this out.
