### ISSUE TITLE
Automatically dedupe parameter values with `identical?`

### ISSUE THREAD

**Issue by p-himik** [jkk/honeysql#269]
If the very same value is reused in an sqlmap, it will be sent multiple times.
I think it's possible to dedupe such parameters, but it would require switching from `?` to positional parameters like `$1`. I have no idea if that's possible with JDBC.

```clojure
(let [s "Hello there"]
  (sql/format (hh/select [(sql/call :length s) :a]
                         [s :s])))
=> ["SELECT length(?) AS a, ? AS s" "Hello there" "Hello there"]
```

**Comment by seancorfield** [comment]
I don't think those `$N` parameters are portable across all databases so this feels like quite a bit of additional complexity for a relatively small gain. I'll do some testing and see how widely supported that is.

**Comment by p-himik** [comment]
Thanks! Perhaps, if the implementation is not that complicated, it could be put behind an extra flag to `sql/format`, similar to how `:quoting` works.

**Comment by seancorfield** [comment]
There is a built-in "parameterizer" for PostgreSQL syntax -- I discovered it once I started writing HoneySQL 2.x -- it's an extensible system and it relies on dynamic variables and side-effects (via atoms) so it's a bunch of complexity I don't want to replicate in the 2.x version.

I'm going to close this out, but I would consider a PR against the 1.x version if you're still sufficiently interested in this feature, but overall I am leaning toward dropping the whole parameterizer machinery at this point (for 2.x).
