### ISSUE TITLE
UPDATE ... SET ... FROM ... WHERE rendered in incorrect order - regression

### ISSUE THREAD

**Issue by stathissideris** [jkk/honeysql#272]
The PG manual shows a form of updates which does an implicit join by using `FROM`. See https://www.postgresql.org/docs/12/sql-update.html and search for "A similar result could be accomplished with a join:"

```
UPDATE accounts SET contact_first_name = first_name,
                    contact_last_name = last_name
  FROM salesmen WHERE salesmen.id = accounts.sales_id;
```

HoneySQL (v1.0.444) renders this as UPDATE ... FROM ... SET ... WHERE ... - the order is wrong:

```clojure
(honeysql.format/format {:update :a,
                         :set {:a.col2 :b.col2},
                         :from [:b],
                         :where
                         [:= :b.col1 :a.col1]})
```
produces:
```clojure
["UPDATE a FROM b SET a.col2 = b.col2 WHERE b.col1 = a.col1"]
```

This used to work correctly in version 0.8.0.

**Comment by seancorfield** [comment]
Use `:set0` instead of `:set` (or the `set0` helper instead of the `sset` helper) to get the "early" `SET`.

See #235 and #200 for the history on this. This is explained in the README: https://github.com/seancorfield/honeysql#updates

**Comment by stathissideris** [comment]
OK, sorry about the false positive, thanks for the explanation!

**Comment by seancorfield** [comment]
Note: 2.0 will support multiple SQL dialects and explicitly handles this `set` priority issue.
