### ISSUE TITLE
2.0 group, artifact, and namespaces

### ISSUE THREAD

**Issue by seancorfield** [jkk/honeysql#274]
The 1.x (and earlier) versions of HoneySQL used the shorthand group/artifact name of just `honeysql` which the Clojure CLI is trying to discourage (in favor of org/user name group IDs).

Since the group/artifact is not tied to the namespaces, this is probably a good opportunity to adopt a proper group ID and, in keeping with `next.jdbc` and several other projects I maintain, I'm considering `seancorfield/honeysql` for the 2.x (and later) versions of HoneySQL. Since folks would have to update their dependencies to specify `"2.x"` for the version, requiring them to _also_ update the group/artifact as a one-off for that upgrade seems reasonable.

The issue of namespaces is a little more complex. Current development work on 2.x is not changing anything in the existing namespaces but just adding two new ones: `honey.sql` (the primary API) and `honey.specs` (a work-in-progress placeholder for Specs for the data DSL).

That has the benefit that users can upgrade to 2.x (changing the group ID) and not have to touch any of their existing code since all the old namespaces would continue to work. Users would not be able to have both 1.x and 2.x on their classpath, however, since the old namespaces would conflict -- and that would be a problem if they depended on a library that depended on the 1.x version but wanted to use the new 2.x code.

One way to avoid that would be to simply keep the old group ID which would allow a dependency on `honeysql/honeysql {:mvn/version "2.0"}` to simply "replace" any transitive dependency on the 1.x version. That perpetuates the "bad" group ID however. Another possibility would be to _remove_ all of the 1.x namespaces prior to making any 2.x release (even an alpha) and then users could just _add_ a dependency on 2.x and have both versions side-by-side with no conflicts between the namespaces: `honeysql.*` would come from 1.x and `honey.sql` etc would come from 2.x. Users could depend on both versions of the library while they are migrating, and then remove the 1.x dependency when they are done.

**Comment by dharrigan** [comment]
I like your second approach. It promotes a cleaner upgrade path and those with the ability to jump to `honey.sql` easily could do that, by removing the old dependency and using the new one. Second approach gets my vote!

**Comment by seancorfield** [comment]
The namespaces will be `honey.sql` and `honey.sql.helpers` and the group/artifact will be `seancorfield/honeysql` for v2
