### ISSUE TITLE
2.0 Minimum Clojure version support?

### ISSUE THREAD

**Issue by seancorfield** [jkk/honeysql#275]
HoneySQL 1.x supports Clojure 1.7 and later, as well as ClojureScript (I'm not sure which versions -- it's tested against whatever version `olical/cljs-test-runner` uses).

HoneySQL 2.x currently requires Clojure 1.9 because of the use of `boolean?` but that could easily be changed (and with that change it does still run on Clojure 1.7).

However, #146 (Spec support) is affected by this support: if Clojure 1.9 were to be the minimum supported version, the Specs could be leveraged directly in the new code, else they must remain optional.

**Comment by dcj** [comment]
I am totally fine wih 1.9 being minimum required version. 
Suggest others with nothing more to add "thumbs up" this comment.

**Comment by dharrigan** [comment]
I concur. There's a time when one has to draw a line and move forward. 1.9 and above gets my vote too!

**Comment by seancorfield** [comment]
v2 now requires 1.9 or later.
