### ISSUE TITLE
Consider "SIMILAR TO" (in addition with ilike clause)

### ISSUE THREAD

**Issue by dharrigan** [jkk/honeysql#280]
Hi,

In addition to `ilike`, would it be possible to also add `similar to` which is part of `SQL:1999` (and `SQL:2003`). It would allow for better pattern matching (for example, supporting `%(a|b)%`)

Here is a linked PostgreSQL explaination:

https://www.postgresql.org/docs/11/functions-matching.html#FUNCTIONS-SIMILARTO-REGEXP

Thank you.

-=david=-

**Comment by seancorfield** [comment]
Adding `:similar-to` and `:not-similar-to` as infix ops is trivial (done & pushed to v2).

Supporting the `ESCAPE` clause variant is a bit harder so I'll have to give them some thought.

**Comment by dharrigan** [comment]
Thanks Sean! If i had known it was so easy, I would have done a PR myself! :-)

**Comment by seancorfield** [comment]
I may have to implement `:similar-to-escape` as "special syntax" for the full version, but adding new infix ops is easy for end users in v2: https://github.com/seancorfield/honeysql/tree/v2#extensibility

**Comment by seancorfield** [comment]
Since you can have `ESCAPE` on all of the regex patterns, I added a special syntax so you can have a pattern with its escape characters for any op, e.g.,
```clojure
... :where [:similar-to :foo [:escape "a%|b_" [:inline ""]]] ...
;;=> WHERE foo SIMILAR TO ? ESCAPE ''
;;=> with "a%|b_" as a parameter
```
