### ISSUE TITLE
Improve Google BigQuery SQL compatibility

### ISSUE THREAD

**Issue by littleli** [jkk/honeysql#281]
BigQuery dialect of SQL includes an additional properties
- SELECT * EXCEPT
- SELECT * REPLACE
- WITH queries (like in Postgres)
- VALUE tables
- Literals for TIME, DATE, DATETIME, ARRAYs, STRUCTs

It would be nice to know how far we can get with current HoneySQL capabilities and improve in situations where capabilities are lacking and understand limits.

References
- [Query Syntax](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax)
- [Lexical Structure](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical)
- [Date functions](https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions)
- [DateTime functions](https://cloud.google.com/bigquery/docs/reference/standard-sql/datetime_functions)

**Comment by markaddleman** [comment]
fwiw, we use BigQuery and it is not difficult to extend HoneySQL to support BQ SQL constructs.  I have implemented support for WITH, SELECT AS STRUCT, STRUCT.  A couple of examples:

Select as struct:
`(defmethod fmt/format-modifiers :struct [_] "AS STRUCT")`

The struct "function call" requires a bit of cribbing Honey's context to get the "AS" alias capability:
`(defmethod fmt/fn-handler "STRUCT" [_ & args]
  (str "STRUCT(" (fmt/comma-join (map (fn [arg]
                                        (if (vector? arg)
                                          (let [[a b] arg]
                                            (str (fmt/to-sql a) " AS " (fmt/to-sql b)))
                                          (fmt/to-sql arg)))
                                      args)) ")"))`

`(sql/format (sql/call "STRUCT" [:a :alias-name] :c :d))` => `"STRUCT(a AS alias_name, c, d)"`

Pretty much everything you need is in the `honeysql.format` namespace

**Comment by cyppan** [comment]
I'm trying to use the Bigquery DDL syntax to create / update my tables and it looks like the honey extensions point are not enough (add-column and with-columns) 
To make it work, I'm forced to introduce new clauses that mimic the original add-column and with-columns but with special handling for adding structures (`my_struct STRUCT<name STRING, description STRING, ...>`) and arrays (`my_array ARRAY<STRING>`), I also use a private var in the honey namespace (format-single-column) so it's far from ideal.

I would be happy to try to contribute but I'm asking you some feedback first, maybe I miss something.

Here the whole code I hope it will be more clear:

```clj
(require '[honey.sql.helpers :as sql-h] '[honey.sql :as sql] '[clojure.string :as str])

;; @doc https://github.com/seancorfield/honeysql/blob/develop/doc/extending-honeysql.md

;; honey functions extensions
;;---------------------

;; add a new SQL *function*, to extend add column syntax to support struct too
(sql/register-fn! :bigquery/struct-column
                  (fn [f [& args]]
                    (let [[id args] (if (not (sequential? (first args)))
                                      [(first args) (rest args)]
                                      [nil args])]
                      [(str (when id (str (name id) " ")) "STRUCT<"
                            (->> args
                                 (mapv #'sql/format-single-column)
                                 (str/join ", "))
                            ">")])))

;; Example
(comment
  (sql/format-expr [:bigquery/struct-column :my_struct [:name :string [:not nil]] [:description :string]])
  ;; => ["my_struct STRUCT<name STRING NOT NULL, description STRING>"]
  )

;; add a new SQL *function*, to extend add column syntax to support arrays too
(sql/register-fn! :bigquery/array-column
                  (fn [f [id type]]
                    [(str (name id) " ARRAY<"
                          (first (sql/format-expr type {:inline true}))
                          ">")]))

;; Example
(comment
  (sql/format-expr [:bigquery/array-column :my_array :string])
  ;; => ["my_array ARRAY<string>"]
  ;; now with an array of struct
  (sql/format-expr [:bigquery/array-column :my_array [:bigquery/struct-column
                                                      [:name :string [:not nil]]
                                                      [:description :string]]])
  ;; => ["my_array ARRAY<STRUCT<name STRING NOT NULL, description STRING>>"]
  )

;; honey clauses extensions
;;-------------------------

(defn format-single-column [arg]
  (let [[first-column-arg] arg]
    (str (if (#{:bigquery/struct-column :bigquery/array-column} first-column-arg)
           (first (sql/format-expr arg {:inline true}))
           (#'sql/format-single-column arg)))))

(sql/register-clause! :bigquery/with-columns
                      (fn [f args]
                        [(str "WITH COLUMNS ("
                              (->> args
                                   (mapv format-single-column)
                                   (str/join ", "))
                              ")")])
                      :create-view)

(sql/register-clause! :bigquery/add-column
                      (fn [f args]
                        [(str (->> args
                                   (mapv (fn [arg]
                                           (str "ADD COLUMN IF NOT EXISTS " (format-single-column arg))))
                                   (str/join ", ")))])
                      :drop-column)

;; sql helpers
(defn with-columns [m columns]
  (assoc m :bigquery/with-columns columns))
(defn add-column [m column]
  (update m :bigquery/add-column conj column))

(comment
  (sql/format (-> (sql-h/create-table :my-table :if-not-exists)
                  (with-columns [[:name :string [:not nil]]
                                 [:bigquery/struct-column :my_struct [:name :string [:not nil]] [:description :string]]
                                 [:bigquery/array-column :my_array :string]])))
  ;; OR
  (sql/format {:create-table          [:my-table :if-not-exists]
               :bigquery/with-columns [[:name :string [:not nil]]
                                       [:bigquery/struct-column :my_struct [:name :string [:not nil]] [:description :string]]
                                       [:bigquery/array-column :my_array :string]]})
  ;; => ["CREATE TABLE IF NOT EXISTS my_table WITH COLUMNS (name STRING NOT NULL, my_struct STRUCT<name STRING NOT NULL, description STRING>, my_array ARRAY<string>)"]

  (sql/format {:alter-table         [:my-table]
               :bigquery/add-column [[:name :string]
                                     [:bigquery/struct-column :my_struct [:name :string] [:description :string]]
                                     [:bigquery/array-column :my_array :string]]})
  ;; OR
  (sql/format (-> (sql-h/alter-table :my-table)
                  (add-column [:name :string])
                  (add-column [:bigquery/struct-column :my_struct [:name :string] [:description :string]])
                  (add-column [:bigquery/array-column :my_array :string])))
  ;; => ["ALTER TABLE my_table ADD COLUMN IF NOT EXISTS my_array ARRAY<string>, ADD COLUMN IF NOT EXISTS my_struct STRUCT<name STRING, description STRING>, ADD COLUMN IF NOT EXISTS name STRING"]
  )
```

**Comment by seancorfield** [comment]
This feels like an overly complicated approach since it is just the _type_ portion that needs to expand to `STRUCT<>` or `ARRAY<>` so you should only need functions for that part and then you wouldn't need special handling for `with-columns` or `add-columns`.

I don't have time to dig into this at the moment but will try to find some time in a week or two to revisit this.

**Comment by cyppan** [comment]
Oh yes there is no need to override the with-columns clauses how dumb I am.. 
I thought it didn't work because I was trying with `(with-columns [[:bigquery/array-column :my_array :string] ...])` but the right way to do it is `[:my_array [:bigquery/array-column :string]]` which makes the function correctly executed 🎉

I still need to override the add-column clause though because it does not support `:if-not-exists`, what are your thoughts about this, would you support it in the DSL even if mysql (the primary target for this library AFAIK) does not support it?

**Comment by seancorfield** [comment]
The original target for HoneySQL was vendor-neutral and supposedly ANSI-compatible but with 2.0 I am supporting a variety of dialects and have greatly expanded the core ANSI dialect support, as well as having support for MySQL and (some support for) Oracle -- and supporting PostgreSQL in the default ANSI dialect, even where PG diverges.

Looks like `add column if not exists` came to PostgreSQL somewhere between 9.1 and 9.6 so I'll open a separate ticket to add support for that since "several" databases support it now. I bet HoneySQL doesn't support `drop column if exists` either, which I guess it should!

**Comment by seancorfield** [comment]
See #354

**Comment by seancorfield** [comment]
I will also add the array/struct syntax from this ticket. I like the namespaced-keyword approach but I wonder if any other databases have those types too? (and therefore the namespace should not be tied to BigQuery)

**Comment by cyppan** [comment]
> The original target for HoneySQL was vendor-neutral and supposedly ANSI-compatible but with 2.0 I am supporting ...    

Good to know

Postgres (at least) supports arrays too (https://www.postgresql.org/docs/9.1/arrays.html) but with a different syntax (ex integer[] vs array<integer> in BQ). But I think for now structs are only a bigquery thing.
So if I follow your logic, the array formatting difference could maybe be handled by the dialect setting (and so the function should not be namespaced) but BQ / Postgres have different features / limitations for them:
- you can specify array size only in postgres arrays
-  postgres array can be multidimensional, BQ can't.
- BQ arrays can be array of structs
- ..?

**Comment by seancorfield** [comment]
Currently, the dialect mechanism doesn't influence functions so that will require some thought before I go down that path.

**Comment by shay-rf** [comment]
+1 for inherently supporting "SELECT * EXCEPT" and "SELECT * REPLACE"
Those select flavors are getting used a lot.
I tried to look into setting these up via the clause extensions but most of the functionality of handling the select and the helper as wells are under private functions. Unless I miss something implementing this from the external API not seems right.
Currently, I am resolving this expression directly and attach it under [:raw] - It could be that supporting it internally would make it better integrated.

**Comment by seancorfield** [comment]
Given that there's already an `EXCEPT` clause that means something different, I'm going to need to come up with some other approach for dealing with `* EXCEPT ... REPLACE ...` and variants of it. I'll look at how I handle `*` (which is already a special case) and maybe having a vector beginning with `*` could be parsed for `:except` and/or `:replace` with their respective syntax. _[Although this has conflicts with alias syntax and, potentially, expression syntax so maybe this will not work]_

**Comment by seancorfield** [comment]
@shay-rf @littleli Please take a look at PR #376 which adds support for BigQuery's except/replace syntax and provide feedback.

**Comment by shay-rf** [comment]
Thanks! The syntax makes sense and this seems to work properly.
The use case that is not working is when there is a prefix to the * - for example :aaa.*
This works : (h/select [:* :except [:a :b :c]])
But this one not: (h/select [:aaa.* :except [:a :b :c]])

**Comment by seancorfield** [comment]
Ah, yes, good catch! PR updated to support that.

**Comment by shay-rf** [comment]
Cool, it seems to work properly.

**Comment by seancorfield** [comment]
@littleli @markaddleman @cyppan PR #376 now includes support for `ARRAY<>` and `STRUCT<>` syntax. See the tests in that PR (and the updates to the docs) for details -- specifically this commit https://github.com/seancorfield/honeysql/pull/376/commits/99ce051a9d1c6b7c75d1dc75435a04e96fde4a42. Feedback welcome.

**Comment by seancorfield** [comment]
FYI:

I'm probably going to draw a line under this work early next week and merge this PR and cut a release -- and close this ticket.

I'll ask that any additional BigQuery compatibility requests are raised as individual tickets (since the initial ask here was very broad and mostly just pointed me at Google's docs to read).

**Comment by seancorfield** [comment]
PR #376 merged. Please open new issues for additional, specific BigQuery compatibility issues.

**Comment by shay-rf** [comment]
Thanks a lot Sean for setting this up. I just found out that the following is also supported:
SELECT * EXCEPT (a, b) REPLACE (123 as c)

That is to remove few columns and replace values for other columns. A classical 2-for-Tuesday case :(
I hit this when performing union on multiple queries, and doing except on a column and then re-introduce that column messes the order of the columns for the union.

I mainly wanted to double check that the current syntax does not really support this, right? I will sort this out for my use case this way or the other. Would you like me to open an issue or should we only keep this comment for future reference?

**Comment by seancorfield** [comment]
@shay-rf You mean like this test: https://github.com/seancorfield/honeysql/blob/develop/test/honey/bigquery_test.cljc#L18-L19

**Comment by shay-rf** [comment]
Yes! I am so glad this is covered :) 
Thanks!
