### ISSUE TITLE
How to write an ORDER BY {EXPR} clause?

### ISSUE THREAD

**Issue by aneilbaboo** [jkk/honeysql#285]
I'm trying to write query where rows which match a clause appear first:

```sql
SELECT * 
FROM processes 
WHERE state = ?
ORDER BY id = ? DESC;
```
I'm trying the following:

```clojure
(-> (select :*) 
    (from :processes)
    (where [:= :state state])
    (order-by [[:= :id pid] :desc])
    sql/format)
```

And have tried variations, but I receive an error about the order-by expression.

```clojure
Assert failed: Alias should have two parts[:= :id #uuid "d957fb32-284c-4678-95f4-6e53767e5df0"]
(= 2 (count x))
```

What is the right way to pass an expression to ORDER BY in HoneySQL?

**Comment by seancorfield** [comment]
This is a case where you have to be explicit about the "call" of the operator:
```
(order-by [(sql/call := :id pid) :desc])
```
Questions like this are probably best asked either in the #honeysql channel of the Clojurians Slack (http://clojurians.net to sign up; https://clojurians.slack.com to chat) or in the #honeysql stream of the Clojurians Zulip Chat (https://clojurians.zulipchat.com).

**Comment by seancorfield** [comment]
In HoneySQL 2.0, this will work as you originally wrote it, without needing the `call` invocation.

**Comment by aneilbaboo** [comment]
Got it, thanks! I signed up for the Clojurians Slack.
