### ISSUE TITLE
How to use honeysql.core/call with array param ?

### ISSUE THREAD

**Issue by jgallinari** [jkk/honeysql#288]
Hi,
I need to call a Postgres stored procedure that expects a text[] parameter, but can't get it to work.
Maybe you can enlighten me?

If I try the following, here's what I get:

```clojure
  (def param-names ["HOST_MNO"])
  (def session-auth-id "1234")
  (def offer-id 88060)
  (def addon-name "MASTER_MNO")
  (println (-> (honeysql.helpers/select :*)
               (honeysql.helpers/from (honeysql.core/call :meta_db.get_offer_param_value_list :?session-auth-id :?offer-id :?addon-name :?param-name-array))
               (honeysql.core/format :params {:session-auth-id session-auth-id :offer-id offer-id :addon-name addon-name :param-name-array (honeysql.types/array param-names)})))

["SELECT * FROM meta_db.get_offer_param_value_list(?, ?, ?, ?)" "1234" 88060 "MASTER_MNO" #sql/array (["HOST_MNO"])]
nil
```

Any chance I could get something like:
```clojure
["SELECT * FROM meta_db.get_offer_param_value_list(?, ?, ?, ARRAY[?])" "1234" 88060 "MASTER_MNO" "HOST_MNO"]
```
?

NB: I've seen [The #sql/array syntax](https://github.com/seancorfield/honeysql/issues/85), but still no luck.
Thanks.

**Comment by seancorfield** [comment]
I don't use PostgreSQL (and GitHub Issues aren't the best place to ask usage questions). Your best bet is to ask folks in the `#honeysql` channel on either the Clojurians Slack or the Clojurians ZulipChat (the former has more users, so a better chance of a PostgreSQL user being able to help you).

**Comment by borkdude** [comment]
@seancorfield You could consider enabling "Discussions" on this repo. This has the benefit that answers to questions are better found using web searches and also enable folks to join who aren't on chat platforms.

**Comment by seancorfield** [comment]
https://github.com/seancorfield/honeysql/discussions/
