### ISSUE TITLE
Support USING for Delete for PostgreSQL (for HoneySQL v2)

### ISSUE THREAD

**Issue by dharrigan** [jkk/honeysql#289]
PostgreSQL uses the keyword `using` in order to perform joins when executing a [delete](https://www.postgresql.org/docs/11/sql-delete.html). Whilst it is entirely possible, with HoneySQL v1 to use the extensibility feature to add this into the mix, it would be good to allow this automagically for HoneySQL v2.

Here is an example using v1:

```
(defmethod fmt/format-clause :using [[_ v] _]
  (str "USING " (fmt/to-sql v)))

(fmt/register-clause! :using 110)

(defhelper using [m args]
  (assoc m :using (first args)))

(-> (delete-from :foo)
    (using :bar)
    (where [:= :bar_id :bar.id]
           [:= :bar.name "baz")
    sql/format))

["DELETE FROM foo USING bar WHERE (bar_id = bar.id AND bar.name = ?)" "baz"]

```

**Comment by seancorfield** [comment]
Supported in v2
