### ISSUE TITLE
:values behavior confusing with heterogeneous maps

### ISSUE THREAD

**Issue by codonnell-reify** [jkk/honeysql#291]
The current behavior for formatting `:values` clauses determines the columns by using the keys from the first map. If a user provides maps with extra keys on subsequent maps, those values will be silently omitted. This behavior can be somewhat confusing if you're not aware of it.

**Comment by seancorfield** [comment]
Fixed in v2: pads missing columns with `NULL` values; both vectors and maps have been updated to be consistent lengths.
