### ISSUE TITLE
Please consider adding support for Create/Refresh/Drop Materialized Views in HoneySQL v2

### ISSUE THREAD

**Issue by dharrigan** [jkk/honeysql#301]
Hi,

Now that the Nilenso extensions have been brought into HoneySQL v2, it would be great if it could additionally support materialized views.

https://www.postgresql.org/docs/13/sql-creatematerializedview.html

In several of my projects, using HoneySQL v1, I currently do this:

`(-> (sql/raw (str "refresh materialized view " view " with data"))`

and in my migration scripts, I have this:

```
DROP MATERIALIZED VIEW IF EXISTS wibble;

CREATE MATERIALIZED VIEW IF NOT EXISTS wibble AS
SELECT foo, bar
FROM baz osl
         LEFT JOIN LATERAL (SELECT TRUE t FROM bou g WHERE st_intersects(g.coordinates, st_buffer(osl.stop_location, 500)) LIMIT 1) g ON TRUE
WHERE g.t IS NULL
WITH NO DATA;
```

Having native support within HoneySQL would be a very nice thing to have.

Thank you!

-=david=-

**Comment by seancorfield** [comment]
I'm looking to consolidate several create* things at this point so I'm looking at somehow implementing a generate syntactic patterns that allows me to map onto:

```
CREATE (SOME OPTIONAL KEYWORDS)* THE-THING [IF NOT EXISTS] entity 
  [some other stuff I haven't figured out yet]
  AS query
  WITH (SOME OPTIONAL KEYWORDS)*
```

So far I have a generic `format-create` function that takes `:the-thing` followed by `entity` or a collection where `entity` is the "last" element, optionally followed by `:if-not-exists`, and any elements prior to the `entity` become the `SOME OPTIONAL KEYWORDS` part.

I think a `:with-data true|false` will address the common `WITH [NO] DATA` clause but something else will be needed for some of the other `CREATE` statements.

**Comment by seancorfield** [comment]
```clojure
  (is (= (sql/format {:create-materialized-view [:metro :if-not-exists
                                                 (columns :foo :bar :baz)
                                                 [:tablespace [:entity :quux]]]
                      :select [:*]
                      :from :cities
                      :where [:= :metroflag "y"]
                      :with-data false})
         [(str "CREATE MATERIALIZED VIEW IF NOT EXISTS metro"
               " (foo, bar, baz) TABLESPACE quux"
               " AS SELECT * FROM cities WHERE metroflag = ? WITH NO DATA") "y"]))
```
(and there are helpers for all of that)
```clojure
  (is (= (sql/format {:drop-materialized-view [:if-exists :foo]})
         ["DROP MATERIALIZED VIEW IF EXISTS foo"]))
```
and
```clojure
  (is (= (sql/format (-> (refresh-materialized-view :concurrently :foo)
                         (with-data true)))
         ["REFRESH MATERIALIZED VIEW CONCURRENTLY foo WITH DATA"]))
```

**Comment by seancorfield** [comment]
Will be in next v2 alpha.
