### ISSUE TITLE
 Add support for CREATE TABLE .. AS

### ISSUE THREAD

**Issue by quan-nh** [jkk/honeysql#306]
CREATE TABLE AS — define a new table from the results of a query https://www.postgresql.org/docs/current/sql-createtableas.html

**Comment by seancorfield** [comment]
Lots of additional syntax options there. I'll have to think about how much of `:create-view` this could share with. https://www.postgresql.org/docs/13/sql-createview.html and whether it might be worth treating `:as` as a clause in its own right to make certain things easier. Also maybe `:with-data true/false` as a clause might be worthwhile.

**Comment by seancorfield** [comment]
Will be in next v2 alpha.
