### ISSUE TITLE
Make README clearer about helper functions

### ISSUE THREAD

**Issue by seancorfield** [jkk/honeysql#307]
Per feedback on Slack from @borkdude : 

> It's been several times now that I've been reading the README and I have trouble resolving mentally where some vars are coming from due to the use of :refer :all. E.g. right now I'm searching where insert-into is coming from (again). Can the README maybe use an alias, or an explicit :refer [...]?

**Comment by seancorfield** [comment]
In particular, make it clear that every SQL clause supported by HoneySQL is available both in data structures (as a keyword or symbol) and in helpers (as a function name).

In addition, note that most special syntax and operators do **not** have helper functions!

**Comment by borkdude** [comment]
The main README emphasizes the `insert-into` function while `:insert-into` is also possible. Maybe change the examples and add more links to "read more here" docs.
