### ISSUE TITLE
Can't use :raw as key in set clause

### ISSUE THREAD

**Issue by brjann** [jkk/honeysql#311]
Works in Honeysql 1

```clojure
(sql/format {:update :table
             :set    {:col1           1
                      (sql/raw "`col2`") 2}})

=> ["UPDATE table SET col1 = ?, `col2` = ?" 1 2]
```

Does not work in Honeysql 2
```clojure
(sql/format {:update :table
             :set    {:col1           1
                      [:raw "`col2`"] 2}})

=> Execution error (ClassCastException) at (REPL:1).
=> null
```

**Comment by seancorfield** [comment]
I'm actually shocked that worked in V1 -- it certainly wasn't intentional to allow that: a column name in a `SET` clause is not an expression context, it's an entity context.

If your goal is simply to quote an awkward column name, I'd recommend just telling HoneySQL to quote all symbols which happens via the `{:quoted true}` option argument to `sql/format` -- in V1 it was `:quoting :<dialect>` and not wrapped in a hash map.

**Comment by brjann** [comment]
This is actually related to the same goal of not bloating my IDE's autocompletion with `:CamelCased` keywords that I explained in #305. I'm working with a legacy database with lots of column names like `UserID`, `OrderCount` and I would prefer to not have `:UserId` and `:OrderCount` invade my autocompletion... 

Is there a way I can get Honey SQL 2 to produce `"UPDATE table SET OrderCount = OrderCount + 1"` without using `:OrderCount`?

**Comment by seancorfield** [comment]
So you're making your code much harder to read, just to avoid your editor trying to auto-complete based on keyword usage?

#305 was a bug: (certain) expressions should have been allowed in that context. Looking at the ANSI SQL docs, it's much harder to justify allowing an expression where a column name should go!

**Comment by brjann** [comment]
@seancorfield:  I'm just trying to keep that old database structure from creeping into my codebase. But you're quite right, the code is harder to read. Maybe silly, yes.

**Comment by brjann** [comment]
It would be awesome though if it was possible to just write a string in that entity context

```clojure
(sql/format {:update :table
             :set    {:col1        1
                      "OrderCount" 2}})
```

**Comment by brjann** [comment]
And this actually works, but I guess that it should not since OrderCount is also in entity position here?

```clojure
{:select [[[:raw "OrderCount"] :order-count]]
 :from   :table}

=> ["SELECT OrderCount AS order_count FROM table"]
```

**Comment by seancorfield** [comment]
`select` allows arbitrary expressions in that context, e.g., `select year(somedate) as yy from ...`

**Comment by brjann** [comment]
@seancorfield, yes of course! Sorry

**Comment by seancorfield** [comment]
```
user=> (sql/format {:update :table
  #_=>              :set    {:col1        1
  #_=>                       "OrderCount" 2}})
["UPDATE table SET col1 = ?, \"OrderCount\" = ?" 1 2]
```

**Comment by seancorfield** [comment]
Note: that's not going to work for MySQL-style quoted names -- it's sort of by accident that it works for ANSI-quoted names.

**Comment by brjann** [comment]
Yes, I'm using MySQL so I couldn't use string keys. But in this case it is actually easy to solve - I'll simply keywordize the keys in a `:set` clause before sending them to `format`. 

(and I have implemented a function `$` such that `($ "OrderCount")` returns ``[:raw "`OrderCount`"]``, so the code is not quite as horrible as my examples here)

**Comment by seancorfield** [comment]
If you call `(sql/set-dialect! :mysql)` at the start of your program, you could use strings in `set` and it would "do the right thing":

```clojure
(! 857)-> clj -Sdeps '{:deps {com.github.seancorfield/honeysql {:git/url "https://github.com/seancorfield/honeysql" :sha "9672ed3704ec2e37babf7b8782d0aa448c06ce0a"}}}'
Clojure 1.10.3
user=> (require '[honey.sql :as sql])
nil
user=> (sql/set-dialect! :mysql)
[:alter-table :add-column :drop-column ... ; rest omitted
(sql/format {:update :table
  #_=>              :set    {:col1        1
  #_=>                       "OrderCount" 2}})
["UPDATE table SET col1 = ?, `OrderCount` = ?" 1 2]
```
That would seem to be an elegant solution for your needs?

I happen to be using the latest from GitHub there but 2.0.0-alpha3 should also work like this. In fact, even Alpha 1 works like that:

```clojure
(! 859)-> clj -Sdeps '{:deps {seancorfield/honeysql {:mvn/version "2.0.0-alpha1"}}}'
Downloading: seancorfield/honeysql/2.0.0-alpha1/honeysql-2.0.0-alpha1.pom from clojars
Downloading: seancorfield/honeysql/2.0.0-alpha1/honeysql-2.0.0-alpha1.jar from clojars
Clojure 1.10.3
user=> (require '[honey.sql :as sql])
nil
user=> (sql/set-dialect! :mysql)
[:alter-table :add-column :drop-column ...
user=> (sql/format {:update :table
  #_=>              :set    {:col1        1
  #_=>                       "OrderCount" 2}})
["UPDATE table SET col1 = ?, `OrderCount` = ?" 1 2]
```

Going to close this since using a string is the appropriate solution I think for you, and that already works if you set the dialect correctly.

**Comment by brjann** [comment]
Thanks @seancorfield. I hadn't actually tried using a string as key since it doesn't work anywhere else. Thank you for all your work on Honey SQL!
