### ISSUE TITLE
Setting new values does not work with fully qualified keywords in PostgreSQL

### ISSUE THREAD

**Issue by aratare-jp** [jkk/honeysql#317]
# Context
I'm trying to update a row in a PostgreSQL table with the following code:

```clojure
(def data {:foo/bar 1})

(-> (helpers/update :user)
    (helpers/set data)
    (helpers/where [:= :user/id id])
    (helpers/returning :*)
    (sql/format {:dialect :ansi}))
```

# Problem
The above query will fail because:

- HoneySQL will translate such query into `... SET "foo"."bar" = 1 ...`, and
- PostgreSQL does not accept table name in `SET` clause.

# Expected behaviour
There should be a way to disable inclusion of table name in `SET` clause for PostgreSQL, or this should be handled by default.

**Comment by seancorfield** [comment]
You can either use a `:git/url` dep with `:sha "06f25ed2e3f96abce4920feca6034f954e138277"` or wait for the next alpha build.

**Comment by aratare-jp** [comment]
Will do. Thanks :)
