### ISSUE TITLE
Support for EXISTS

### ISSUE THREAD

**Issue by yenda** [jkk/honeysql#318]
It looks like this was supported in the v1: https://github.com/seancorfield/honeysql/pull/76/files

**Comment by seancorfield** [comment]
See https://cljdoc.org/d/seancorfield/honeysql/2.0.0-alpha3/doc/differences-from-1-x#exists

It was implemented incorrectly in V1. In V2 it's "just" a function.

**Comment by seancorfield** [comment]
See the tests for it in V2: https://github.com/seancorfield/honeysql/blob/v2/test/honey/sql_test.cljc#L150-L165
