### ISSUE TITLE
v2: INSERT... ON CONFLICT does not support unique index inference for multiple columns

### ISSUE THREAD

**Issue by hoxu** [jkk/honeysql#323]
At least I could not find a test case for this.

Example SQL:

```sql
INSERT INTO table(a, b) VALUES(1, 2) ON CONFLICT (a, b) DO NOTHING;
```

https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT

Emphasis mine:

> conflict_target can perform unique index inference. When performing inference, it consists of **one or more index_column_name columns** and/or index_expression expressions, and an optional index_predicate.

**Comment by seancorfield** [comment]
Definitely a bug in my interpretation of what it should allow. Will fix for the next Beta release.

**Comment by seancorfield** [comment]
Fixed on **v2** if you want to try it out via git.
