### ISSUE TITLE
offset weird behaviour

### ISSUE THREAD

**Issue by orestis** [jkk/honeysql#327]
Hey there, I was migrating some HoneySQL v1 code as a first foray and bumped into this:

Normal:
```
(sql/format {:select [:foo]
             :offset 10})
;=> ["SELECT foo OFFSET ?" 10]

(sql/format (h/offset  {:select [:foo]}
                        10 ))
;=> ["SELECT foo OFFSET ?" 10]
```

Unexpected but good, since `nil` offset would produce bad SQL (but the error is not so helpful)
```
(sql/format {:select [:foo]
             :offset nil})
; (err) Execution error (ExceptionInfo) at honey.sql/format-dsl (sql.cljc:904).
; (err) Unknown SQL clauses: :offset
```

Unexpected and also produces truly invalid SQL:
```
(sql/format (h/offset  {:select [:foo]}
                        nil ))
;=> ["OFFSET (SELECT foo)"]
```

My preference would be for offset (and limit, and potentially more) to be ignored when nil. It will remove a lot of conditionals  we have around just for those cases. But in second place would be to throw an exception because potentially a missing limit/offset might return a huge result set which could be dangerous if not intended.

**Comment by seancorfield** [comment]
This is a bit of a tricky one. Right now, there's an inherent assumption that a key in the DSL cannot have a `nil` value so the parsing logic draws no distinction between "unknown clause" and "clause has no value" -- which it really should -- but allowing _some_ clauses to have `nil` values but not others would be pretty complicated and really isn't a path I want to go down.

I think the best I can do here -- for now -- is to at least split the logic for "unknown" from "not `nil`" and provide a better error message here.

**Comment by seancorfield** [comment]
I decided to just update that exception: it now says `These SQL clauses are unknown or have nil values`

**Comment by seancorfield** [comment]
OK, the `(h/offset nil)` issue was a bug in _all_ single-argument helpers and is fixed as well:
```clojure
dev=> (sql/format (-> {:select :foo} (h/offset nil)))
Execution error (ExceptionInfo) at honey.sql/format-dsl (sql.cljc:904).
These SQL clauses are unknown or have nil values: :offset
dev=> (sql/format (-> {:select :foo} (h/offset 10)))
["SELECT foo OFFSET ?" 10]
```

**Comment by mrkam2** [comment]
> This is a bit of a tricky one. Right now, there's an inherent assumption that a key in the DSL cannot have a `nil` value so the parsing logic draws no distinction between "unknown clause" and "clause has no value" -- which it really should -- but allowing _some_ clauses to have `nil` values but not others would be pretty complicated and really isn't a path I want to go down.

I ran into a similar issue converting our codebase to HoneySQL v2. In particular, `offset` and `limit` helpers were conveniently skipping corresponding clauses from SQL when `nil` value was passed to them. With v2, this caused the exception. By looking at a source code a found a very ugly workaround to achieve the same behavior:

```
              (-> ...
                  (h/limit (or limit []))
                  (h/offset (or offset []))
                  ...)
```                    

Based on your thoughts above, you're not planning on supporting `nil` values for `limit` and `offset`. Would it also make sense to not support `[]` values?

I must admit that I would've been more happy if it actually supported `nil` values.

**Comment by seancorfield** [comment]
Please open a new issue about `[]` in that context for me to look at next time I'm doing OSS work (in a few weeks).

**Comment by mrkam2** [comment]
Opened https://github.com/seancorfield/honeysql/issues/361

**Comment by seancorfield** [comment]
Thanks!
