### ISSUE TITLE
Re-introduce `call` function from honeysql1

### ISSUE THREAD

**Issue by orestis** [jkk/honeysql#329]
While I think the nested vector/seq convention for function calls (and so many other things) seems to work fine, migrating codebases from honeysql1 is a bit painful because in those cases we use `core/call`. So migrating the code becomes a chore of either:

1. Manually replace the calls to `call` with a vector.
2. Define a project-level `call` function and replace the reference

There's a second point about readability: it feels a bit harder to parse queries with multiple levels of nested vectors, as some of them can be aliases. 

In any case, it would help migrations greatly if we could get a honeysql-native `call` function that could just be:

```
(defn call [f & args]
  (apply vector f args))
```

Thanks!

**Comment by seancorfield** [comment]
3. Do a find'n'replace to turn `core/call` into `vector` (from `clojure.core`) 😄 

I will add this. I just have to think about how/where to document it because I don't think I want to encourage the use of it.

**Comment by orestis** [comment]
I guess it could be a deprecated or undocumented function (that doesn’t show up on cljdoc) :)

**Comment by seancorfield** [comment]
I have added this to `honey.sql` and marked it `^:no-doc` so that it will not appear in the documentation. It _is_ mentioned as a note in the "Differences" page so folks migrating from 1.x can learn about it.
