### ISSUE TITLE
more INSERT ... SELECT

### ISSUE THREAD

**Issue by mccraigmccraig** [jkk/honeysql#33]
INSERT INTO where one of the inserted columns is a subquery is supported with :

    (-> (insert-into :user_profile_to_role)
          (values [{:user_profile_id user-id
                    :role_id         (-> (select :id)
                                         (from :role)
                                         (where [:= :name role-name]))}])

and INSERT INTO where all of the inserted columns match a subquery with (a happy accident ?):

    (-> (insert-into [:bar (-> (select :id) (from :role))]))

but i can't figure out a way to to an INSERT...SELECT where the columns to be inserted are specified, e.g.

  INSERT INTO foo (id) (SELECT id FROM bar);

is this currently supported, or do i need to wrap the sub-query to match columns with the INSERT INTO table ?

**Comment by ddellacosta** [comment]
This is resolved with #50, now merged in and released.
