### ISSUE TITLE
Joins against a table named "entity" result in surprising/inconsistent behavior

### ISSUE THREAD

**Issue by john-shaffer** [jkk/honeysql#330]
Version: 2.0.0-rc3

```clj
(honey.sql/format
        {:select :* :from :dataset
         :join [[:b [:= :dataset.id :b.id]]
                [:entity [:= :b.id :entity.id]]]})
```

This throws because honeysql tries to destructure `:entity` as if it were a vector. This is fixed by replacing `:entity` with `[:entity :entity]`.

But this similar code does not throw:
```clj
(honey.sql/format
        {:select :* :from :dataset
         :join [:entity [:= :b.id :entity.id]]})
```

I'm not sure what the desired behavior is here, but I think that it should at least be consistent. Is the desired behavior to throw or to accept `"entity"` as the table name?

**Comment by john-shaffer** [comment]
It looks like I misunderstood the syntax, as this does work correctly:

```clj
(honey.sql/format
        {:select :* :from :dataset
         :join [:b [:= :dataset.id :b.id]
                :entity [:= :b.id :entity.id]]})
```

Can we either accept the vector-of-vector syntax or throw a more informative error? I'd be happy to make a PR, just need guidance on how you want it handled.

(I'd also like to add a multiple join example to the docs, so making a note here).

**Comment by seancorfield** [comment]
How's this:

```clojure
dev=> (sql/format
 #_=>         {:select :* :from :dataset
 #_=>          :join [[:b [:= :dataset.id :b.id]]
 #_=>                 [:entity [:= :b.id :entity.id]]]})
Execution error (ExceptionInfo) at honey.sql/namespace (sql.cljc:160).
expected symbol, found: class clojure.lang.PersistentVector
dev=> *e
#error {
 :cause "expected symbol, found: class clojure.lang.PersistentVector"
 :data {:symbol [:= :b.id :entity.id], :failure "class clojure.lang.PersistentVector cannot be cast to class clojure.lang.Named (clojure.lang.PersistentVector and clojure.lang.Named are in unnamed module of loader 'app')"}
```

**Comment by john-shaffer** [comment]
Thanks! That looks perfect. I made a PR adding an example to the "big complicated map" in the README, as that was the first place I looked for an example and it seems like a very good spot for it.
