### ISSUE TITLE
Enhance keep-hyphen logic to allow - in operators

### ISSUE THREAD

**Issue by k3nj1g** [jkk/honeysql#340]
Is there any way we could register operators to work with json without register-fn! in custom way?
For example, "@@"  operator i have registered like 
```
(hsql/register-fn! :##
                   (fn [_ [a b]]
                     (let [[sql-a & params-a] (hsql/format-expr a)
                           [sql-b & params-b] (hsql/format-expr b)]
                       (-> [(str sql-a " @@ " sql-b)]
                           (into params-a)
                           (into params-b)))))
```

I think its totally ok, because symbol @ is reserverd for derefing and couldn't be used for keyword.
 
But what about "->" and "->>"? I think we should might register them with `sql/register-op!` 

Thank you for your work btw.

**Comment by seancorfield** [comment]
It took me a while to understand the problem here: if you try to register `:->` and `:->>` as operators, the leading `-` is converted to space when the SQL is formatted. Is that what you're asking about?

As for `@@`, one possibility is:

```clojure
dev=> (def atat (keyword "@@"))
#'dev/atat
dev=> (sql/register-op! atat)
nil
dev=> (sql/format {:select [ [ [atat :a :b] ] ]})
["SELECT a @@ b"]
```

**Comment by k3nj1g** [comment]
It would be more convenient to register the operator using with additional param. 
`(sql/register-op! atat {:keep-hyphen? true})`

**Comment by seancorfield** [comment]
There's already some logic in place to handle certain exceptions to the "replace hyphen with space" logic -- it just isn't smart enough right now. If I enhance that to only replace hyphens that are between alphanumerics, I believe that will solve that aspect of this issue.

Are you OK with the `atat`/`@@` workaround?

**Comment by seancorfield** [comment]
```clojure
dev=> (defn dehyphen [s]
 #_=>   (loop [s s prev nil]
 #_=>     (if (= s prev)
 #_=>       s
 #_=>       (recur (str/replace s #"(\w)-(\w)" "$1 $2") s))))
```
Something like that works to replace all hyphens that are adjacent to "word" characters (I'm sure this could be improved but my regex-fu has failed so far).

**Comment by orestis** [comment]
Just for Google help: If you're looking to support the Postgres JSON/JSONB operators `->` and `->>`, this issue (and the associated fix) is what you're looking for. The fix works great as far as I can see, all you need is:

```
(sql/register-op! :-> :variadic true)
(sql/register-op! :->> :variadic true)
```

**Comment by seancorfield** [comment]
Thanks, @orestis ! I assume `@@` is also variadic?

**Comment by orestis** [comment]
I don't think so @seancorfield : https://www.postgresql.org/docs/12/functions-textsearch.html the arguments there are `tsvector` and `tsquery` so I think it's binary. I'm not using those text search operators myself though.
