### ISSUE TITLE
Customize/Config positional/named parameter

### ISSUE THREAD

**Issue by zerg000000** [jkk/honeysql#341]
In JDBC world, we use `?` `:name` for positional parameter and named parameter.

For some db like PostgreSQL, the native query is using `$1`, `$2` for positional parameter.

Is honeysql intended to support them?

**Comment by seancorfield** [comment]
No. The numbered parameters will not be supported. Only `?` (positional) and named parameters. This was discussed and denied in a ticket early in the 2.x design phase.

**Comment by zerg000000** [comment]
@seancorfield May I know the related ticket? Since I cannot search for any or I don't know the proper keyword to search.

**Comment by seancorfield** [comment]
I don't remember. I'd have to spend time searching for it just like you would.
