### ISSUE TITLE
Unexpected result when using sql/call with :unique 

### ISSUE THREAD

**Issue by vushu** [jkk/honeysql#345]
using version
`        com.github.seancorfield/honeysql {:mvn/version "2.0.0-rc5"}
`
```
(ns test.database 
  (:require [honey.sql :as sql]
            [honey.sql.helpers :refer [with-columns create-table]]))
  

(-> (create-table :user)
      (with-columns [[:email (sql/call :varchar 60) (sql/call :unique :email)]])
      sql/format))
```

Actual result:
  CREATE TABLE user (email VARCHAR(60) UNIQUE EMAIL)

Expected result:
  CREATE TABLE user (email VARCHAR(60) UNIQUE (email))

**Comment by seancorfield** [comment]
See https://cljdoc.org/d/com.github.seancorfield/honeysql/2.0.783/doc/getting-started/sql-special-syntax-#index-unique

The first argument to `unique` is assumed to be the name given to the constraint. You should pass `nil` if the constraint is unnamed:

```clojure
dev=> (-> (h/create-table :user)
 #_=>       (h/with-columns [[:email (sql/call :varchar 60) [:unique nil :email]]])
 #_=>       sql/format)
["CREATE TABLE user (email VARCHAR(60) UNIQUE(EMAIL))"]
dev=> 
```
