### ISSUE TITLE
Strings not handled correctly for CREATE TABLE

### ISSUE THREAD

**Issue by seancorfield** [jkk/honeysql#353]
In order to get through the namespaced/dotted-name handling for keywords/symbols in `format-entity` you are supposed to be able to use a string and get a literal, multi-segment, quoted name.

However, since the introduction of `destructure-create-items` to handle additional syntax, strings are not passed through correctly and, even then, `format-entity` does not handle more than two segments in a dotted (string) name.

This is the expected behavior:

```clojure
dev=> (sql/format (h/create-table "project-dashed.dataset.table"))
["CREATE TABLE \"project-dashed\".\"dataset\".\"table\""]
```

**Comment by cyppan** [comment]
I'm surprised about the quotes around the table name, is it valid sql? (it's not valid bigquery standard sql at least)

**Comment by seancorfield** [comment]
Using a string triggers quoting according to whatever dialect is selected -- the reason being that you normally only use strings when you want to either circumvent the `-` to `_` translation or you have a table/column name that is not representable as a Clojure symbol/keyword.

The default dialect is ANSI which uses double-quoting, as does PostgreSQL.

Looks like BigQuery expects backticks which is what MySQL uses, so you'll need to select that dialect:

```clojure
dev=> (sql/set-dialect! :mysql)
[...]
dev=> (sql/format (h/create-table "project-dashed.dataset.table"))
["CREATE TABLE `project-dashed`.`dataset`.`table`"]
```

or you could stay in the default dialect (ANSI) and just specify the `:mysql` dialect for that call:

```clojure
dev=> (sql/format (h/create-table "project-dashed.dataset.table") {:dialect :mysql})
["CREATE TABLE `project-dashed`.`dataset`.`table`"]
```

**Comment by cyppan** [comment]
Oh ok I didn't set the dialect indeed, I understand better how you handle the different engines syntaxes now, thank you, it works as expected on "develop".

**Comment by cyppan** [comment]
I'm facing other problems with the `:from` clause, I don't know how I should specify my table name
```clj
  (sql/format {:create-table "a.b.c"} {:dialect :mysql})
  ;; ["CREATE TABLE `a`.`b`.`c`"]
  (sql/format {:from "a.b.c"} {:dialect :mysql})
  ;; ["FROM ?" "a.b.c"]
  (sql/format {:from [[:raw "`a`.`b`.`c`"]]} {:dialect :mysql})
  ;; ["FROM `raw` AS ``a`.`b`.`c``"]
```

Update: (sql/format {:from :a.b.c}) works as expected
```clj
(sql/format {:create-table :a.b.c} {:dialect :mysql})
=> ["CREATE TABLE `a`.`b`.`c`"]
```

**Comment by seancorfield** [comment]
Like with `select`, you need nesting to identify a function call (`:raw`) from an alias, and `from` takes a sequence of such things:
```clojure
dev=> (sql/format {:from [[[:raw "a.b.c"]]]} {:dialect :mysql})
["FROM a.b.c"]
```

**Comment by seancorfield** [comment]
With the *develop* version of HoneySQL, your original example works without strings:
```clojure
dev=> (sql/format (h/create-table :project-dashed.dataset.table) {:dialect :mysql})
["CREATE TABLE `project-dashed`.`dataset`.`table`"]
```

**Comment by cyppan** [comment]
Oh sorry I wasn't on develop anymore indeed thank you 🙏
