### ISSUE TITLE
Add support for "id = ANY(array-of-ids)" operator

### ISSUE THREAD

**Issue by mrkam2** [jkk/honeysql#360]
Originally in our project and for HoneySQL v1 I added support for `[:any :id ids]` operator which translated this into `["id = ANY(?)" ids]` where ids was a postgres array object rather than anything that converts into `"ANY(?, ?, ?)". Sometimes we use it with thousands of array values, so the latter isn't a good option for us.

Here is a v1 snippet of this:
```clojure
(defmethod hf/fn-handler "any" [_ field array]
  (str (hf/to-sql field) " = ANY(" (hf/to-sql (->pg-array array)) ")"))
```
where `->pg-array` is a helper function to generate an object that will be converted to postgres array later on.

This is how I implemented the same with v2:
```clojure
(h/register-fn!
  :any
  (fn [_ [field array]]
    (let [[sql & params] (h/format-expr field)]
      (concat [(str sql " = ANY(?)")]
              params
              [(->pg-array array)]))))
```

However, I realized that I might be able to take advantage of the new DSL of v2 and do something like this:
`[:= :id [:any  ids]]` but it doesn't seem to work as expected:

```clojure
(h/format-expr [:= :id [:any [:lift [1 2 3]]]])
["id = ? = ANY(?)" #function[clojure.lang.AFunction/1] nil]
```

Is this a bug?

**Comment by seancorfield** [comment]
`format-expr` doesn't have the full context for resolving lifted expressions.

You are correct that you can do this directly in v2 with no extensions:

```clojure
dev=> (sql/format {:select :foo :from :table :where [:in :id [:any [:lift [1 2 3]]]]})
["SELECT foo FROM table WHERE id IN ANY(?)" [1 2 3]]
```

**Comment by mrkam2** [comment]
> `format-expr` doesn't have the full context for resolving lifted expressions.

What does it missing? Or how can it be provided?

A quick example shows that `format` can be confused as well:

```clojure
(h/format {:where [:= :id [:any [1 2 3]]]})
["WHERE id = (?, ?, ?) = ANY(?)" 1 2 3 nil]
(h/format {:where [:in :id [:any [1 2 3]]]})
["WHERE id IN (?, ?, ?) = ANY(?)" 1 2 3 nil]
```

**Comment by seancorfield** [comment]
As the documentation says, you must use `:lift` for parameters that are data structures:
```clojure
dev=> (sql/format {:where [:= :id [:any [:lift [1 2 3]]]]})
["WHERE id = ANY(?)" [1 2 3]]
```

**Comment by mrkam2** [comment]
I just realized that it was my registered `:any` function that was corrupting all the experiments for me. Once I removed it, it started working:

```clojure
(honey.sql/format-expr [:= :id [:any [:lift [1 2 3]]]])
["id = ANY(?)" #function[clojure.lang.AFunction/1]]
```
