### ISSUE TITLE
`limit` and `offset` do not accept `nil` value but happy with `[]`

### ISSUE THREAD

**Issue by mrkam2** [jkk/honeysql#361]
In v1, `(limit nil)` or `(offset nil)` where interpreted as not having corresponding clauses. In v2, those throw `These SQL clauses are unknown or have nil values: :limit` exception upon formatting (as discussed in https://github.com/seancorfield/honeysql/issues/327).

An ugly workaround is to use `[]` instead:

```clojure
              (-> ...
                  (h/limit (or limit []))
                  (h/offset (or offset []))
                  ...)
```                  

Would be great to support `nil` and not support `[]`.

**Comment by mrkam2** [comment]
Current API requires something like this:
```clojure
                (-> ...
                    (#(if limit (h/limit % limit) %))
                    (#(if offset (h/offset % offset) %))
                    ...)
```

Is there a better alternative?

**Comment by seancorfield** [comment]
My preference is:
```clojure
    (-> ...
        (cond-> limit (h/limit limit))
        (cond-> offset (h/offset offset))
        ...)
```

**Comment by mrkam2** [comment]
Nice option, thanks for sharing!

**Comment by seancorfield** [comment]
Since the change to prevent `nil` arguments to clauses in general was an explicit and deliberate one (so folks don't accidentally get SQL with "missing" clauses) and there is a good idiom for handling optionality in threading forms -- as shown above with `cond->` -- I'm closing this out.
