### ISSUE TITLE
Can't use params with [:inline x]

### ISSUE THREAD

**Issue by evilsneer** [jkk/honeysql#362]
Produces some of 

```[:= 1 [:inline [:param :sources]]] -> "1 = PARAM SOURCES"```

I use global {:inline true}, but still..

**Comment by seancorfield** [comment]
You can't inline parameters. I'll make a note in the docs that is not possible. Parameter substitution happens at the end of formatting. Inline substitution happens during the parse/build phase.

**Comment by evilsneer** [comment]
But it works fine when `(sql/format hm {:inline true})`

**Comment by seancorfield** [comment]
The `:inline` special syntax and the `:inline` option are not the same thing (by design). As noted in the other ticket, inlining data structures is not supported and the `:inline` _syntax_ doesn't format its argument: it just treats it as a Clojure value.

**Comment by seancorfield** [comment]
Per #363 I decided to make `:inline` syntax work like localized `:inline true` options so this works as expected now. Thank you!
