### ISSUE TITLE
Operators with `@` character

### ISSUE THREAD

**Issue by tomasd** [jkk/honeysql#364]
`honey.sql/register-op!` expects operator to be a keyword. In postgresql there are couple of operators (e.g. [range](https://www.postgresql.org/docs/current/functions-range.html) or [text search](https://www.postgresql.org/docs/current/functions-textsearch.html)) which contains special character `@`. Unfortunately clojure reader does not support `@` in the keyword:

```clj
=> [:<@ :submitted [:range :begin :end]]
Execution error (ClassCastException) at luminare.backend.dev/eval32742 (form-init670959681325125999.clj:1).
class clojure.lang.Keyword cannot be cast to class java.util.concurrent.Future (clojure.lang.Keyword is in unnamed module of loader 'app'; java.util.concurrent.Future is in module java.base of loader 'bootstrap')
```

The only way to currently use it (except `:raw`) is to use `keyword` function:

```clj
(honey.sql/register-op! (keyword "<@"))
[(keyword "<@")  :submitted [:range :begin :end]]
```

Can you please provide more straightforward way to use these operators? Perhaps allowing `register-op!` to use also strings can help.

**Comment by seancorfield** [comment]
What I've recommended to other PostgreSQL users is:

```clojure
(def <at (keyword "<@"))

(sql/register-op! <at)

[<at :submitted [:range :begin :end]]
```

Something like this should be added to the (extensive) PostgreSQL section in Tips & Tricks.
