### ISSUE TITLE
set clauses (UNION/UNION ALL, etc) are parenthesized, which breaks sqlite (See #141)

### ISSUE THREAD

**Issue by zohar-cyc** [jkk/honeysql#365]
I see there was an issue (#141) before the rewrite.

**Comment by seancorfield** [comment]
I don't understand what you're asking here. Please provide an example and show the expected and actual output.

**Comment by seancorfield** [comment]
OK, I think you're referring to this (which is a regression from 1.x):

```clojure
user=> (sql/format {:union
  #_=>              [{:select :* :from :table}
  #_=>               {:select :* :from :other-table}]})
["(SELECT * FROM table) UNION (SELECT * FROM other_table)"]
```

I'll work on this in the coming week, as I'm on vacation.
