### ISSUE TITLE
cljdoc shows confusing (to me) documentation for some helpers due to :arglists metadata

### ISSUE THREAD

**Issue by ianmcorvidae** [jkk/honeysql#369]
I was looking at https://cljdoc.org/d/com.github.seancorfield/honeysql/2.1.818/api/honey.sql.helpers#limit (and other helpers, as I found later), and it led me down a wrong path. Since it listed only `(limit limit)` as an argument list, I mistakenly believed that the `limit` function could not be used within a threading macro unless it was the first function call within the threading (since it did not, apparently, accept a query as an optional first argument). This seemed non-ideal to me and I dove into the code to see if it was a documentation issue, a limitation of the code, or something else entirely, and after discerning how the `generic-1` function worked, concluded that it could, in fact, take that optional first argument despite the documentation indicating otherwise. I don't think that code spelunking should generally be required to understand a library's API, so I thought I would open an issue.

I think that this would be improved by amending the :arglists metadata that cljdoc uses to include the optional query argument.

I do see that there are past, closed issues raised about the arglists concerning linters, but I want to stress that my confusion was not due to a linter but was in fact due to normal human use of documentation, so I hope that this can be considered independently of those past issues. I do also understand that in the context of a threading macro, the current arglist corresponds, arguably, to how it appears, but since I understood how the threading macro works, my internal mental model knew that in reality, the function needed to be able to take two arguments to work and as such I was confused until I dug into the code.

Thanks for a great library and I hope this can help improve the documentation! I'm happy to do the grunt work of finding these spots and sending a PR if this is a welcome change.

**Comment by seancorfield** [comment]
Only about half of the helper functions have `:arglists`. The rest just have generic `& args` style arities (which is the underlying arity of every helper function.

I am adding the following text to the `honey.sql.helpers` _namespace_ docstring:

  All helper functions are inherently variadic. Typical
  usage is threaded, like this:

```
  (-> (select :a :b :c)
      (from :table)
      (where [:= :id 42])
      (sql/format))
```

  Therefore all helpers can take an existing DSL expression
  as their first argument or, if the first argument is not
  a hash map, an empty DSL is assumed -- an empty hash map.
  The above is therefore equivalent to:

```
  (-> {}
      (select :a :b :c)
      (from :table)
      (where [:= :id 42])
      (sql/format))
```

  Some of the helper functions here have `:arglists` metadata
  in an attempt to provide better hints for auto-complete in
  editors but those `:arglists` _always omit the DSL argument_
  to avoid duplicating the various argument lists. When you
  see an auto-complete suggestion like:

    bulk-collect-into [varname] [varname n]

  bear in mind that a DSL hash map can always be threaded in
  so the following (pseudo) arities are also available:

    bulk-collect-into [dsl varname] [dsl varname n]

  The actual arguments are:

    bulk-collect-info [& args]

  (as they are for all helper functions).
