### ISSUE TITLE
:not doesn't wrap in parens

### ISSUE THREAD

**Issue by valerauko** [jkk/honeysql#371]
`:not` doesn't wrap its arguments in parens, which can result in weird clash of operator precedence in the resulting SQL.

I'd suggest just explicitly wrapping _everything all the time_...

## Repro
```clojure
{:select :*
 :from :vblog_posts
 :where [:and
         [:between :post_id 23 2105]
         [:not [:and
                [:or
                 [:like :post_main "%[img%"]
                 [:like :post_long "%[img%"]]
                [:< :post_date 1239462000]]]
         [:not [:or
                [:like :post_main "%[devfav%"]
                [:like :post_long "%[devfav%"]]]
         [:= :post_id 415]]
 :limit 1}
```
### Current
```
["SELECT * FROM vblog_posts WHERE post_id BETWEEN ? AND ? AND NOT ((post_main LIKE ?) OR (post_long LIKE ?)) AND (post_date < ?) AND NOT (post_main LIKE ?) OR (post_long LIKE ?) AND (post_id = ?) LIMIT ?" 23 2105 "%[img%" "%[img%" 1239462000 "%[devfav%" "%[devfav%" 415 1]
```
### Expected
```
["SELECT * FROM vblog_posts WHERE (post_id BETWEEN ? AND ?) AND (NOT ((post_main LIKE ?) OR (post_long LIKE ?)) AND (post_date < ?)) AND (NOT (post_main LIKE ?) OR (post_long LIKE ?)) AND (post_id = ?) LIMIT ?" 23 2105 "%[img%" "%[img%" 1239462000 "%[devfav%" "%[devfav%" 415 1]
```

Slack [discussion thread](https://clojurians.slack.com/archives/C66EM8D5H/p1636037757002200)

**Comment by valerauko** [comment]
This can be worked around with `[[:nest [:not ,,,]]]` (double wraps around `:nest`)

**Comment by seancorfield** [comment]
See also #370

**Comment by valerauko** [comment]
@seancorfield is be1df97b2baaa03fa3f3f0c47101ef58763a72f6 a safe fix? Doesn't it break table definitions with NOT NULL in them?

**Comment by seancorfield** [comment]
There are tests and "doc tests" with `[:not nil]` and they all still work 😸 

The key here is that it uses `{:nested true}` so it only parenthesizes "complex" expressions, not simple ones.

Unlike `:nest` which _always_ puts `(` `)` around its formatted operand.

**Comment by seancorfield** [comment]
```clojure
dev=> (sql/format {:create-table :fruit
 #_=>                     :with-columns
 #_=>                     [[:id :int [:not nil]]
 #_=>                      [:name [:varchar 32] [:not nil]]
 #_=>                      [:cost :float :null]]})
["CREATE TABLE fruit (id INT NOT NULL, name VARCHAR(32) NOT NULL, cost FLOAT NULL)"]
dev=>
```

**Comment by valerauko** [comment]
Got it! Looking forward to the release when it's done

**Comment by seancorfield** [comment]
Probably early this coming week -- I want to get a couple of DDL enhancements in and maybe some doc updates too. You can use the 2.1.999-SNAPSHOT to test if you want (or a git dep). Every commit to develop pushes a snapshot to Clojars.

**Comment by seancorfield** [comment]
2.1.829 is on Clojars. The DDL enhancements went easier than I expected.

**Comment by valerauko** [comment]
Thanks!
