### ISSUE TITLE
select-distinct-on helper function merges incorrectly

### ISSUE THREAD

**Issue by Caluminus** [jkk/honeysql#372]
When merging 2 select-distinct-on functions, I would expect for the "distinct-on" fields from both functions to be aggregated, so that the distinct-on fields from function 1 and 2 are all distinct-on in the resulting SQL generated. However, merging just seems to chain the arguments of the two functions, meaning that you lose the distinct-on modifier for fields in the 2nd function.

Example below:
```
(-> (select-distinct-on [:a :b] :c :d)
    (select-distinct-on [:e :f] :g :h))
```

Expected result: `{:select-distinct-on [[:a :b :e :f] :c :d :g :h]}`
Actual result: `{:select-distinct-on [[:a :b] :c :d [:e :f] :g :h]}`

**Comment by seancorfield** [comment]
Definitely a bug. Thank you for catching it and reporting it. I suspect it will affect a few other helpers that wrap certain special DSL elements...

**Comment by seancorfield** [comment]
This is fixed on **develop**. I still need to review other helpers and see if any others need special treatment.

I also need to consider whether merging two _different_ types of `select` clauses should be an error or should be handled in an "intelligent" manner.

**Comment by seancorfield** [comment]
This will be in 2.1.833.
