### ISSUE TITLE
Helper for converting maps to where clause

### ISSUE THREAD

**Issue by corasaurus-hex** [jkk/honeysql#377]
It would be nice to have a helper for converting a map to a where clause structure.

For example, if you had `{:id 1 :status_id 2}` and wanted to convert it to `[:and [:= :id 1] [:= :status_id 2]]` you could write this yourself:

```clojure
(defn as-where [where-map]
  "Convert a map into an appropriate argument to pass to where,
  specifically one that combines each key-value pair into an equality check
  wrapped in an :and.

  (as-where {:id 1})
  ;; => [:= :id 1]
  (as-where {:status 2 :category 3})
  ;; => [:and [:= :status 2] [:= :category 3]]"
  (let [clauses (reduce-kv (fn [where col val]
                             (conj where [:= col val]))
                           []
                           where-map)]
    (if (> (count clauses) 1)
      (into [:and] clauses)
      (first clauses))))


(as-where {:id 1})
;; => [:= :id 1]
(as-where {:status 2 :category 3})
;; => [:and [:= :status 2] [:= :category 3]]
```

But that seems like the sort of thing that would fit in really nicely as a helper, I think.

**Comment by seancorfield** [comment]
I think maybe `map->cond` is more indicative of the functionality since it'll get used as the condition (in a where clause).

I think `:where (sql/as-where data)` seems a bit odd (repeat of `where`).

Maybe just `condition`? So we'd have `:where (sql/condition data)` or perhaps that's too verbose.

**Comment by corasaurus-hex** [comment]
I feel like map->cond is better, but if we're going with condition it would be nice if it included something about equality, that it's making it an :and :=

**Comment by seancorfield** [comment]
`map->:and:=` 😄 `map->and=`

What about `map=` ? So we'd have `... :where (map= data) ...` or `(-> ... (h/where (map= data)) ... )`

**Comment by corasaurus-hex** [comment]
I like `map=`! it's slick and brief and contains the core of what the function does
