### ISSUE TITLE
Register a clause using existing formatter

### ISSUE THREAD

**Issue by shay-rf** [jkk/honeysql#380]
When I try to register a new clause via:
(sql/register-clause! :qualify :having :window )

It raises an exception "The formatter must be a function or existing clause"
Since (fn?  #'honey.sql/format-on-expr )  returns false

**Comment by seancorfield** [comment]
This also affects `register-fn!`.

**Comment by seancorfield** [comment]
Available to test on **develop**.

**Comment by shay-rf** [comment]
Thanks! a short followup question -
Now that I have :qualify registered, is there a way for a user to setup a helper function somehow? I mean, I can just assoc - but I wonder if there is a way to get the other ergonomics from the helper of the original clause I mimic. 

For example:
(-> (h/select :*) (h/from :foo) (h/where [:= :a "a"]) (my-qualify [...] )

**Comment by seancorfield** [comment]
There isn't anything _public_ right now, but you could do:

```clojure
(defn my-qualifiy [& args]
  (#'honey.sql.helpers/generic :qualify args))
```

Most helper functions look like that, or else use `generic-1` for clauses that don't "merge", such as `update`, `delete`, `truncate` (`generic-1` does an `assoc` inserting an empty map if the first argument is not a map).

I could make those public (with better names) and document them -- open a new issue if you think that's worthwhile.
