### ISSUE TITLE
Allow creating helper functions for user registered clauses

### ISSUE THREAD

**Issue by shay-rf** [jkk/honeysql#381]
As per https://github.com/seancorfield/honeysql/issues/380 :
Once a clause has been registered to mimic existing clause, the usage of that clause is foreign to the surrounding code.

It would be nice if the ergonomics of the existing helpers can be exposed and made public to allow reuse.

Example:
(sql/register-clause! :qualify :having :window )
Usage:
(-> (h/select :*) (h/from :foo) (h/where [:= :a "a"]) (my-qualify [...] )

**Comment by seancorfield** [comment]
I definitely would not want `register-clause!` or `register-fn!` to automatically create a helper in the calling namespace (I don't think that's what you're suggesting but I want to clarify that this should be explicit).

Possibilities include:
* exposing versions of `generic` and `generic-1` with better names as public functions in `honey.sql.helpers`
* providing machinery in `honey.sql` to define such helpers (via a macro -- which would be the first and only macro in HoneySQL)
* simply documenting the private `generic` and `generic-1` functions as a way to do this

(implied in #1 and #2: document the new functions/machinery)

**Comment by shay-rf** [comment]
For me, option 1 sounds proper - to allow users to participate in the helpers arena. And a bit more telling names for the public functions would assist with that. 
A macro would be fine too.
