### ISSUE TITLE
Add support for CREATE FUNCTION syntax (ANSI, BigQuery)

### ISSUE THREAD

**Issue by shay-rf** [jkk/honeysql#383]
The first, which is a smaller issue - is how can I express a function creation:
For example:
CREATE FUNCTION my_dataset.multiply_by_three(x INT64) AS (x * 3);
Or:
CREATE `other-project`.other_dataset.other_function(x INT64, y INT64) AS (x * y * 2);
Or:
CREATE TEMP FUNCTION AddFourAndDivide(x INT64, y INT64)
  RETURNS FLOAT64
  AS ((x + 4) / y);
https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#calling_persistent_user-defined_functions_udfs
https://cloud.google.com/bigquery/docs/reference/standard-sql/user-defined-functions

But the main issue, is how to express a calling for such function?
I guess that it would be either [:other-project.other_dataset.other_function 1 2] or something like [:fn :other-project.other_dataset.other_function 1 2]
Also, the [:%other-project.other_dataset.other_function 1 2] didnt work for me.

Is there a way to express such UDF call?

**Comment by shay-rf** [comment]
To provide more examples of the issue:
(h/select [[:my.your.fn 1 3] :aa])
=> SELECT MY.YOUR.DDD(1, 3) AS `aa`
Change the names into capital

(h/select [[:my-proj.your.fn 1 3] :aa])
=> SELECT MY PROJ.YOUR.FN(1, 3) AS `aa`
Also Introduces a space in the project name

**Comment by seancorfield** [comment]
Is BigQuery case-sensitive? SQL is not supposed to be case-sensitive so uppercase function names should not be a problem (but some dialects are, weirdly, case-sensitive for user-defined names). As for the `-` to space transform, yes, that's required for a lot of (SQL) constructs that are function-like but are multiple words. See #352 for more discussion on the naming transforms.

The `%` call format is intended to include the arguments (and they are treated as inline literals) so `:%other-project.other_dataset.other_funct.1.1` would be close to what you want (modulo uppercasing and `-` to space transforms).

Your other option is using `:raw` for function calls that can't be handled just with vectors.

As for `CREATE` on functions, I don't know what ANSI syntax is for that but HoneySQL doesn't support any form of that _yet_. I'll keep this open as a placeholder.

**Comment by shay-rf** [comment]
The SQL itself is not case-sensitive - such as the UDF function name itself. But the fully qualified name prefix is. So, the name of the project must be all lowercase and the dash is part of its name. Same for dataset.
Basically, the same name handling as done for "from" clause applies here. So if a table fully qualified name is :
:my-proj.my_dataset.my-table => resolved into : `my-proj`.`my_dataset`.`my-table` 

The same thing needs to apply to the name of the UDF function. The function itself might get uppercase but not its namespace : `my-proj`.`my_dataset`.MYFUNC

Is there a convenient way to work with wrapping :raw ? If the wrapping UDF is handled as :raw, how to process the arguments? They need to be resolved early into the final string to be wrapped in a :raw

BTW, my current workaround was not to use a stored function at the project/dataset level. But to prepare the complete query using just the function name, into a string, and then prepend a hardcoded string of the TEMP function definition, before executing the query.

**Comment by seancorfield** [comment]
There's no easy way to do this with HoneySQL at the moment. I'll have to give it some thought. As noted in #352 changing how vectors-as-functions are treated would likely break all sorts of stuff for other situations so some specific new syntax may need to be added for this sort of thing.

**Comment by seancorfield** [comment]
@shay-rf I'm going to treat this as two separate tickets:

* #352 will tackle the case-sensitive/`-` transform aspect of the function _call_,
* #383 (this ticket) will tackle the `CREATE FUNCTION` aspect.

I'm going to update the title of this ticket to reflect that.

**Comment by seancorfield** [comment]
**develop** has addressed #352 so now you can have:

```clojure
dev=> (sql/format (h/select [[:my.your.fn 1 3] :aa]))
["SELECT MY.YOUR.FN(?, ?) AS aa" 1 3]
dev=> (sql/format (h/select [[:'my.your.fn 1 3] :aa]))
["SELECT my.your.fn(?, ?) AS aa" 1 3]
dev=> (sql/format (h/select [[:my-proj.your.fn 1 3] :aa]))
["SELECT MY PROJ.YOUR.FN(?, ?) AS aa" 1 3]
dev=> (sql/format (h/select [[:'my-proj.your.fn 1 3] :aa]))
["SELECT my-proj.your.fn(?, ?) AS aa" 1 3]
```

**Comment by seancorfield** [comment]
The `CREATE FUNCTION` syntax is too wildly variable to be supported in any meaningful way:
* https://www.ibm.com/docs/en/informix-servers/12.10?topic=statements-create-function-from-statement
* https://docs.teradata.com/r/Teradata-Database-SQL-Data-Definition-Language-Syntax-and-Examples/September-2015/User-Defined-Function-Statements/CREATE-FUNCTION-SQL-Form-and-REPLACE-FUNCTION-SQL-Form
* https://docs.microsoft.com/en-us/sql/t-sql/statements/create-function-transact-sql?view=sql-server-ver15
* https://www.tutorialscan.com/sql/create-function-sql/
* https://www.educba.com/mysql-create-function/
* https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_5009.htm
* https://www.postgresql.org/docs/current/sql-createfunction.html

**Comment by shay-rf** [comment]
Thanks!
The only issue that blocks me from using the fully qualified name function call is the dash.
BQ will not accept:
SELECT my-proj.your.fn(1, 2) AS aa

It expects the quoting form like "from":
SELECT `my-proj`.`your`.fn(1, 2) AS aa

**Comment by seancorfield** [comment]
Ah, GitHub is munging your examples because you're not putting code in triple-backtick blocks.

Functions are never normally split/quoted but I can modify the new `:'` behavior to support that I suspect -- you'll have to be explicit with a dialect or quoting option.

**Comment by shay-rf** [comment]
I always run in the context of 
```
(h/format form :inline true :dialect :mysql)
```

So, the "from" clause fully qualified table name is resolved to something like
```
`my-proj`.`my_dataset`.`my-table`
```

**Comment by seancorfield** [comment]
OK, I'm updating it so this is the behavior for `:'`:

```clojure
(-> (select :*) (from :foo)
    (where [:'my-schema.SomeFunction :bar 0])
    (sql/format))
=> ["SELECT * FROM foo WHERE my_schema.SomeFunction(bar, ?)" 0]
(-> (select :*) (from :foo)
    (where [:'my-schema.SomeFunction :bar 0])
    (sql/format :quoted true))
=> ["SELECT * FROM \"foo\" WHERE \"my-schema\".\"SomeFunction\"(\"bar\", ?)" 0]
(-> (select :*) (from :foo)
    (where [:'my-schema.SomeFunction :bar 0])
    (sql/format :dialect :mysql))
=> ["SELECT * FROM `foo` WHERE `my-schema`.`SomeFunction`(`bar`, ?)" 0]
```

**develop** is updated to reflect this -- please try again.

**Comment by shay-rf** [comment]
Works perfectly :)
