### ISSUE TITLE
Support ONLY keyword (Inheritance)

### ISSUE THREAD

**Issue by rafaeldelboni** [jkk/honeysql#389]
Hey we are using postgresql's [Inheritance](https://www.postgresql.org/docs/14/ddl-inherit.html) and we need to extend honey to add the keyword ONLY to make selects like `SELECT * FROM ONLY table_name` needed to get data from the top level of the tables that have Inheritance.

This is what we did currently:
```clojure
(def format-selects-common #'sql/format-selects-common)

(defn- format-selects [k xs]
  (format-selects-common
   (sql/sql-kw k)
   'from
   xs))

(sql/register-clause! :from-only format-selects :from)

(sql/format {:select [:*], :from-only [[:table :t]]})
```
ps: The example is not complete, since you can add `ONLY` in the front of the table name and use in `JOIN`s as well
for example:
```sql
select * from ONLY countries join ONLY capitals on countries.id = capitals.country_id;
```

Docs:
[SQL SELECT / ONLY and Inheritance](https://www.postgresql.org/docs/14/sql-select.html#id-1.9.3.171.10.6)
[DDL Inheritance](https://www.postgresql.org/docs/14/ddl-inherit.html)
[Some usage example](https://rextester.com/BMCB94324)

**Comment by seancorfield** [comment]
I realized you do not need any extensions for this. Although PostgreSQL considers them optional, the ANSI SQL syntax is more function-like:

```clojure
  (sql/format {:select [:*], :from [[[:only :table] :t]]})
;;=> ["SELECT * FROM ONLY(table) AS t"]
  (sql/format {:select [:*]
               :from [[[:only :countries]]]
               :join [[[:only :capitals]] [:= :countries.id :capitals.country_id]]})
;;=> ["SELECT * FROM ONLY(countries) INNER JOIN ONLY(capitals) ON countries.id = capitals.country_id"]
```

That should work out of the box with PG.

I'll add some notes to the appropriate clauses.
