### ISSUE TITLE
with materialized cte

### ISSUE THREAD

**Issue by seancorfield** [jkk/honeysql#392]
### Discussed in https://github.com/seancorfield/honeysql/discussions/391

<div type='discussions-op-text'>

<sup>Originally posted by **k3nj1g** March  1, 2022</sup>
Can you help with register clause for materialized cte? For query like:

```
WITH foo AS MATERIALIZED (
  SELECT foo 
  FROM bar
)
```
</div>

See discussion for whether this should be a specialized `:with-materialized` or whether this should be the start of adding metadata support to provide hints on various clauses.

**Comment by robhanlon22** [comment]
Interested in helping out here! It would be nice to support `AS NOT MATERIALIZED` as well. I would be partial to adding `:with-materialized` and `:with-not-materialized` given that programmatically working with metadata adds more overhead both cognitively and logically, i.e. it's not as easy to use simple map operations for transformations/merging/etc.

**Comment by robhanlon22** [comment]
I thought about this a bit more and I realized a limitation of introducing `:with-materialized` and `:with-not-materialized` (and also `:with-recursive`) is that it's not possible to freely mix all three types together because SQL only supports a single `WITH` clause per (sub)query. 

An alternative to using metadata could be providing a third "argument" within the `:with` vector:

```clojure
;; set of behaviors

(with [:foo (-> (select :*) (from :bars)) #{:recursive :materialized}]) 

;; or an options map

(with [:foo (-> (select :*) (from :bars)) {:recursive? true :materialized? true}])
```

**Comment by seancorfield** [comment]
I haven't yet taken the time to dig into the grammar for `WITH` to see just what syntax is possible but I believe it can have multiple parts -- which HoneySQL already supports -- so it's not clear to me (yet) how best to approach this ticket.

**Comment by robhanlon22** [comment]
Did a bit of digging:
- WITH and WITH RECURSIVE are different clauses, i.e. RECURSIVE is not a modifier to the CTE.
- AS MATERIALIZED and AS NOT MATERIALIZED can be specified on a CTE-to-CTE basis within a single WITH.
