### ISSUE TITLE
oracle does not support `tablename as a` syntax

### ISSUE THREAD

**Issue by cmal** [jkk/honeysql#395]
`select a.name from tablename as a where rownum < 2` throws `ORA-00933` whereas `select a.name from tablename a where rownum < 2` works.

**Comment by seancorfield** [comment]
Have you specified `:dialect :oracle`?

**Comment by seancorfield** [comment]
See https://john.shaffe.rs/honeysql/?q=%7B%3Aselect%20%3A*%20%3Afrom%20%5B%5B%3Atable%20%3At%5D%5D%20%3Awhere%20%5B%3A%3C%20%3Aid%20100%5D%7D%20&opt=%7B%3Adialect%20%3Aoracle%20%3Aquoted%20false%7D%20 for example.
