### ISSUE TITLE
Can we have left-outer-join clause?

### ISSUE THREAD

**Issue by cmal** [jkk/honeysql#397]
Can we have left-outer-join clause?

**Comment by seancorfield** [comment]
Why? What item does that solve that you can't already do with the existing join clauses that are supported?

**Comment by seancorfield** [comment]
Just to note, `:left-join` produces `LEFT JOIN` which in SQL is equivalent to `LEFT OUTER JOIN` -- `OUTER` is optional in the left and right joins, and `FULL` is optional in the (full) outer join.

Plain old `JOIN` is equivalent to `INNER JOIN` and that's the only case where HoneySQL supports an alias: `:join` is treated as if it were `:inner-join`.

I don't see much point in adding longer clause names for these joins (and with `:join-by` it supports even shorter names to avoid duplicating the word `join` everywhere). You can try to convince me that there's value in supporting the following longer clause names as aliases but I'm going to close this out as invalid for now:
* `:left-outer-join` -- alias for `:left-join`
* `:right-outer-join` -- alias for `:right-join`
* `:full-outer-join` -- alias for `:outer-join`
