### ISSUE TITLE
Doc Check Breaks Compiler Option

### ISSUE THREAD

**Issue by dfrugg** [jkk/honeysql#409]
https://github.com/seancorfield/honeysql/blob/2e9b395b31373d5265dab5153f300ea095349553/src/honey/sql/helpers.cljc#L1029

Attempting to use the compiler option -Dclojure.compiler.elide-meta=[:doc] , but compilation fails with that option if honeysql is in the application.  It looks like it is due to some code that ensures all public functions have doc strings.

**Comment by seancorfield** [comment]
I think you are the first person I've run across who uses that option to elide docs in production but I will figure out how to make that check conditional (I'll probably check a known Var for `:doc` metadata and only do the `assert` if that is present, which should omit the check for folks like you).

**Comment by dfrugg** [comment]
It's probably a rare edge case.  I'm really just playing with compiler options to see results in size and performance, but thought it was interesting that it failed.  I like the idea of asserting there are docs on public functions.  Wonder if it would work as a unit test:

```clojure
(deftest issue-295-ensure-docs-on-public-functions
  (testing "Testing to ensure that all public functions in the helper namespace has docs"
    (is (empty? (->> (ns-publics honey.sql.helpers) (vals) (c/filter (comp not :doc meta)))))))
```

**Comment by seancorfield** [comment]
You can try it out via git deps or https://clojars.org/com.github.seancorfield/honeysql/versions/2.3.999-SNAPSHOT

**Comment by dfrugg** [comment]
Worked like a charm.  Thank you.
