### ISSUE TITLE
Anything to convert the raw sql to honeysql data structure?

### ISSUE THREAD

**Issue by raghavio** [jkk/honeysql#411]
Hello. I was wondering if there's any tool that could parse raw sql to honeysql data structures.

**Comment by seancorfield** [comment]
Not that I know of. Similar questions have been asked several times before but the problem is a hard one: you would need a full SQL parser to do this and SQL is a very complex language with a lot of vendor-specific variations.

**Comment by namenu** [comment]
Here's my crumpy trial -> https://github.com/namenu/yenoh ([demo](https://namenu.github.io/yenoh/))

It can only parse a very tiny portion of the SQL syntax.
I have to stop implementing further because of MySQL's ill-defined, complex spec..
