### ISSUE TITLE
add-column / drop-column for multiple fields

### ISSUE THREAD

**Issue by kwrooijen** [jkk/honeysql#415]
(postgres specific?)

It's currently not possible to add / drop multiple columns using honeysql

```clj
(-> (honey.sql.helpers/alter-table :account)
    (honey.sql.helpers/drop-column [:name :email])
    (honey.sql/format))

;; => ["ALTER TABLE account DROP COLUMN name, email"]

(-> (honey.sql.helpers/alter-table :account)
    (honey.sql.helpers/drop-column :name)
    (honey.sql.helpers/drop-column :email)
    (honey.sql/format))

;; => ["ALTER TABLE account DROP COLUMN email"]

```

## Expected
```clj
["ALTER TABLE account DROP COLUMN name, DROP COLUMN email"]
```

## HoneySQL Version 1

```clj
(defmethod format-clause :drop-column* [[_ fields] _]
  (->> fields
       (map #(str "DROP COLUMN " (honeysql.format/to-sql %)))
       (string/join ",\n")))
```

**Comment by seancorfield** [comment]
I checked on some other databases -- including my "home" MySQL -- and, yeah, HoneySQL's behavior here is just wrong.

**Comment by seancorfield** [comment]
This looks reasonably straightforward for drop but hard for add -- I'll have to give this some thought...

**Comment by seancorfield** [comment]
It's not even straightforward for drop since you can optionally have `:if-exists` as a guard -- and there's currently no way to provide that "per item" without making the drop formatting substantially more complex and hard to document. Not discounting it -- just need to think harder about it.

**Comment by seancorfield** [comment]
Multiple columns are now supported in `:drop-column`. I'm still thinking about how to support this for alter/modify/add column without breaking anything...
