### ISSUE TITLE
`sqlize-value` does not SQLize Dates, Instants, etc. correctly

### ISSUE THREAD

**Issue by robhanlon22** [jkk/honeysql#419]
Since `sqlize-value` falls back to `str` when the type is not specially handled, some things that need to be quoted aren't:

```clojure
(format (-> (select :*) 
            (from :foo) 
            (where [:= :t (java.time.Instant/parse "2020-04-03T00:00:00.00Z")])) 
        {:inline true})

;; => ["SELECT * FROM foo WHERE t = 2020-04-03T00:00:00Z"]
```

I see that there's a special case for `java.util.UUID`s but it does seem like adding special cases could quickly get unwieldy. Would it be excessive to introduce a protocol that allows for extension of `sqlize-value`? Otherwise adding fixes will quickly become a game of Whac-A-Mole 😆

**Comment by seancorfield** [comment]
Yeah, at this point it probably makes sense to turn that into an extension point.
