### ISSUE TITLE
how can I generate `replace into table` valeus use honeysql with mysql8

### ISSUE THREAD

**Issue by imxingquan** [jkk/honeysql#421]
https://dev.mysql.com/doc/refman/8.0/en/replace.html
REPLACE INTO tableName
the old row is deleted before the new row is inserted

**Comment by seancorfield** [comment]
I'll add `:replace-into` under the `:mysql` dialect as an "alias" for `:insert-into` (since it has the same syntax) so it will produced `REPLACE INTO` instead of `INSERT INTO`.
