### ISSUE TITLE
Support `INSERT INTO table DEFAULT VALUES` syntax

### ISSUE THREAD

**Issue by camsaul** [jkk/honeysql#423]
It's not completely out of the ordinary to have a table with something like

```sql
CREATE TABLE birds (
  id serial PRIMARY KEY NOT NULL,
  name text,
  bird_type text NOT NULL DEFAULT 'toucan'
);
```

where all `NOT NULL` columns either have an auto-generated value or a default value.

Suppose you want to insert a row into that table without specifying any values. H2 supports the syntax

```sql
INSERT INTO table () VALUES ();
```

but Postgres fails with an error like

```
ERROR:  syntax error at or near ")"
LINE 1: INSERT INTO birds () VALUES ();
```

when you use that statement. Postgres, however, does support

```sql
INSERT INTO table DEFAULT VALUES;
```

which does what we want. H2 supports this syntax as well; I haven't tested any other databases yet.

```clj
(honey.sql/format {:insert-into [:birds], :values [{}]})
;; => ["INSERT INTO birds () VALUES ()"]
```

can be used to generate the H2-compatible version.

I was able to work around this by registering a custom clause like

```clj
(honey.sql/register-clause!
 ::default-values
 (fn [_clause _value]
   ["DEFAULT VALUES"])
 nil)

(honey.sql/format {:insert-into [:birds], ::default-values true})
;; => ["INSERT INTO birds DEFAULT VALUES"]
```

but I find the syntax a little icky. Something like 

```clj
{:insert-into [:birds], :values :default}
```

or maybe

```clj
{:insert-into [:birds], :values []}
```

generate that would be nice -- is there any interest in extending the existing formatter for `:values` to support that?

**Comment by seancorfield** [comment]
Does PostgreSQL and/or H2 have a syntax for inserting multiple rows where some rows are default-valued and some are specified completely?

See https://github.com/seancorfield/honeysql/blob/develop/test/honey/sql_test.cljc#L159-L179 for examples of multi-row inserts.

**Comment by camsaul** [comment]
@seancorfield Postgres and H2 supports the default keyword to tell it to use the default value for a specific column:

```sql
-- postgres or H2
INSERT INTO birds (name) VALUES ('toucan'), (DEFAULT);
```

In H2, you can use `DEFAULT` for an entire row, like this:

```sql
-- h2 only
INSERT INTO birds (name) VALUES ('toucan'), DEFAULT;
```

but that doesn't work in Postgres and as far as I know there is no native equivalent.

**Comment by seancorfield** [comment]
And I just confirmed that MySQL (and possibly others) does not support `DEFAULT VALUES`. I had a feeling it wouldn't be very portable and couldn't be easily synthesized across dialects.

What I'm going to do:
* if `:values` has a single value of `:default`, it will generate `DEFAULT VALUES`
* if `:values` has a **row** value of `:default`, it will generate `DEFAULT` for that whole row (the H2 case above)
* if `:values` has a **column** value of `:default`, it will generate `DEFAULT` just for that column (it currently supports this but produces `default`, not that case really matters but it is formatted as a column name rather than a SQL entity)

**Comment by seancorfield** [comment]
To avoid ambiguity with a _column_ named `default`, the third case has to use `[:default]` (which already works).

**Comment by seancorfield** [comment]
Added documentation to `values` clause.
