### ISSUE TITLE
`:interval` formatter returns invalid Postgres SQL

### ISSUE THREAD

**Issue by robhanlon22** [jkk/honeysql#425]
`(sql/format-expr [:interval 30 :days])` is returning `INTERVAL 30 DAYS`, which is not valid Postgres SQL:

```
# SELECT (INTERVAL 30 DAYS);
ERROR:  syntax error at or near "30"
LINE 1: SELECT (INTERVAL 30 DAYS);
```

It should instead return `INTERVAL '30 DAYS'`:

```
# SELECT (INTERVAL '30 DAYS');
 interval
----------
 30 days
(1 row)
```

Not sure if this applies to other SQL dialects.

**Comment by seancorfield** [comment]
That's definitely dialect-specific. In MySQL, it's `INTERVAL 30 DAY` (no quotes, strictly singular). I'll have to do some research on what different databases do with `INTERVAL`.

**Comment by seancorfield** [comment]
PostgreSQL seems to be using the `INTERVAL 'string'` syntax where the `'string'` is a general specification of an interval. Currently, HoneySQL does not allow a string there. I think my preferred approach here would be to "just" fix the issue of HoneySQL not accepting a string there so you can specify an arbitrary string.

Could you confirm that the following SQL works in PostgreSQL (as a call to `next.jdbc`):

```
(jdbc/execute! ds ["select (interval ?)" "30 days"])
```

This is essentially what HoneySQL would allow/generate with this fix.

**Comment by robhanlon22** [comment]
After doing a bit of testing it looks like Postgres doesn't allow prepared statement syntax with intervals! Interesting. I think the best approach that one can take is `[:cast "30 days" :interval]`, which is what I've been doing as (what I thought was) a workaround. This might be a nice thing to document. Side note, it looks like intervals are not a data type in MySQL, just a syntactic construct, whereas they're types in Postgres.

**Comment by seancorfield** [comment]
Thanks for checking on that @robhanlon22 -- I'll turn this into a documentation issue and make a note of it in both the PG tips & tricks and under the `:interval` syntax itself. There should be no problem using `:interval` as a data type in DDL since it will be treated as a SQL keyword in that context.
