### ISSUE TITLE
How can I put a specifix syntax between select and columns?

### ISSUE THREAD

**Issue by SongKJ00** [jkk/honeysql#426]
I'm trying to register [MySQL optimizer hints ](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html) by referring to [Extending HoneySQL](https://github.com/seancorfield/honeysql/blob/develop/doc/extending-honeysql.md).

According to the [MySQL reference manual](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html), the optimizer hints should be placed between the select statement and the columns because it is treated as a comment.
e.g.,
```mysql
SELECT /*+ INDEX_MERGE(t1 i_a, i_b, i_c)*/ * FROM t1
  WHERE a = 1 AND b = 2 AND c = 3 AND d = 4;
```

I couldn't find a way to put a specific syntax(optimizer hints) between select and columns in [Extending HoneySQL](https://github.com/seancorfield/honeysql/blob/develop/doc/extending-honeysql.md).
Are there any ways to implement this feature in HoneySQL v2?

**Comment by seancorfield** [comment]
The best you're going to be able to do is use `:raw` to provide that sort of stuff (including the column selection). This is far too database-specific for me to want to support it in HoneySQL in any other way.
