### ISSUE TITLE
Add a way to set the checking mode globally

### ISSUE THREAD

**Issue by maxrothman** [jkk/honeysql#427]
[`set-dialect!`](https://cljdoc.org/d/com.github.seancorfield/honeysql/2.3.928/api/honey.sql#set-dialect!) allows dialect and quoting options to be set globally, but other options like `:checking` cannot be set globally. It would be nice if at least `:checking`, but possibly other [options](https://cljdoc.org/d/com.github.seancorfield/honeysql/2.3.928/doc/all-the-options#format-options) could also be set globally.

**Comment by seancorfield** [comment]
I've added `set-options!`, which can set defaults for `:checking`, `:inline`, `:quoted`, and `:quoted-snake`.

I need to think about how/where exactly it needs documenting (beyond just the docstring) so I'll keep this issue open until I've completed that work. Feel free to try out the latest **develop** version or the latest SNAPSHOT on Clojars and provide feedback.

**Comment by seancorfield** [comment]
Looks like I messed that up a bit and now quoting is on by default. Will fix shortly.

**Comment by seancorfield** [comment]
Fixed: https://clojars.org/com.github.seancorfield/honeysql/versions/2.3.999-SNAPSHOT

**Comment by maxrothman** [comment]
Wow, that was a fast turnaround! I’ll see about getting our usage upgraded and trying this out.
