### ISSUE TITLE
UPDATE with INNER JOIN in wrong order

### ISSUE THREAD

**Issue by irigarae** [jkk/honeysql#429]
Hi,

I tried doing a join on an update with the latest version `com.github.seancorfield/honeysql {:mvn/version "2.3.911"}`

```clojure
(-> {:update [:table_a]
     :inner-join [[:table_b]
                  [:= :table_a.id :table_b.id]]
     :set {:table_b.field 1}}
    (honey.sql/format))
;; => ["UPDATE table_a SET table_b.field = ? INNER JOIN table_b ON table_a.id = table_b.id" 1]
```

and the order is not as I would expect. Is there a way to have INNER JOIN before SET (maybe using something like `:join-by`), or maybe it's a bug?

I would have expected

```clojure
["UPDATE table_a INNER JOIN table_b ON table_a.id = table_b.id SET table_b.field = ?" 1]
```

Thanks

**Comment by seancorfield** [comment]
Are you on MySQL? Did you select `:dialect :mysql`? MySQL has a non-standard precedence for `SET` compared to all the other databases so the `:mysql` dialect changes the order of the `:set` clause.

**Comment by irigarae** [comment]
Yes, I’m on MySQL, but no, I did not set up the dialect. Indeed, that was it. Thank you!
