### ISSUE TITLE
Allow `with expr AS ident` syntax in WITH clause

### ISSUE THREAD

**Issue by MawiraIke** [jkk/honeysql#433]
As discussed in #428 , the expression passed to `WITH` clause in ClickHouse can be a string, which is not currently supported. When the expression is a string, the order of `WITH` clause is `with expr AS ident` and not the current `with ident AS expr`.
I have created a [PR](https://github.com/seancorfield/honeysql/pull/432) that will allow for both variants of ClickHouse i.e
`with expr AS ident` and `with ident AS subquery-expr`

**Comment by seancorfield** [comment]
Note: I'm going to leave this open until I've wordsmithed the docs a bit and updated the CHANGELOG. Thank you for the PR!
