### ISSUE TITLE
Support full TRUNCATE syntax (cascade, identity)

### ISSUE THREAD

**Issue by maxrothman** [jkk/honeysql#438]
Postgres’ TRUNCATE command supports two additional options that are not supported in HoneySQL: CASCADE/RESTRICT, and RESTART IDENTITY/CONTINUE IDENTITY. It’d be great to have them supported!

Doc link: https://www.postgresql.org/docs/current/sql-truncate.html

**Comment by kolstae** [comment]
Also the ability to truncate multiple tables would be great.

**Comment by seancorfield** [comment]
`:truncate` now accepts either a table name or a sequence with a table name followed by options that should work for all the various database-specific syntax allowed here. It does not allow for truncating multiple tables (I do not plan to support that).
