### ISSUE TITLE
First call to format with :dialect may fail

### ISSUE THREAD

**Issue by valerauko** [jkk/honeysql#441]
```
user=> (honey.sql/format
  {:replace-into :accounts
   :values [{:public-key 1 :private-key 2}]
   :returning [:*]})
ExceptionInfo These SQL clauses are unknown or have nil values: :replace-into {:replace-into :accounts}
user=> (honey.sql/format
  {:replace-into :accounts
   :values [{:public-key 1 :private-key 2}]
   :returning [:*]}
  {:dialect :mysql
   :quoted-kebab true})
ExceptionInfo These SQL clauses are unknown or have nil values: :replace-into {:replace-into :accounts}
```
Then from the next call on it'd succeed.
```
user=> (honey.sql/format
  {:replace-into :accounts
   :values [{:public-key 1 :private-key 2}]
   :returning [:*]}
  {:dialect :mysql
   :quoted-kebab true})
["REPLACE INTO `accounts` (`public-key`, `private-key`) VALUES (?, ?) RETURNING *" 1 2]
user=> (honey.sql/format
  {:replace-into :accounts
   :values [{:public-key 1 :private-key 2}]
   :returning [:*]})
["REPLACE INTO accounts (public_key, private_key) VALUES (?, ?) RETURNING *" 1 2]
```

https://github.com/seancorfield/honeysql/blob/23be700b7eb74ff75096bc5c8324634a8e2b9e84/src/honey/sql.cljc#L107-L110

Maybe the :clause-order-fn is called at the wrong time and/or the clause dictionary is deref'd before it so it's not updated for the first call?

## Workaround

* using set-dialect! before any format calls
* not using :mysql

**Comment by seancorfield** [comment]
Your deduction of the bug is spot on: the argument to `:clause-order-fn` is the base clause order so it has already been derefed and passed in before `register-clause!` does its thing.

**Comment by valerauko** [comment]
Thanks for the blazing fast fix! <3

**Comment by seancorfield** [comment]
Let me know if it actually solves the problem for you _without introducing any new problems_! There should be a new SNAPSHOT you can depend on from Clojars or you can test against git deps.

**Comment by valerauko** [comment]
I can confirm the first call to format with :dialect now works! (And I don't see anything breaking.) Thanks!
