### ISSUE TITLE
Differences from Honey SQL 1 dox should mention things like `:desc-nulls-last` (2.x) vs `:desc :nulls-last` (1.x) in `:order-by`

### ISSUE THREAD

**Issue by camsaul** [jkk/honeysql#449]
In Honey SQL 1 if you wanted `ORDER BY ... DESC NULLS LAST` you would do something like

```clj
{:order-by [[:my-column :desc :nulls-last]]}
```

(two separate keywords)

In Honey SQL 2 this is 

```clj
{:order-by [[:my-column :desc-nulls-last]]}
```

This tripped me up when converting some old code that used Honey SQL 1 today -- it would be good to mention this in the "Differences from Honey SQL 1" documentation

**Comment by seancorfield** [comment]
Please submit a PR. I can't possibly know all the differences from 1.x since it was so poorly documented.
