### ISSUE TITLE
Is there any way to do `IN (...)` with columns inside the list? Should a `:list` primitive be available?

### ISSUE THREAD

**Issue by camsaul** [jkk/honeysql#450]
I ran into this today while porting some Honey SQL 1 code to Honey SQL 2.

The old code had a query did something along the lines of 

```clj
{:select [:t1]
 :left-join [:t2
             [:= :t1.id :t2.id]
             :t3
             [:in :t3.id [:t1.id :t2.id]]]}
```

In Honey SQL 1, this compiled to

```sql
SELECT t1 
LEFT JOIN t2
  ON t1.id = t2.id 
LEFT JOIN t3 
  ON (t3.id in (t1.id, t2.id))
```

However, in Honey SQL 2, it compiles to:

```sql
SELECT "t1"
LEFT JOIN "t2" 
  ON "t1"."id" = "t2"."id" 
LEFT JOIN "t3" 
  ON "t3"."id" IN T1.ID("t2"."id")
```

I understand why -- because it's interpreting `[:t1.id :t2.id]` as a function call -- but is there any way to get around this?

I assumed there would be some sort of `:list` used internally by `:in`, or maybe something like `[::parens [::commas ...]]`, so I could just change my query to something like `[:in :a [:list :t1.id :t2.id]]` to get it to do what I wanted, but after digging thru the code I was a little surprised to find that nothing like this exists and it's all done manually everywhere this is needed. I counted 39 instances of `(str/join ", " ...)` in `honey.sql` -- does it make sense to refactor this a bit so there is less code duplication?

Here's an example of what I mean from an experimental SQL compilation library I was working on a while back. I implemented`:in` in terms of `::interpose`, `::parens`, and `::commas`:

https://github.com/camsaul/moneysql/blob/39e51a058c54ae3c5465fd4aa3f8e9e0706deecb/src/money/sql.clj#L236-L248

```clj
(defn interpose-sql-args [separator xs]
  (combine-sql-args xs
                    (comp
                     (remove empty?)
                     (clojure.core/interpose [separator]))))

(m/defmethod to-sql [::interpose :default]
  [[_ separator & xs] options]
  (interpose-sql-args separator (for [x xs]
                                  (to-sql x options))))

(defn interpose [separator xs]
  (into [::interpose separator] xs))
```

https://github.com/camsaul/moneysql/blob/39e51a058c54ae3c5465fd4aa3f8e9e0706deecb/src/money/sql.clj#L297-L312

```clj
(m/defmethod to-sql [::commas :default]
  [[_ & xs] options]
  (to-sql (interpose ", " xs)
          options))

(defn commas [xs]
  (into [::commas] xs))

(m/defmethod to-sql [::parens :default]
  [[_ x] options]
  (combine-sql-args [["("]
                     (to-sql x options)
                     [")"]]))

(defn parens [x]
  [::parens x])
```

https://github.com/camsaul/moneysql/blob/39e51a058c54ae3c5465fd4aa3f8e9e0706deecb/src/money/sql.clj#L398-L401

```clj
(m/defmethod to-sql [:in :default]
  [[_ x vs] options]
  (to-sql (interpose " IN " [x (parens (commas vs))]) options))
```

Would a PR to adopt a similar approach be welcome here?

Anyways, with regards to solving the `IN` problem: I ended up working around this by registering an `::identifier` function that ultimately calls `sql/format-entity`, so my code looks like

```clj
[:in :t3.id [[::identifier ::t1.id] [::identifier ::t2.id]]]
```

now. But I think `[:list ...]` would have been a lot easier and nicer to look at 🙃

**Comment by seancorfield** [comment]
Look at `:composite`?

**Comment by camsaul** [comment]
Oh wow, I'm sorry. I didn't realize that existed. 😬
