### ISSUE TITLE
`:union`/`:union-all` can fail if subqueries are not wrapped in parentheses

### ISSUE THREAD

**Issue by camsaul** [jkk/honeysql#451]
I believe this is a regression of #279. 

I have a query like

```clj
{:select [[:ids.id :id]]
 :from   [[{:union
            [{:select [[:dimension.human_readable_field_id :id]]
              :from   [[:dimension :dimension]]
              :where  [:and
                       [:= :dimension.field_id 1]
                       [:not= :dimension.human_readable_field_id nil]]
              :limit  1}
             {:select    [[:dest.id :id]]
              :from      [[:field :source]]
              :left-join [[:table :table] [:= :source.table_id :table.id] [:field :dest] [:= :dest.table_id :table.id]]
              :where     [:and
                          [:= :source.id 1]
                          [:in :source.semantic_type #{"type/PK"}]
                          [:in :dest.semantic_type #{"type/Name"}]]
              :limit     1}]}
           :ids]]
 :limit  1}
```

And that compiles to

```sql
SELECT
  "ids"."id" AS "id"
FROM
  (
    SELECT
      "dimension"."human_readable_field_id" AS "id"
    FROM
      "dimension" AS "dimension"
    WHERE
      ("dimension"."field_id" = ?)
      AND ("dimension"."human_readable_field_id" IS NOT NULL)
    LIMIT
      ?
    UNION
    SELECT
      "dest"."id" AS "id"
    FROM
      "field" AS "source"
      LEFT JOIN "table" AS "table" ON "source"."table_id" = "table"."id"
      LEFT JOIN "field" AS "dest" ON "dest"."table_id" = "table"."id"
    WHERE
      ("source"."id" = ?)
      AND ("source"."semantic_type" IN (?))
      AND ("dest"."semantic_type" IN (?))
    LIMIT
      ?
  ) AS "ids"
LIMIT
  ?
```

which fails in Postgres.

This is similar to the issue I ran into in #279 (which was against Honey SQL 0.9.5, and closed because it was fixed in 2.x).

I managed to work around it here, but the workaround was a little more difficult in Honey SQL 2. In Honey SQL 1 I just wrote a custom function called `:_parens` and wrapped my sub-expressions in `(hsql/call :_parens ...)` and called it a day.

In Honey SQL 2, you can't do something similar -- arbitrary functions don't work inside `:union`. (This is a similar issue to #402.)

I'm not entirely sure whether this is intentional behavior or not -- https://github.com/seancorfield/honeysql/issues/279#issuecomment-706485769  

> This won't get fixed in 1.0, but in 2.0 I am not treating the UNION sub-expressions as nested (so they get parenthesized)
> [...]
> I think this is correct in v2 so I'm going to close this out now.

seemed to suggest that the sub-expressions _should_ get parenthesized. But if this is actually intentional behavior after all, please feel free to close this issue.

I ultimately created a custom version of `:union` like so to get it to do what I want:

```clj
(defn- format-union [_clause exprs]
  (let [[sqls args] (sql/format-expr-list exprs)
        sql         (str/join " UNION " sqls)]
    (into [sql] args)))

(sql/register-clause! ::union format-union :union)
```

**Comment by seancorfield** [comment]
Please explain what you think this SQL should be for PG to accept it. It looks correct to me.

**Comment by camsaul** [comment]
The SQL I posted above doesn't work in Postgres. Postgres doesn't like `UNION`ing things that have a `LIMIT` unless they're wrapped in parens. It's the same issue as #279 🙃 

The working syntax for Postgres is 

```sql
SELECT
  "ids"."id" AS "id"
FROM
  (
    (
      SELECT
        "dimension"."human_readable_field_id" AS "id"
      FROM
        "dimension" AS "dimension"
      WHERE
        ("dimension"."field_id" = ?)
        AND ("dimension"."human_readable_field_id" IS NOT NULL)
      LIMIT
        ?
    )
    UNION
    (
      SELECT
        "dest"."id" AS "id"
      FROM
        "field" AS "source"
        LEFT JOIN "table" AS "table" ON "source"."table_id" = "table"."id"
        LEFT JOIN "field" AS "dest" ON "dest"."table_id" = "table"."id"
      WHERE
        ("source"."id" = ?)
        AND ("source"."semantic_type" IN (?))
        AND ("dest"."semantic_type" IN (?))
      LIMIT
        ?
    )
  ) AS "ids"
LIMIT
  ?
```

(the sub-expressions need to be wrapped in parens)

RE how to make this work: I'd be happy if there was an easy way to do this without having to create a custom `:union` expression type -- some way to explicitly wrap the sub-expressions in parens would do the trick. 

In #279 you wrote:

> Given the complexities here -- different SQL dialects having different rules about how parentheses around `union` clauses and their sub-clauses behave -- I think adding a way to explicitly wrap parens around a given construct is probably the right solution overall.
>
> At this point, I'm not sure I want to add that to 1.0 -- and you have a workaround -- but I will add this as a "special syntax" function in 2.0 to make everyone's life easier in future.

So I think you had originally planned on doing something like that for 2.x -- I just wanted to bring it to your attention so it didn't slip thru the cracks. If it still makes sense, I'd be happy to submit a PR for it

**Comment by seancorfield** [comment]
Okay, so I think `:nest` is what you want then?

**Comment by seancorfield** [comment]
```clojure
          (-> {:select [[:ids.id :id]]
               :from   [[{:union
                          [{:nest
                            {:select [[:dimension.human_readable_field_id :id]]
                             :from   [[:dimension :dimension]]
                             :where  [:and
                                      [:= :dimension.field_id 1]
                                      [:not= :dimension.human_readable_field_id nil]]
                             :limit  1}}
                           {:nest
                            {:select    [[:dest.id :id]]
                             :from      [[:field :source]]
                             :left-join [[:table :table] [:= :source.table_id :table.id] [:field :dest] [:= :dest.table_id :table.id]]
                             :where     [:and
                                         [:= :source.id 1]
                                         [:in :source.semantic_type #{"type/PK"}]
                                         [:in :dest.semantic_type #{"type/Name"}]]
                             :limit     1}}]}
                         :ids]]
               :limit  1}
              (sql/format))
```

That produces:

```
SELECT ids.id AS id FROM 
(
  (SELECT dimension.human_readable_field_id AS id FROM dimension AS dimension 
   WHERE (dimension.field_id = ?) AND (dimension.human_readable_field_id IS NOT NULL)
   LIMIT ?)
  UNION
  (SELECT dest.id AS id FROM field AS source
   LEFT JOIN table AS table ON source.table_id = table.id
   LEFT JOIN field AS dest ON dest.table_id = table.id
   WHERE (source.id = ?) AND (source.semantic_type IN (?)) AND (dest.semantic_type IN (?))
   LIMIT ?)
) AS ids 
LIMIT ?
```
