### ISSUE TITLE
Cannot create compound keys in table constraint with :unique

### ISSUE THREAD

**Issue by marrs** [jkk/honeysql#453]
I'm trying to create a unique constraint on a table across multiple columns by doing something like the following
```
{:create-table [:foo]
 :with-columns [[:a :integer]
                [:b :integer]
                [[:constraint :foo_natural_key] [:raw "UNIQUE (a, b)"]]
]}
```

I'd like to write the query without having to invoke the `:raw` operator.  I've tried `[:unique :a :b]`, `[:unique [:a :b]]`, and so on, but nothing seems to generate the correct code.  Is there something I'm missing or is it a limitation of Honey?

**Comment by seancorfield** [comment]
Does this help? https://github.com/seancorfield/honeysql/issues/445

Otherwise I'll look at this when I get back from vacation (next week).

**Comment by seancorfield** [comment]
I'm adding this example to the docs:

```clojure
user=> (-> {:create-table [:bar]
            :with-columns
            [[:a :integer]
             [:b :integer]
             [[:constraint :foo_natural_key] :unique [:composite :a :b]]]}
           (sql/format))
["CREATE TABLE bar (a INTEGER, b INTEGER, CONSTRAINT foo_natural_key UNIQUE (a, b))"]
```

**Comment by marrs** [comment]
Sorry for the delay in replying.  On the face of it, the docs look good.  I'll let you know if I have any issues using them to adjust my schemas.
