### ISSUE TITLE
Breaking change in `2.4.979` with variadic logical combinators

### ISSUE THREAD

**Issue by thenonameguy** [jkk/honeysql#461]
With the [variadic argument change](https://github.com/seancorfield/honeysql/issues/459), the logic operations in the form of `[:and true]` produce invalid sql in the form of:
```
WHERE AND true
```
vs. the valid previous output:
```
WHERE true
```

## Examples
[2.4.979 (bad)](https://john.shaffe.rs/honeysql/?q=%7B%3Aselect%20%5B%3Afoo%5D%0A%20%3Afrom%20%3Ax%0A%20%3Awhere%20%5B%3Aand%20true%5D%7D&opt=%7B%3Achecking%20%3Astrict%0A%20%3Aparams%20%7B%3Aparam1%20%22gabba%22%2C%20%3Aparam2%202%7D%0A%20%3Apretty%20true%7D)
[2.4.972 (good)](https://john.shaffe.rs/honeysql/v2.4.972/?q=%7B%3Aselect%20%5B%3Afoo%5D%0A%20%3Afrom%20%3Ax%0A%20%3Awhere%20%5B%3Aand%20true%5D%7D&opt=%7B%3Achecking%20%3Astrict%0A%20%3Aparams%20%7B%3Aparam1%20%22gabba%22%2C%20%3Aparam2%202%7D%0A%20%3Apretty%20true%7D)

This is a major regression, that sadly I only caught after mistakenly selecting the latest version of the 2.x release and ported the codebase from 1.x :disappointed: .

**Comment by seancorfield** [comment]
Sorry about that. At least you can fall back to 2.4.972 until I fix it.

It's a result of trying to support unary operators (which never worked properly before, I think) and there are some operators that just can't be used in that context -- so `[:and true]` worked "by accident" prior to this release:

```clojure
(~/clojure)-(!2001)-> clj -Sdeps '{:deps {com.github.seancorfield/honeysql {:mvn/version "2.4.972"}}}'
Downloading: com/github/seancorfield/honeysql/2.4.972/honeysql-2.4.972.pom from clojars
Downloading: com/github/seancorfield/honeysql/2.4.972/honeysql-2.4.972.jar from clojars
Clojure 1.11.1
user=> (require '[honey.sql :as sql])
nil
user=> (sql/format {:select :* :from :table :where [:and true]})
["SELECT * FROM table WHERE TRUE"]
user=> (sql/format {:select :* :from :table :where [:- 1]})
["SELECT * FROM table WHERE ?" 1]
user=>
```
☝️ unary `-` doesn't work (nor work any genuinely unary operators).

**Comment by seancorfield** [comment]
2.4.980 is available on Clojars and includes a fix for this.
