### ISSUE TITLE
Incorrect precedence with UNION, EXCEPT and INTERSECT

### ISSUE THREAD

**Issue by akedrou** [jkk/honeysql#462]
#365 removed parentheses from UNION queries, which breaks when set operators are combined:
```clojure
{:intersect [{:union [{:select [:m.title]
                       :from :m
                       :where [:= :m.author "me"]}
                      {:select [:b.title]
                       :from :b
                       :where [:= :b.author "me"]}]}
             {:union [{:select [:m.title]
                       :from :m
                       :where [:= :m.editor "me"]}
                      {:select [:b.title]
                       :from :b
                       :where [:= :b.editor "me"]}]}]}
```
yields
```sql
SELECT
  m.title
FROM m
WHERE m.author = ?
UNION
SELECT
  b.title
FROM b
WHERE b.author = ?
INTERSECT
SELECT
  m.title
FROM m
WHERE m.editor = ?
UNION
SELECT
  b.title
FROM b
WHERE b.editor = ?
```
instead of
```sql
(SELECT
   m.title
 FROM m
 WHERE m.author = ?
 UNION
 SELECT
   b.title
 FROM b
 WHERE b.author = ?)
INTERSECT
(SELECT
   m.title
 FROM m
 WHERE m.editor = ?
 UNION
 SELECT
   b.title
 FROM b
 WHERE b.editor = ?)
```
Obviously that change would break sqlite, but I assume that'd be expected from sqlite users nesting set operators, and the current state has pretty surprising behavior - I'd really not expect looking at the map that the result is to `INTERSECT` the second select in the first statement with the first select in the second statement and then `UNION`ing the result with the first and last (well, at least for Postgres, MySQL, and MSSQL - Oracle set operations are currently purely LTR, but the Oracle docs say that it will change `INTERSECT` to higher precedence to comply with the "emerging standard" in a "future release").

It seems just wrapping parentheses around nested set operations would be the best fix - it would mean that sqlite users would lose the ability to combine different set operations, but to me the misleading nature of nested maps (even if you're using sqlite) implying precedence makes breaking sqlite here the "better" option, but of course it's easy for me to say since I don't use it...

Maybe a general solution could be a `:combine` key that takes `[query setop query & setopquerys]`, then wrap parens around nested `:combine`?

**Comment by seancorfield** [comment]
You can use the `:nest` syntax to add explicit parens.

I'll give this some thought but I suspect the variance across databases might make this hard to solve genetically.

I'll add some notes to the docs for set ops to earn about this.
