### ISSUE TITLE
Review :dialect/:quoted docs -- ensure it's clear that :quoted nil is valid

### ISSUE THREAD

**Issue by seancorfield** [jkk/honeysql#463]
The docs may imply that `:quoted` has to be either `true` or `false` when you use `:dialect`. Make sure it's clear that you can also use `:quoted nil` to have the dialect with the default quoting strategy.

**Comment by nharsch** [comment]
@seancorfield working on a PR

**Comment by nharsch** [comment]
@seancorfield https://github.com/seancorfield/honeysql/pull/475/

**Comment by seancorfield** [comment]
Thank you!
