### ISSUE TITLE
Facilitate adding SQL keywords in between function arguments

### ISSUE THREAD

**Issue by p-himik** [jkk/honeysql#471]
Given the examples below, seems like having this ability would be quite useful, and perhaps not only for PostgreSQL.

Examples of PostgreSQL syntax from https://www.postgresql.org/docs/current/functions-string.html:
```sql
overlay ( string text PLACING newsubstring text FROM start integer [ FOR count integer ] ) → text
position ( substring text IN string text ) → integer
substring ( string text SIMILAR pattern text ESCAPE escape text ) → text
trim ( [ LEADING | TRAILING | BOTH ] [ characters text ] FROM string text ) → text
```

About SQL standard but also from PostgreSQL documentation at https://www.postgresql.org/docs/current/functions-matching.html#POSIX-VS-XQUERY:
```sql
TRANSLATE_REGEX(pattern IN string WITH replacement)
```

The `extract` PostgreSQL function documented [here](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT) accepts not only strings but also keywords to specify which fields to extract:
```sql
EXTRACT(CENTURY FROM TIMESTAMP '2000-12-16 12:21:13')
EXTRACT(MICROSECONDS FROM TIME '17:12:28.5')
```

The [`xmlelement` function](https://www.postgresql.org/docs/current/functions-xml.html#id-1.5.8.21.5.5):
```sql
xmlelement(name "foo$bar", xmlattributes('xyz' as "a&b"))
```

**Comment by seancorfield** [comment]
Some sort of generic `[:*extract-from_the :a :b :c]` => `a EXTRACT b FROM THE c` seems reasonable as a "general" special syntax. Not sure about how best to flag this (`:*` is already an operator so I'd prefer something more "unusual") and my thinking is "split at `-`" to delineate each part and then "replace `_` with space" to allow multi-word "operators" like `FROM TIME` etc?

**Comment by p-himik** [comment]
I think `[:overlay [:*placing-from-for :col "hi" 1 2]]` is really hard to read. Also, note that while `overlay` has an expression followed by a keyword, `trim` has it the other way around. While it is possible to use `[:overlay :col [:*placing-from-for "hi" 1 2]]` and `[:trim [:*both-from "x" "y"]]`, it doesn't make it easier on the eyes.

Feels like having a flag that means "inline this as an SQL keyword surrounded by spaces" would be both easier to read and implement, something like:
```clj
[:overlay :col :*placing "hi" :*from 1 :*for 2]

[:overlay :col :_placing "hi" :_from 1 :_for 2]

[:overlay :col :-placing "hi" :-from 1 :-for 2]
```
 (underscores or hyphens as a visual aid to getting that it will be inlined or "grounded").

Given that, as you said, `:*` and `:-` are used on their own, `_` seems to make the most sense. Initially I thought that maybe having them at both sides of a keyword would be good, like `:_from_`, but after writing a few expressions like that I think that a single leading one is better.

**Comment by seancorfield** [comment]
Is there a danger that folks might have existing columns (or tables) whose name begins with `_` (so that would collide with trying to use `:_` or `'_` as a prefix for this)?

Also, note that `:overlay` (and the others listed here) takes a single argument so there's an inherent conflict between:

```clojure
[:overlay :col :*placing "hi" :*from 1 :*for 2]
```

and a function call with seven arguments, whereas:

```clojure
[:overlay [:*placing-from-for :col "hi" 1 2]]
```

does not have that ambiguity (you are right that doesn't work for expressions that need a _leading_ SQL keyword like `TRIM`).

I wouldn't be averse to having two related syntaxes here: one indicating a "spread" or interspersed list of keywords (which was why I initially thought of `:*` for "spread") and another one indicating some of prefixing, e.g., `[:!leading-from "," :x]` producing `LEADING ? FROM x` with `","` as a parameter.

**Comment by p-himik** [comment]
> Is there a danger that folks might have existing columns (or tables) whose name begins with `_` (so that would collide with trying to use `:_` or `'_` as a prefix for this)?

Of course. But it's also the case for `:*...`, even when used as in your original proposal, albeit it's much less likely that someone has an SQL function named `*something`.
That danger is slightly alleviated by the fact that with the right quoting settings `"_foo"` in SQL can be written as `:-foo` in HoneySQL.

The only other valid character in keywords that's not used as an operator in HoneySQL is `!`. There is `:!=` but perhaps, if the flag ends up being `!`, that operator could be explicitly checked for.

> `:overlay` takes a single argument so there's an inherent conflict between `[:overlay :col :*placing "hi" :*from 1 :*for 2]` and a function call with seven arguments

If I understand what you mean by "conflict" correctly, then it's exactly the same with `[:overlay [:*placing-from-for :col "hi" 1 2]]`, no?
After all, `overlay` in SQL is not a function of a single argument, there are 3 or 4 arguments - they are just separated with words instead of commas (if I'm reading PostgreSQL source code correctly, internally it translates `OVERLAY("x" PLACING "y" FROM 1 FOR 2)` into a C call of `text_overlay("x", "y", 1, 2)` or something like that).

---

But it all feels a tad icky, regardless of the approach. The `overlay` signature is fixed, so why would anyone need to repeat those extra keywords over and over again? It would make sense if they weren't positional, but they are.
What if, instead of yet another syntax oddity, there would be a much easier way to register such functions? Something that lets a user say that `:overlay`, when formatted as a function, should have its first `, ` replaced with ` PLACING `, the second `, ` replaced with ` FROM `, and so on?
That will also work for `extract` - `TIMESTAMP '2000-12-16 12:21:13'` is a value by itself, the function doesn't see the word `TIMESTAMP`, and the first argument could be "quoted" with `:'...`, as in `:'century`.
It's possible to make it work for functions like `xmlelement` where there's a fixed leading keyword (god, why is it all some complex, why not just a list of arguments...)
That will even work for functions like `trim` - if you treat the first word as an argument to the function (an argument that must always be quoted and implicitly inlined), then the first `, ` should be replaced with ` `, just a space.

**Comment by seancorfield** [comment]
I meant more that `[:f 1 2 3 4 5 6 7]` is formatted as `F(1, 2, 3, 4, 5, 6, 7)` whereas `[:f [..]]` is formatted as `F( <single-expression> )`

The formatting logic for a function's argument list is to basically `(str/join ", " (map format-expr args))` and that semantic -- that lists of expressions can be formatted by formatting each expression and joining the results together -- is fairly widespread in HoneySQL. 

Expressions are analyzed in isolation -- HoneySQL's only "flag" to control formatting is something function-like so encountering something like `[:f 1 :_foo 2 3 :_bar 4 :_quux 5 6]` becomes really hard to process since `(1 :_foo 2 3 :_bar 4 :_quux 5 6)` would need to become `1 FOO 2, 3 BAR 4 QUUX 5, 6`, i.e., three arguments.

And this "mixed" notation of "phrases" and "comma-separated" argments is needed for `xmlelement` (based on what you showed above) so I can't just look for "arguments" that are `:_..` or `'_..` to indicate interspersed SQL keywords and assume the whole argument list is that format, rather than the current format -- it's not one or the other, it can be both.

_time passes, cogs in the brain go round_

OK, I think I can see how to make this work by essentially doing the following:
* map format-expr over args with the `:_*` expressions dropped
* loop over that and the original args...
  * ...using the formatted keyword for `:_*` or else `,` to join the args

(with a bit of careful special casing for the start and end of the list)

I'll give this a bit more thought over the next few days and prototype something up at the weekend.

It's possible this would allow HoneySQL to drop a lot of special syntax processing by mapping existing special syntax onto this new feature (distinct, escape, interval, etc).

**Comment by seancorfield** [comment]
A first pass at this, using `:*foo` to indicate interspersed keywords, is available on **develop** now -- here are tests showing it in action: https://github.com/seancorfield/honeysql/blob/develop/test/honey/sql_test.cljc#L1112-L1132

Documentation TBD once we've decided on the most appropriate syntax (I'm leery of usurping `:_foo` since that is a valid column name right now, assuming some DB allows a leading `_` in names).

**Comment by p-himik** [comment]
So, tried an alternative approach. What do you think?

```clojure
(defn register-fn!
  "Register a new function (as special syntax). The `formatter` is either
  a keyword, meaning that this new function should use the same syntax as
  an existing function, or a function of two arguments that generates a
  SQL string and parameters (as a vector). The two arguments are the name
  of the function (as a keyword) and a sequence of the arguments from the
  DSL."
  [function formatter]
  (let [function (sym->kw function)]
    (assert (keyword? function))
    (let [k (sym->kw formatter)
          f (if (keyword? k)
              (get @special-syntax k)
              formatter)
          f (if (map? f)
              (let [{:keys [separators with-first?]} f
                    f-str (sql-kw function)
                    separators (mapv (fn [s]
                                       (let [s (sql-kw s)]
                                         (str
                                           (when-not (or (str/starts-with? s ",")
                                                         (str/starts-with? s " "))
                                             " ")
                                           s
                                           (when-not (str/ends-with? s " ")
                                             " "))))
                                     separators)
                    separators (concat separators (repeat ", "))]
                (fn [_function args]
                  (let [sql+params (mapv format-expr args)
                        all-sqls (map first sql+params)
                        all-params (mapcat rest sql+params)
                        sql (str f-str "("
                                 (str/trim
                                   (str/join (if with-first?
                                               (interleave separators all-sqls)
                                               (butlast (interleave all-sqls separators)))))
                                 ")")]
                    (into [sql] all-params))))
              f)]
      (when-not (and f (or (fn? f) (and (var? f) (fn? (deref f)))))
        (throw (ex-info "The formatter must be a function or existing fn name"
                        {:type (type formatter)})))
      (swap! special-syntax assoc function f))))


(sql/register-fn! :substring {:separators [:from :for]})

(sql/format {:select [[[:substring :a :b]]]})
=> ["SELECT SUBSTRING(a FROM b)"]
(sql/format {:select [[[:substring :a :b :c]]]})
=> ["SELECT SUBSTRING(a FROM b FOR c)"]

(sql/register-fn! :xmlattributes {:separators [:as]})
(sql/register-fn! :xmlelement {:separators  [:name]
                               :with-first? true})

(sql/format {:select [[[:xmlelement :a [:xmlattributes :b :c] :d :e]]]})
=> ["SELECT XMLELEMENT(NAME a, XMLATTRIBUTES(b AS c), d, e)"]
```

**Comment by seancorfield** [comment]
Currently, `[:substring :a :b]` produces `SUBSTRING(a, b)` which works in all SQL dialects. It doesn't need to be registered separately to have the `FROM`/`FOR` formatting -- and that formatting doesn't work in all SQL dialects, as far as I can see, so I don't like the idea of a) having to register a function with separators when the function already works without them and b) having that formatting baked into `register-fn!` as a "hijack" of regular function formatting.

I'm also not sure how your proposal would work for `:trim` which can be `TRIM(BOTH ' ' FROM col)` or `TRIM(BOTH FROM col)` or `TRIM(' ' FROM col)` where both the introductory keyword and the removal string are optional?

**Comment by p-himik** [comment]
> Currently, `[:substring :a :b]` produces `SUBSTRING(a, b)` which works in all SQL dialects. 

Oh, so it does... Weird that [this PostgreSQL doc page](https://www.postgresql.org/docs/current/functions-string.html) doesn't mention it. It does mention `substr` though and it does explicitly say that `substring` is a keyword-based function. And the SQL standard (albeit, from 1999 since I couldn't find a newer edition online) says that it must be a keyword-based function. Not sure what to think of it, but feels like `subtring(a TEXT, b INTEGER[, c INTEGER])` is a happenstance in PostgreSQL and not something deliberate/public.

But in any case, I chose `substring` only to demonstrate the code, so any other keyword-based function could be used there.

> I'm also not sure how your proposal would work for `:trim`

Given that the proposal makes the keywords fixed, same-named functions that use different keywords at the same place will have to be named differently. So there will have to be 3 functions - `:trim-leading`, `:trim-trailing`, and `:trim-both`. I wouldn't say it's too bad. Actually, I would probably prefer it to always having to pass an argument - similar to `.activate()` and `.deactivate()` as opposed to just (or in addition to) `.setActive(bool)`.

---

Going back to `:*...`.
> I wouldn't be averse to having two related syntaxes here: one indicating a "spread" or interspersed list of keywords (which was why I initially thought of `:*` for "spread") and another one indicating some of prefixing, e.g., `[:!leading-from "," :x]` producing `LEADING ? FROM x` with `","` as a parameter.

Given the discussion, it seems clear that there's no spreading of any kind here, it's just inlining SQL keywords.
It makes me feel that `!` would be a more suitable flag.

**Comment by seancorfield** [comment]
Looking around the 'net at various SQL tutorials, there's a mix of `SUBSTRING()` with pure positional arguments and with keywords. The MS SQL Server docs give no indication that keywords are supported in any functions. The MySQL docs show keywords, but most of the tutorials for MySQL use pure positional arguments. It's definitely the Wild West out there (as so much SQL seems to be, across different databases).

I agree that `:!kw` seems a more reasonable choice here than `:*kw` so I'll change the implementation to that. I think that allowing folks to "opt-in" to this syntax, as and when they feel it is more readable, is probably the best compromise -- given that some dialects don't seem to support it at all (which means that if someone uses these inline keywords, it's on them to be portable across whatever dialects they need to use -- I'll add that caveat in the docs).
