### ISSUE TITLE
HoneySQL2 makes all functions calls uppercase

### ISSUE THREAD

**Issue by slvrtrn** [jkk/honeysql#479]
I encountered this issue while migrating [the ClickHouse plugin for Metabase](https://github.com/ClickHouse/metabase-clickhouse-driver) to HSQL2 as Metabase is going to drop HSQL1 support in a few versions, and there are deprecation warning now.

Having something like this in HSQL1

```clj
(defmethod sql.qp/->honeysql [:clickhouse LocalDateTime]
  [_ t]
  (hsql/call :parseDateTimeBestEffort t))
```

as I understood, it should look like this with HSQL2

```clj
(defmethod sql.qp/->honeysql [:clickhouse LocalDateTime] 
  [_ t] 
  [:parseDateTimeBestEffort t])
```

However, `:parseDateTimeBestEffort` function call, which was not capitalized in HSQL1, now is uppercase, and ClickHouse DB does not like that:

```
clojure.lang.ExceptionInfo: 
INSERT FAILED: Code: 46. DB::Exception: Unknown function PARSEDATETIMEBESTEFFORT. 
Maybe you meant: ['parseDateTimeBestEffort','parseDateTime64BestEffort']: 
While processing PARSEDATETIMEBESTEFFORT('2014-04-01 08:30:00'): 
While executing ValuesBlockInputFormat. 
(UNKNOWN_FUNCTION)
```

I searched for an option to disable this behavior but couldn't find any. 
Ideally, I'd like to have the possibility to render the function calls as-is without changing the case, just like it was in HSQL1.

**Comment by seancorfield** [comment]
For case-sensitive names, you can use `'` in the name to prevent upper-case coercion:

```clojure
user=> (require '[honey.sql :as sql])
nil
user=> (sql/format [:parseDateTimeBestEffort :t])
["PARSEDATETIMEBESTEFFORT(t)"]
user=> (sql/format [:'parseDateTimeBestEffort :t])
["parseDateTimeBestEffort(t)"]
user=>
```

**Comment by slvrtrn** [comment]
thanks @seancorfield!

**Comment by seancorfield** [comment]
In 2.4.1011, I added a new section to the docs https://cljdoc.org/d/com.github.seancorfield/honeysql/2.4.1011/doc/getting-started/other-databases that mentions this for ClickHouse.
