### ISSUE TITLE
Difficulties in converting documentation examples from hashmap form to helper function form

### ISSUE THREAD

**Issue by NoahTheDuke** [jkk/honeysql#480]
Hey Sean!

Great work overall on v2, been slowly transitioning and it's going well. Ran into a small issues/moment of frustration earlier today when I struggled to call one of the helper functions with the correct arguments because the example in the documentation used the map form.

To be very specific for the purposes of helping, I was reading the section on [`insert-into`](https://cljdoc.org/d/com.github.seancorfield/honeysql/2.4.1006/doc/getting-started/sql-clause-reference#insert-into-replace-into). The "third case" involves passing a CTE to the INSERT INTO "table name" clause, and is written with a quoted map.

The example says: `(sql/format '{insert-into (transport {select (id, name) from (cars)})})`

My existing v1 code is: `(-> (insert-into :temp-table) (query-values (-> (with ...) ...)) ...)`

I initially wrote `(-> (insert-into (:temp-table (-> (with ...)))) ...)`, but that of course gave me "INSERT INTO NULL". Realizing my mistake (calling the keyword), I then tried `(-> (insert-into [:temp-table (-> (with ...))]) ...)` as that sort of matched the `(transport {...})` form in the example (vector instead of list). That resulted in "INSERT INTO TEMP TABLE (WITH ...)", not sure exactly why. After poking at it for a minute, I realized my mistake, that I needed to pass the CTE as a second argument to `insert-into`, which naturally fixed the issue.

Some of this is user error, I didn't read the docstring of `insert-into` because v1 trained me to ignore the docstrings as mostly useless lol. (v1 `insert-into` has no docs and the arglist is `([table] [m table])`. Not helpful.)

But some of it is also that there's a small and necessary disconnect between the expected API of the helper functions and of the map-based query-as-data, and using the map-based form in the docs led me to misunderstand how it worked.

Is this a real issue? Should anything be done to help poor fools like me out in the future?

**Comment by seancorfield** [comment]
Is the missing piece in the helper docs essentially something like this?

In general, `(helper foo bar)` is equivalent to `{:helper [foo bar]}`.

**Comment by NoahTheDuke** [comment]
Yeah, I think that would be helpful. Maybe a link to the docs for a helper when it exists? The documentation for `insert-into` can remain map-focused and then at the top or bottom, "There's a helper function for this if that's your style: [[honey.sql/insert-into]]".

**Comment by seancorfield** [comment]
Well, there's a helper function for every DSL clause by design (there's an assert that fails the build if that's not the case) so adding a link for every clause would be redundant, but I'll try to find appropriate places to add that "hint" into parts of the documentation.

**Comment by NoahTheDuke** [comment]
Cool, thanks for the help.

**Comment by NoahTheDuke** [comment]
The updated docs look good, thank you.
