### ISSUE TITLE
`format` can emit syntactically invalid AS clauses

### ISSUE THREAD

**Issue by spencerwilson** [jkk/honeysql#482]
In both 2.4.1011 and 2.3.928,
```clj
(-> (honey.sql/format {:select [[:col :a/b]]})
    first
    println)
```
prints `SELECT col AS a.b`. This is not valid SQL:2016. Compare with `<as clause>` in the [SQL:2016 grammar](https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#_7_16_query_specification). Specifically, `a.b` does not parse as a `<column name>`.

The following _does_ work, though:
```clj
(-> (honey.sql/format {:select [[:col (keyword "a.b")]]})
    first
    println)
```
prints `SELECT col AS "a.b"`, which is valid since `"a.b"` parses as a `<column name>`.

Some possible resolutions:

- If `:a/b` is used in "column alias" position, format it as a delimited identifier `"a.b"` (automatically join the namespace and name with a `.`. Note that this would be a different transformation than what's done for when it appears in a [`<column reference>`](https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#_6_7_column_reference) position, where such a namespaced keyword would get formatted as `a.b`.
- Throw an error if someone supplies a namespaced keyword as an alias, w/ message referring to this issue.
- Document the gotcha, and continue to generate invalid SQL when given this input.

Not knowing anything about HoneySQL's implementation, my vote would be for the first one.

**Comment by seancorfield** [comment]
There are many, many ways that HoneySQL can be persuaded to generate invalid SQL -- and various databases accept all sorts of weird extensions to ANSI SQL so it's actually counter-productive for HoneySQL to try to restrict results to "standard" SQL.

I'd lean to 3) but, like I say, all sorts of constructs can generate invalid SQL for a specific database so -- other than a very generic caveat at the start of the README that if you pass garbage in, you'll get garbage out -- I am not convinced anything useful be done.
