### ISSUE TITLE
`:quoted` doesn't work together with `if exists`

### ISSUE THREAD

**Issue by danielhvs** [jkk/honeysql#488]
Hi!
I've noticed that using `:quoted` option doesn't work very well when we try to use together with "if exists" (and related).

```clojure
(sql/format (hh/drop-view [:if-exists] :aBc) {:quoted true})
; => ["DROP VIEW  IF EXISTS ABC"]

(sql/format (hh/drop-view :aBc) {:quoted true})
; => ["DROP VIEW \"aBc\""]
```

Expected:

```clojure
(sql/format (hh/drop-view [:if-exists] :aBc) {:quoted true})
; => ["DROP VIEW  IF EXISTS \"aBc\""]
```

Is there another way of achieving the desired result without relying on `:raw`?

**Comment by danielhvs** [comment]
(sql/format (hh/drop-view :if-exists :aBc) {:quoted true})
; => ["DROP VIEW  IF EXISTS \"aBc\""]

**Comment by seancorfield** [comment]
I suspect your confusion came from misunderstanding how helpers and the underlying clauses relate -- if you use just the helper, without `sql/format`, you can see what data structure it produces:

```clojure
user=> (require '[honey.sql :as sql] '[honey.sql.helpers :as hh])
nil
user=> (sql/format {:drop-view [:if-exists :aBc]} {:quoted true})
["DROP VIEW IF EXISTS \"aBc\""]
user=> (hh/drop-view [:if-exists] :aBc)
{:drop-view [[:if-exists] :aBc]}
user=> (hh/drop-view :if-exists :aBc)
{:drop-view [:if-exists :aBc]}
user=>
```

Per the [**Clause Reference**](https://cljdoc.org/d/com.github.seancorfield/honeysql/2.4.1026/doc/getting-started/sql-clause-reference):

> In general, `(helper :foo expr)` will produce `{:helper [:foo expr]}` (with a few exceptions -- see the docstring of the helper function for details).
