### ISSUE TITLE
Does honeysql support pg's json path?

### ISSUE THREAD

**Issue by cmal** [jkk/honeysql#492]
Hi! Does honeysql support pg's json path? Thanks!

**Comment by seancorfield** [comment]
I've no idea what you're asking. Please provide a link to the relevant documentation and an example of what you're trying to generate.

**Comment by zerg000000** [comment]
@cmal are you talking about pg json operator? 

https://www.postgresql.org/docs/9.3/functions-json.html

https://cljdoc.org/d/com.github.seancorfield/honeysql/2.4.1045/api/honey.sql.pg-ops#-%3E

It would be better to just scan through the documentation first, and provide enough information when you ask for help.

**Comment by seancorfield** [comment]
@cmal I'm going to close this next week unless you can provide either more details, or confirmation that you have enough information.

**Comment by seancorfield** [comment]
Closing for lack of information.
