### ISSUE TITLE
namespace honey.sql does not exist. i found honeysql.core in the core.cljc included in the jar.

### ISSUE THREAD

**Issue by johanatan** [jkk/honeysql#506]
should the README's `require` calls be updated appropriately?

**Comment by p-himik** [comment]
You're using HoneySQL 1.x. The README is about HoneySQL 2.x.

**Comment by johanatan** [comment]
The one I am using is the latest you get from clicking the little clojars bar link. So, still a readme bug.

**Comment by p-himik** [comment]
The top Clojars bar points to https://clojars.org/com.github.seancorfield/honeysql, without any version, so the page mentions the latest, which is `2.4.1066` currently.

There's another section in the README at https://github.com/seancorfield/honeysql#honeysql-1x, perhaps you have clicked the link there. But that section is specifically about the 1.x version, so it's intended.

**Comment by johanatan** [comment]
Ah yea I didn’t look closely and just clicked the first clojars bar I saw (which when scrolling up from the bottom after having skimmed the readme was the 1.x one). 🫤

**Comment by p-himik** [comment]
So seems that the issue can be closed then?

**Comment by seancorfield** [comment]
I've updated the README to make it clearer that 1.x is a legacy version:
![image](https://github.com/seancorfield/honeysql/assets/43875/e02bb3cd-9340-419e-882a-ee078208d328)
