### ISSUE TITLE
Cast seems to be breaking with a type named "*-type" in v2.4.962

### ISSUE THREAD

**Issue by liquidz** [jkk/honeysql#507]
### Expected

`[:cast :foo :bar-type]` should be formatted to `CAST(foo AS bar_type)`.

### Actual

`[:cast :foo :bar-type]` is formatted to `CAST(foo AS BAR TYPE)` with v2.4.962 or above.

### How to reproduce

* v2.4.947
```clojure
(honey.sql/format {:select [:foo [[:cast :bar :foo-type]]]})
;; => [SELECT foo, CAST(bar AS foo_type)]
```
* v2.4.962
```clojure
(honey.sql/format {:select [:foo [[:cast :bar :foo-type]]]})
;; => [SELECT foo, CAST(bar AS FOO TYPE)]
```

**Comment by seancorfield** [comment]
That seems to be a side-effect of https://github.com/seancorfield/honeysql/pull/443 in order to avoid (incorrect) quoting -- and also to uppercase type names in that context.

**Comment by seancorfield** [comment]
You can use the quoted-keyword form to avoid that:

```clojure
user=> (require '[honey.sql :as h])
nil
user=> (h/format [:cast :foo :bar-type])
["CAST(foo AS BAR TYPE)"]
user=> (h/format [:cast :foo :'bar-type])
["CAST(foo AS bar_type)"]
```

I'll have to give this some thought because the original behavior was incorrect with quoting but the new behavior is a breaking change for some types.

**Comment by seancorfield** [comment]
There's a Postgres-related test in the suite:

```clojure
  (is (= ["SELECT foo, CAST(bar AS DOUBLE PRECISION)"] ;; Postgres example
         (sql/format {:select [:foo [[:cast :bar :double-precision]]]})))
```

To keep that working `:bar-type` **MUST** format as `BAR TYPE` by default so you either have to use `:bar_type` (to produce `BAR_TYPE`) or `:'bar-type` as noted above.

I'll update the `:cast` documentation to make this clear -- the behavior of hyphenated type names in 2.4.947 and earlier should be considered a bug, I'm afraid.

**Comment by liquidz** [comment]
@seancorfield Thanks for your confirmation!

> I'll update the :cast documentation to make this clear -- the behavior of hyphenated type names in 2.4.947 and earlier should be considered a bug, I'm afraid.

OK. I'll change to use `:foo_type`. Thanks!

**Comment by seancorfield** [comment]
I've added several examples to the **Special Syntax** description of `:cast` and a note about the change in behavior (from December last year), as well as adding a note to 2.4.962 in the CHANGELOG with a link to this new documentation (when I cut a new release to update cljdoc.org).
