### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by MichaelBlume** [jkk/honeysql#51]
I'd like to cut a new release soonish. I'm guessing we want to merge #34 and #43 before we do that. Is there anything else we should try to get in?

**Comment by ddellacosta** [comment]
I'd like to get #50 in if no one objects.  Otherwise, I'll update #34 immediately after if you merge in #43 @MichaelBlume , assuming @jkk is on board with that plan.

**Comment by ddellacosta** [comment]
Are we going to bump this to 0.5.0?  Seems like it fits the bill considering we're adding a fair bit of functionality vs. simply doing bug fixing.

**Comment by MichaelBlume** [comment]
That sounds about right to me, yeah

**Comment by jkk** [comment]
Thumbs up from me for everything. Thanks again for bringing this repo back to life.

**Comment by MichaelBlume** [comment]
Glad to help, it's been fun =)

I think all the named pulls are in, I'm up to try pushing up a release if everything seems ready.

**Comment by MichaelBlume** [comment]
Done =)

Clojars doesn't want to promote the new release, though, because the project.clj doesn't have an url. I've fixed that in master and I think I'd like to just push up 0.5.1 so we have a promoted package.

**Comment by ddellacosta** [comment]
Awesome!  BTW folks, I wanted to bring up the fact that the packages haven't been signed up until now--I would push for that, although I recognize that it adds an extra layer of complexity and would require any of us who can push to clojars to have a set of keys. Thoughts?

Congrats to all on the new release!  Very exciting.  I've bumped the version # on README to 0.5.1--maybe we should merge in #45?

**Comment by ddellacosta** [comment]
Also, seems like the release was pushed from your fork @MichaelBlume--probably better to push from the main repo.

**Comment by MichaelBlume** [comment]
Yeah, I can't quite figure out how to convince it that I am pushing from
the main repo

**Comment by MichaelBlume** [comment]
Oh, hm, maybe the problem is that I have my repo marked as 'origin'
