### ISSUE TITLE
BigQuery ARRAY subquery

### ISSUE THREAD

**Issue by markaddleman** [jkk/honeysql#512]
https://cloud.google.com/bigquery/docs/reference/standard-sql/array_functions#array

**Comment by markaddleman** [comment]
Obviously keyword :array conflicts with the existing HoneySQL use of :array.  FWIW, in my custom formatters, I prefix BQ special syntax with :bq/ ...

**Comment by seancorfield** [comment]
The current `:array` takes an expression so I could make it accept a statement as well and generate this syntax. 

Looks like we'd need support for `select as struct` as well so I'll have to give that some thought.

**Comment by seancorfield** [comment]
PostgreSQL also supports `ARRAY(subquery)` and the docs have an example showing how to do that:

```clojure
user=> (sql/format {:select [[[:'ARRAY {:select :oid :from :pg_proc :where [:like :proname [:inline "bytea%"]]}]]]})
["SELECT ARRAY (SELECT oid FROM pg_proc WHERE proname LIKE 'bytea%')"]
```

So, you have a way to do it right now but it would make sense for me to adjust how `:array` works with subqueries so the workaround with `'` isn't needed for PostgreSQL either.
