### ISSUE TITLE
with clause does not support register-fn! formatters

### ISSUE THREAD

**Issue by snoe** [jkk/honeysql#525]
Given this registered formatter:
```clojure
  (defn- foo-formatter [f [x]]
    [(str "(select * from _secret)")])

  (sql/register-fn! :foo foo-formatter)
```

These are equivalent:
```clojure
 
  (sql/format {:select [:*], :from [[{:select [:*] :from [:secret]}]]})
  (sql/format {:select [:*], :from [[[:foo]]]})
```

However using `[:foo]` in a `with` clause here throws an exception:
```clojure
  (sql/format {:select [:*], :from [:x] :with [[:x {:select [:*] :from [:secret]}]]})
  (sql/format {:select [:*], :from [:x] :with [[:x [:foo]]]})
```

In metabase, [we use a similar formatter](https://github.com/metabase/metabase/blob/master/src/metabase/driver/sql/query_processor.clj#L72) to do some slight modification of raw sql that we reference with a `:from [[[::sql-source-query native-query] :source]]` It would be helpful to be able to do the same in a `with` clause.

**Comment by seancorfield** [comment]
Functions are not acceptable in every context. What you want here is a _clause_, not a function, since you want it to be usable in places where a _clause_ is acceptable:

```clojure
; foo-formatter as above
user=> (sql/register-clause! :foo foo-formatter :select)
...
user=> (sql/format {:select [:*], :from [:x] :with [[:x {:foo []}]]})
["WITH x AS ((select * from _secret)) SELECT * FROM x"]
```

(modulo `WITH` automatically nesting its argument so `foo-formatter` would need to omit the `(`..`)`)
