### ISSUE TITLE
Postgres `@?` operator produces `@??`

### ISSUE THREAD

**Issue by igrishaev** [jkk/honeysql#528]
Steps to reproduce:

```clojure
(require '[honey.sql.pg-ops :as sut])

(sql/format {:select [[[sut/at? :a :b] :x]]})
["SELECT a @?? b AS x"]
```

But it must have been `@?`. I've tried various options but still getting a double q.mark. I believe, there is some kind of extra quoting for safe purposes, no?

**Comment by seancorfield** [comment]
I've made what I believe is the smallest reasonable change to fix this -- namely that infix/prefix operators are now exempt from the `?` -> `??` escaping that functions and SQL keywords at large are currently subject to. This should fix the PG ops issue.

There is a very small potential breakage for anyone registering custom operators that contain `?` but rely on the `??` escaping -- but I think this is extremely unlikely (and it's probable that if they were doing this, they too would have been surprised by the escaping and would have already raised it as a question... I hope!).

**Comment by seancorfield** [comment]
If you want to try this out, you can either depend on the source via `:git/url` or the new `2.6.9999-SNAPSHOT` release on Clojars.

**Comment by seancorfield** [comment]
Per @igrishaev reverting this change as it is not actually needed.
