### ISSUE TITLE
The `:join` special syntax does not allow specifying an alias for the leftmost expression

### ISSUE THREAD

**Issue by p-himik** [jkk/honeysql#529]
The original Slack thread: https://clojurians.slack.com/archives/C66EM8D5H/p1715631198472399

The desired query:
```sql
SELECT *
FROM foo
LEFT JOIN (populations pm INNER JOIN customers pc ON pm.id = pc.id AND pm.other_id = pc.other_id)
ON foo.fk_id = pm.id
```

My attempt at it:
```clojure
(sql/format {:select    :*
             :from      :foo
             :left-join [[[:join [:populatons :pm]
                           {:join [[:customers :pc]
                                   [:and
                                    [:= :pm/id :pc/id]
                                    [:= :pm/other-id :pc/other-id]]]}]]
                         [:= :foo/fk-id :pm/id]]})
=>
["SELECT * FROM foo LEFT JOIN (POPULATONS(pm) INNER JOIN customers AS pc ON (pm.id = pc.id) AND (pm.other_id = pc.other_id)) ON foo.fk_id = pm.id"]
```

The [special syntax](https://cljdoc.org/d/com.github.seancorfield/honeysql/2.6.1126/doc/getting-started/sql-special-syntax-#join) required for that works just fine, except for the `populations pm` part.
If you were to use `[:populations :pm]` it'd be formatted as an expression and thus would become `populations(pm)`.

There's a special `:alias` syntax that sounds suitable, but it doesn't work either as it expects only a single argument.

**Comment by seancorfield** [comment]
The special `:join` syntax was introduced in #483 so I'll have to see why I implemented it as `format-expr` in the first place, since that precludes using an alias without forcing additional nesting to get the expression semantics.

**Comment by seancorfield** [comment]
Looking at the syntax diagrams in a few database's docs, it looks like `format-selectable-dsl` would be better here than `format-expr` and there are no expression examples given, nor tests in HoneySQL, so changing this shouldn't break anyone's _sanctioned_ code... And clearly the expectation is that `[:populations :pm]` _should_ work (which a selectable DSL formatter would do), and therefore an expression would need an additional level of `[` .. `]` just as in `from` and `select` and so on.

**Comment by p-himik** [comment]
I _think_ that that syntax is largely to avoid regrouping items. Maybe @NoahTheDuke can correct me, but after skimming the docs it seems that an alternative way to write the very same query would be:
```sql
SELECT *
FROM populations pm
INNER JOIN customers pc ON pm.id = pc.id AND pm.other_id = pc.other_id
RIGHT JOIN foo ON foo.fk_id = pm.id
```

With that in mind, maybe the whole special-case `:join` is unnecessary if `(...)`-grouping can be achieved at the e.g. `:join-by` level.

A somewhat related perspective pointed out by those docs mentioned in #483:
> A JOIN clause combines two FROM items

So, at least conceptually and for PostgreSQL, `:join` seems to logically belong to `:from`. Of course, that ship has long sailed, but maybe extending `:from` is also an option.
