### ISSUE TITLE
How to specify `USING` with `create-index`?

### ISSUE THREAD

**Issue by evanlouie** [jkk/honeysql#530]
I'm trying to write the following postgresql and can't figure out how to specify a `GIN` index.

```sql
create index my_index
    on my_table using gin (properties);
```

**Comment by seancorfield** [comment]
This was the PR that added `:create-index` (fairly recently): https://github.com/seancorfield/honeysql/pull/517

I don't use PostgreSQL so this isn't a syntax I've ever seen. You're welcome to submit a PR to enhance the work done in #517 with some appropriate way to support the syntax you need (with tests and docs please).

**Comment by seancorfield** [comment]
```clojure
user=> (sql/format {:create-index [:my_index [:my_table :using-gin :properties]]})
["CREATE INDEX my_index ON my_table USING GIN (properties)"]
```
