### ISSUE TITLE
postgres :alter-column documentation produces incompatible queries.

### ISSUE THREAD

**Issue by Tillaert** [jkk/honeysql#536]
According to the [honeysql postgres documetation:](https://github.com/seancorfield/honeysql/blob/develop/doc/postgresql.md#ddl-support) 

This statement is given as an example. 
```
user=> (-> (alter-table :fruit)
           (alter-column :name [:varchar 64] [:not nil])
           sql/format)
["ALTER TABLE fruit ALTER COLUMN name VARCHAR(64) NOT NULL"]
```
However, this creates code which is not compatible with postgres. 

Postgres expects

`ALTER TABLE fruit ALTER COLUMN name TYPE VARCHAR(64)`

and

`ALTER TABLE fruit ALTER COLUMN name SET NOT NULL`

(See: https://www.postgresql.org/docs/current/sql-altertable.html )

This can be achieved with these queries:

`{:alter-table [:table], :alter-column [(:column :set [:not nil])]}`

and:

`{:alter-table [:table], :alter-column [(:column :type [:varchar 64])]}`

**Comment by seancorfield** [comment]
Your alternatives do not work:
```clojure
user=> (sql/format {:alter-table [:table], :alter-column [(:column :set [:not nil])]})
["ALTER TABLE table ALTER COLUMN not NULL"]
```
But the following do work:
```clojure
user=> (-> (alter-table :fruit)
           (alter-column :name :type [:varchar 64])
           sql/format)
["ALTER TABLE fruit ALTER COLUMN name TYPE VARCHAR(64)"]
user=> (-> (alter-table :fruit)
           (alter-column :name :set [:not nil])
           sql/format)
["ALTER TABLE fruit ALTER COLUMN name SET NOT NULL"]
user=>
```
The raw DSL for that last one is:
```clojure
{:alter-table [:fruit], :alter-column [:name :set [:not nil]]}
```

**Comment by Tillaert** [comment]
You are correct. My apologies for the mistake.
