### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by MichaelBlume** [jkk/honeysql#54]
@jkk can you make @ddellacosta and I able to see the settings tab on the honeysql repo? I'd really really like to turn on automatic travis builds, and I think I can do that myself with access to settings, but I can't seem to see them right now.

**Comment by jkk** [comment]
@MichaelBlume I don't see a way for me to give you guys access to settings. I added Travis CI as a service to settings, though I didn't add anything under username/password/domain fields that it shows

**Comment by MichaelBlume** [comment]
Aha, sorry, looks like there's not actually any way to do that.

So what *should* work is if you go to https://travis-ci.org/recent , click "sign-in with github" in the top-right, accede to the permissions request (it's not that bad). Then click your icon which is now in the top-right corner, scroll down to honeysql, and flick the switch to on.

What this gives us is automated builds both of the master branch and of pull requests. Pull requests will be visibly tagged in github with the results of their builds, and if we somehow push something breaking to master I think whoever merged it will get an e-mail. It's pretty handy.

**Comment by jkk** [comment]
@MichaelBlume followed your instructions on Travis CI. I think we're all set

**Comment by jkk** [comment]
@MichaelBlume Thanks for making it dead simple for me :)

**Comment by MichaelBlume** [comment]
Awesome, thanks :D
