### ISSUE TITLE
DDL statements for table names that start with % produce malformed SQL

### ISSUE THREAD

**Issue by alexander-yakushev** [jkk/honeysql#548]
Metabase uses URL encoding to escape non-ASCII table names, so after the encoding the name may start with `%`. The linked commit replaced calling `format-entity` on the ddl names with `format-var`, and the latter treats the leading `%` as a function call.
```clj
(honey.sql/format {:create-table (java.net.URLEncoder/encode "привіт")})
=> ["CREATE TABLE D0%BF%D1%80%D0%B8%D0%B2%D1%96%D1%82()"]
;; The above is a malformed SQL.
```

This appears to be caused by this commit: https://github.com/seancorfield/honeysql/commit/a3ef21548520636168a970d780ff46a4be4fa002.

I'm willing to fix this myself, but I need guidance on what approach should be taken.

**Comment by seancorfield** [comment]
Sorry that broke things. The fix will be to refactor `format-var` into two functions where the intermediate one does everything(?) except `%` handling, and change that table name code to use that instead. I'll fix that today.

**Comment by alexander-yakushev** [comment]
I can confirm that the latest SNAPSHOT version fixes the problem. Thank you very much!
