### ISSUE TITLE
HoneySQL fails on Babashka with NoSuchFieldException after version 2.5.1103

### ISSUE THREAD

**Issue by odie2630463** [jkk/honeysql#549]
When using HoneySQL versions after 2.5.1103 on Babashka, the library fails with a NoSuchFieldException. Version 2.5.1103 works correctly, but all subsequent versions produce this error.

java.lang.NoSuchFieldException: sym user honey/sql.cljc:440:14

**Comment by seancorfield** [comment]
The performance tweaks added in the latest round of changes introduced this Java interop call on `.sym`

**Comment by borkdude** [comment]
@seancorfield Any reason you're not just using `(symbol :keyword)`? This works in clojure 1.10

**Comment by seancorfield** [comment]
HoneySQL currently supports back to 1.9.0 which does not support `(symbol :keyword)`

**Comment by seancorfield** [comment]
@odie2630463 Can you try the 2.6.9999-SNAPSHOT version, that has a fix for this? (I hope)

I'll work with @borkdude to get Babashka into the test matrix and make it fully supported.

**Comment by seancorfield** [comment]
OK, Babashka testing is performed on PRs and commits to **develop** now -- Thanks @borkdude !
