### ISSUE TITLE
Support for type definition in aliases (for jsonb_to_recordset)

### ISSUE THREAD

**Issue by holyjak** [jkk/honeysql#557]
https://www.postgresql.org/docs/17/functions-json.html shows this SQL:

```sql
select * from json_to_recordset('[{"a":1,"b":"foo"}, {"a":"2","c":"bar"}]') as x(a int, b text) 
```

which is not possible to express with Honey and we have to fall back to raw:

```clj
(hh/from [:jsonb_to_recordset :my_jsonb_column])
               [[:'x [:raw "a int"] [:raw "b text"]]])
```

(Somewhat better docs here https://neon.tech/docs/functions/jsonb_to_record.)

**Comment by seancorfield** [comment]
I suspected this was already possible since aliases can have a qualifying "statement" DSL following them:

```clojure
user=> (sql/format {:select :* :from [[[:json_to_recordset :my-json-column] [:b {:with-columns [[:c :int] [:d :text]]}]]]})
["SELECT * FROM JSON_TO_RECORDSET(my_json_column) AS b (c INT, d TEXT)"]
```

Does that address your needs?

**Comment by seancorfield** [comment]
I see you gave a "raised hands" response to this example when I posted it in Slack, so I'm going to assume "yes" to my Q last week, and close this.
