### ISSUE TITLE
Support for Microsoft SQL Server paging queries

### ISSUE THREAD

**Issue by smahood** [jkk/honeysql#58]
Microsoft SQL Server requires a bit different syntax for paging queries. SQL Server 2005 and 2008 require a pretty ugly syntax that I don't know would be easy to add in to Honey SQL. SQL Server 2012, however, is pretty close to the format in PostgreSQL. 

In Honey SQL, `:select ... :limit 50 :offset 10` results in `SELECT ... LIMIT 50 OFFSET 10`. 

SQL Server 2012 requires queries in the form `SELECT ... OFFSET 10 ROWS FETCH NEXT 50 ROWS ONLY`.

Would it be possible to add in handling for this with new helpers in honeysql.helpers/build-clause (possibly `:offsetrows` and `:fetchnext`)?

**Comment by dball** [comment]
You could do that last bit yourself simply by making the helpers and registering them at the appropriate offsets in the query construction priority. Personally, I'd be slightly more interested in exploring including the database vendor as a hint to format; a generalization of what was done to support the postgresql parameterizer.

**Comment by camsaul** [comment]
You can just pass a `raw` argument as the `:offset`:

```clojure
(honeysql.core/format {:select [:*]
                       :from [:table]
                       :offset (honeysql.core/raw "10 ROWS FETCH NEXT 10 ROWS ONLY")})
->
["SELECT * FROM table OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY"]
```

**Comment by smahood** [comment]
Thanks @camsaul, that sounds perfect.

**Comment by ddellacosta** [comment]
FWIW if this is ANSI SQL don't think it's a bad idea to support it...any interest in providing a patch w/tests @smahood?

**Comment by smahood** [comment]
@ddellacosta I don't have the time right now, I've moved away from honeysql in my production sites and the solution above solves the problem well enough for any of my other uses.

**Comment by ddellacosta** [comment]
@smahood totally understood!
