### ISSUE TITLE
Opt of sub-queries for IPersistentMap in ToSql 

### ISSUE THREAD

**Issue by emidln** [jkk/honeysql#63]
Right now, ToSql defines a method (-to-sql [x] ...) that is specified to IPersistentMap in such a way as to prevent passing JSON values with (honeysql.helpers/values [{:my-json-field {:foo "bar"}}]). This is a significant obstacle for me right now. Would a patch that adds an optional second parameter (meaningful to at least the IPersistentMap implementation) be considered?

**Comment by MichaelBlume** [comment]
Yep, that sounds like an annoying problem, I'd be interested in seeing a patch to fix it.

**Comment by MichaelBlume** [comment]
Actually I wonder if it makes sense for IPersistentMap to implement ToSql at all. Is the IPM implementation used recursively or only as an entry point? If it's only an entry point would it make sense to have it be its own function?

**Comment by emidln** [comment]
It's unfortunately used recursively to process all of the clauses.

**Comment by emidln** [comment]
See https://github.com/jkk/honeysql/pull/64 for a pull request implementing this as an option to honeysql.format/format

**Comment by MichaelBlume** [comment]
Done, and released in 0.5.2 =)
