### ISSUE TITLE
DDL plans

### ISSUE THREAD

**Issue by niquola** [jkk/honeysql#67]
Hi, i'm interested in DDL support.

Do you have ideas or plans, how it should look like?

``` clojure

{:create-table :users
  :columns { :name [:serial :primary-key]
                    :email :text}}}

{:alter-table :users
 :add-columns { :password :text}
 :alter-columns {:email {:type :email :default "anonymous"}}
 :drop-columns [:email]}

{:drop-table :users}
```

**Comment by MichaelBlume** [comment]
I don't really have any ideas or plans, I'm curious how well this can be done without cluttering the interface with vendor-specific stuff. In my experience, my table definitions have a lot more vendor-specific syntax than my queries.

**Comment by seancorfield** [comment]
I'll second Michael's response here that DDL tends to be very vendor-specific so I'm not sure how a generic library like HoneySQL should handle this? It's also why the DDL support in `clojure.java.jdbc` is so minimal.

**Comment by seancorfield** [comment]
We already have `honeysql-postgres` and I just suggested a `honeysql-mysql` companion so maybe this is a candidate for that sort of library?

**Comment by seancorfield** [comment]
Given HoneySQL's position of trying to be vendor-neutral and DDL being inherently vendor-specific, I'm closing this out.
