### ISSUE TITLE
Support for MySQL's `ON DUPLICATE KEY UPDATE` Syntax?

### ISSUE THREAD

**Issue by timvisher** [jkk/honeysql#77]
I'm implementing `upsert!` and I would greatly benefit from access to this mysql feature. Is there any way to access it via honeysql?

**Comment by dball** [comment]
I myself implement it as follows:

```
(defn upsert-sql
  [table columns updates]
  (let [updates (map (ƒ [[column value]]
                       (str (name column) " = " value))
                     updates)]
    (str "INSERT INTO " (name table) " "
         "(" (string/join ", " (map name columns)) ") "
         "VALUES (" (string/join ", " (repeat (count columns) "?")) ") "
         (when (seq updates)
           (str "ON DUPLICATE KEY UPDATE "
                (string/join ", " updates))))))

(defn upsert!
  ([db table values updates]
     (upsert! db table (keys values) [(vals values)] updates))
  ([db table columns rows updates]
     (when (seq rows)
       (let [sql (upsert-sql table columns updates)]
         (apply jdbc/db-do-prepared db false sql rows)))))
```

But am also interested in supporting a logical upsert operation in honeysql. Perhaps we might consider supporting an :updates keyword taking a map of fields and values to upsert? It would be good to figure out a nice way to refer to the VALUES pseudo-function though. It would also be good to survey other databases' upsert syntaxes and make sure that whatever we chose to signify upserts could plausibly be rendered in their sql variants.

Honeysql doesn't seem to put much stock in developing common abstractions for database-specific features, which is a fine and practical choice, but if it's not hard to do so, it might be worth a bit of effort.

**Comment by dball** [comment]
I wrote some clause and helper support for them here:

https://github.com/jkk/honeysql/pull/86

which has the advantage of participating in honeysql's to-sql abstraction

**Comment by seancorfield** [comment]
Given HoneySQL's position of trying to be vendor-neutral and the fact that PR #86 was closed out years ago based on that position, I'm closing this out.
