### ISSUE TITLE
Automatic dashification/underscorizing

### ISSUE THREAD

**Issue by pjstadig** [jkk/honeysql#80]
It might be worth calling out in the Readme the fact that honeysql will automatically dashify/underscorize. This caught me off guard, and I'm not sure what I need to do about it. I'm trying to start using honeysql in a project where I am programatically creating tables in Postgres, and to prevent problems with dashes I just quote the column names. Honeysql is underscoring my column names. Is there a way to disable that behavior? I also need Honeysql to quote my unmodified column names. Currently, it is quoting them, but after it has already munged them, which seems a bit counter productive.

**Comment by pjstadig** [comment]
Probably some examples are in order:
```clojure
(sql/format {:select [:*] :from [:accumulator1] :where [:= :driver-name "foo"]})
=> ["SELECT * FROM accumulator1 WHERE driver_name = ?" "foo"]
(sql/format {:select [:*] :from [:accumulator1] :where [:= :driver-name "foo"]} :quoting :ansi)
=> ["SELECT * FROM \"accumulator1\" WHERE \"driver_name\" = ?" "foo"]
```

What I'd like to be able to do is:
```clojure
(sql/format {:select [:*] :from [:accumulator1] :where [:= :driver-name "foo"]} :quoting :ansi)
=> ["SELECT * FROM \"accumulator1\" WHERE \"driver-name\" = ?" "foo"]
```

**Comment by pjstadig** [comment]
This is HoneySQL 0.6.1.

**Comment by azapps** [comment]
I have forked Honey SQL and fixed this bug/feature. I understand that this will break many existing HoneySQL installations so I did not submit a pull request.

Here is the repo: https://github.com/azapps/honeysql and the commit: https://github.com/azapps/honeysql/commit/e3c77e8b

**Comment by dzhus** [comment]
+1 on this issue. The behaviour should be optional, most of databases can handle column names or aliases with dashes.

**Comment by jrdoane** [comment]
+1 on this as well, when formatting as ```:ansi``` to be specific. Preserving hyphens would be nice if the database supports it (PostgreSQL does,) and I think keywords with hyphens over underscores looks much more like idiomatic Clojure, so it makes sense to support it whenever possible and changing functionality based on the formatting as opposed to simply catering to the lowest common denominator.

**Comment by jrdoane** [comment]
Just to bat out some ideas, so this in unobtrusive, could an overidable function be provided in cases when we want control over this? How about an option to override the renaming function for fields? I would invision such a thing to be similar to this:

```clojore
(defn name-fn
  [q i] (str
           (when (keyword i)
             (when-let [n (namespace i)] (str q n q ".")))
           q (name i) q))

(sql/format
  {:select [[:foo/bar :bar-bar]]
   :from [[:foo-bar :foo]]}
   :quoting :ansi
   :name-fn name-fn)
```
To give us something like:
```clojure
["SELECT \"foo\".\"bar\" AS \"bar-bar\" FROM \"foo-bar\" \"foo\""]
```

That way, old code isn't broken while adding extensibility and control over quoting should someone want to express tables belonging to a particular schema (at least for PostgreSQL.) Just an idea. If I get adventurous, I might consider looking into doing this.

**Comment by MichaelBlume** [comment]
I'm probably not going to author a change myself, but if someone wants to submit a pull request and it doesn't look like it's going to break loads of existing code, I'll be happy to review it.

**Comment by jrdoane** [comment]
@MichaelBlume : Challenge accepted. :)
https://github.com/jkk/honeysql/pull/92

**Comment by jrdoane** [comment]
Take 2: https://github.com/jkk/honeysql/pull/93

**Comment by jrdoane** [comment]
Now that this change is merged in, we probably can mark this as resolved. :+1:

**Comment by ddellacosta** [comment]
@pjstadig Look good from your perspective?

**Comment by pjstadig** [comment]
:+1:
