### ISSUE TITLE
The #sql/array syntax

### ISSUE THREAD

**Issue by icambron** [jkk/honeysql#85]
It's easy to generate an update statement for a SQL array, using the syntax documented in the tests:

``` clj
dev=> (fmt/format {:update :foo :set {:bar #sql/array ["baz"]}})
["UPDATE foo SET bar = ARRAY[?]" "baz"]
```

But that doesn't actually work if vector is in a var, which I expect is a common case:

``` clj
dev=> (def bazzes ["baz"])
#'dev/bazzes
dev=> (fmt/format {:update :foo :set {:bar #sql/array bazzes}})

IllegalArgumentException Don't know how to create ISeq from: clojure.lang.Symbol  
clojure.lang.RT.seqFrom (RT.java:505)
```

I guess that's a reader macro, so maybe that can't be expected to work with anything but literals. 

Anyway, I figured out that you can do this:

``` clj
dev=> (fmt/format {:update :foo :set {:bar (honeysql.types/array bazzes)}})
["UPDATE foo SET bar = ARRAY[?]" "baz"]
```

But then I sorta wonder what the the `#sql/array` syntax is for. If all that's expected behavior, would you accept a PR that changes the test to use the `honeysql.types/array` function, so users like me don't get confused?

**Comment by seancorfield** [comment]
This sounds like a documentation / education issue (as well as a test update)?

**Comment by seancorfield** [comment]
I just looked over the tests and they use the `honeysql.types/array` function (aliased as `sql/array`). There are no examples of using the raw data reader types, as far as I can see. Does that address your question, or do you think more needs to be done @icambron ?

**Comment by icambron** [comment]
@seancorfield Yeah, looks like this has been fixed. Thanks for looking into it.
