### ISSUE TITLE
In a multi-column select, apply modifier to only one column

### ISSUE THREAD

**Issue by ilyabe** [jkk/honeysql#91]
I'd like to generate a query like this:

```
Select id, max(last_modified)
From some_table
Group by id
Order by max(last_modified)
```

but doing this with honeysql:

```
(-> (select :s.id, :s.last_modified)
     (modifiers :max)
     (from [:some_table s])
     (group :s.id)
     (order-by :s.last_modified))
```

Creates a query like `SELECT MAX s.id, s.last_modified...`

Is there a way to apply the modifier, in this case `max` to only one column, in this case `last_modified`?

**Comment by piranha** [comment]
`(select :s.id, (sql/call :max :s.last_modified))` should work.

**Comment by ilyabe** [comment]
Thank you, that's exactly what I was looking for!
