### ISSUE TITLE
support for schema-qualified object names (for PostgreSQL)

### ISSUE THREAD

**Issue by avandras** [jkk/honeysql#97]
I've tried to find this functionality, without success.  It would be very nice to have the ability to build a query like

    SELECT interesting_column
    FROM other_schema.important_table;

**Comment by ddellacosta** [comment]
It's totally do-able:

```clojure
> (require '[honeysql.core :as hsql])
nil
> (hsql/format
     (hsql/build :select :interesting_column :from :other_schema.important_table))
["SELECT interesting_column FROM other_schema.important_table"]
>
```

Is there another scenario where you're having trouble with this?

**Comment by avandras** [comment]
Hm, that works, thanks.  What I could not figure out is the same for function calls, based on this: 
```
(require '[honeysql.core :as sql]
         '[honeysql.helpers :refer :all])

(sql/format 
  (-> 
    (select :wal_bytes_from_zero) 
    (from :%zmon_utils.get_database_cluster_information)))
["SELECT wal_bytes_from_zero FROM zmon_utils(get_database_cluster_information)"]
```

**Comment by piranha** [comment]
How about `(sql/call :other_schema.get_database_cluster_information)`?

**Comment by ddellacosta** [comment]
Yeah, to follow on what @piranha is saying I'm not sure how to do it other than something like

```clojure
(hsql/format (hsql/build :select :wal_bytes_from_zero :from (hsql/call :other_schema.get_database_cluster_information)))
```

If I think of a way to use the `%` shorthand I'll add it to this issue...

**Comment by piranha** [comment]
I don't know, I prefer `sql/call` much more than `:%`, since then query starts to look like line noise, plus you can't pass more than one argument (and it needs to be a column!).

**Comment by avandras** [comment]
@piranha that's neat!  I even agree that ```sql/call``` is a cleaner solution - I've just missed this in the readme.  Thanks, guys!
