### ISSUE TITLE
Should (values) quote field names?

### ISSUE THREAD

**Issue by SevereOverfl0w** [jkk/honeysql#99]
Seeing something strange where that if the field names are strings, instead of keywords, they are quoted in the query, making the query invalid.

**Comment by ddellacosta** [comment]
Can you give us a concrete example of what you're talking about?

**Comment by SevereOverfl0w** [comment]
Sure.

```clojure
(defn update!
  [db filter game]
  (-> (update table)
      (sset game)
      (where filter)
      sql/format
      (#(j/execute! db %))))
```

If I pass in:
```clojure
{"name" "foo" "description" "bar"}
```
the sql generated is different to that of
```clojure
{:name "foo" :description "bar"}
```

Is that expected behaviour?

**Comment by jrdoane** [comment]
I think I can clarify here, @ddellacosta. He's talking about using strings as indentifiers for fields not working properly, I have a more clear cut example:
```clj
(honeysql.core/format {:select ["a" "b" "c"] :from ["Fruits"]} :quoting :ansi :allow-dashed-names? true)
;;; Yields
["SELECT ?, ?, ? FROM ?" "a" "b" "c" "Fruits"]
```

Whereas, using keywords behaves as expected:
```clj
(honeysql.core/format {:select [:a :b :c] :from [:Fruits]} :quoting :ansi :allow-dashed-names? true)
(honeysql.core/format {:select ['a 'b 'c] :from ['Fruits]} :quoting :ansi :allow-dashed-names? true)
;;; Both yield
["SELECT \"a\", \"b\", \"c\" FROM \"Fruits\""]
```

I'm not sure I would call this a bug though as I think there is an expectation that quoted field names will always be keywords or symbols in the query map.
